### ISSUE TITLE
Permissions issue on AWS, spawn EACCES

### ISSUE THREAD

**Issue by danteata** [alixaxel/chrome-aws-lambda#1]
I know this is pretty new, but was just wondering if you've been successful running on AWS lambda yet. I hit permissions error when running on AWS lambda. Could it be that the binary is neither statically linked nor built for the matching version of Amazon Linux as specified [here](https://aws.amazon.com/de/blogs/compute/running-executables-in-aws-lambda/)
 I'm running the latest version of this package `67.0.3372` with puppeteer `1.2.0`

Thank you.

**Comment by alixaxel** [comment]
Hi @danteata, altought the repository is new (and might change name[space]), I've been running these binaries in AWS Lambda successfully for quite some time, I just ran the example code in the README and the CloudWatch logs output a successful decompression of the binary: 

> chrome-aws-lambda Inflating 'chromium.br'.
> chrome-aws-lambda Finished inflating 'chromium.br' into '/tmp/chromium'.

I also get the correct output from Lambda (`"Example Domain"`).

As you can see on:

https://github.com/alixaxel/chrome-aws-lambda/blob/e9e50a08da0dd23089e9c61a4976b06798144271/_/ansible/inventory.ini#L6

I'm using the appropriate AMI image and the binary is also statically linked.

I assume you have transpiled your code to run Node 6.10 using Babel or similar?

**Comment by danteata** [comment]
@alixaxel confirmed, my codebase is transpiled to run Node 6.10 via Babel. Could that be the reason? Thanks for the quick reply.

**Comment by alixaxel** [comment]
It's unlikely as I'm doing the same.

Would you mind sharing some more details so we can get to the bottom of this issue? As I mentioned, the example code works just as expected, so I'm out of ideas with what I know.

**Comment by alixaxel** [comment]
How much memory have you given to your Lambda?

**Comment by danteata** [comment]
@alixaxel it strangely started working ok without any further updates to the deploy. I allocated ~1GB of memory.

**Comment by alixaxel** [comment]
Closing as it seems to be resolved.
