### ISSUE TITLE
[BUG] Deployment to GCP fails with "Cannot find module 'chrome-aws-lambda'"

### ISSUE THREAD

**Issue by sinapis** [alixaxel/chrome-aws-lambda#100]
## Environment
* `chrome-aws-lambda` Version: 2.0.2
* `puppeteer` / `puppeteer-core` Version: 2.1.1
* OS: ubuntu 18.04
* Node.js Version: 8.17
* Lambda / GCF Runtime: 1.4.0

## Expected Behavior
Deployment successful

## Current Behavior
This code is a very minor adjustment of the example code form this repo. It works perfectly fine locally but when deployed to GCP the following error occurs:

ERROR: (gcloud.functions.deploy) OperationError: code=3, message=Function failed on loading user code. Error message: Code in file index.js can't be loaded.
Did you list all required modules in the package.json dependencies?
Detailed stack trace: Error: Cannot find module 'chrome-aws-lambda'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/srv/index.js:3:18)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)

## Steps to Reproduce
```
git clone https://github.com/sinapis/chrome-aws-lambda-repro
cd chrome-aws-lambda-repro
npm i
npm run deploy
```

**Comment by alixaxel** [comment]
@sinapis This should work... It looks like it's an issue with `gcloud` CLI tool or with your deployment configuration. I believe you should get the same problem with a totally different package like `lodash`:

```typescript
import * as _ from "lodash";
import { Request, Response } from "express";

export const finalPrice = async (request: Request, response: Response) => {
  try {
    return response.send(_.words('Does this work?'));
  } catch (error) {
    return response.status(500).send(error);
  }
};
```

Also, you don't need `puppeteer`, just use `puppeteer-core`.

Additionally, if you upgrade your `nodejs8` runtime to 10 or 12, you shouldn't need `iltorb`.

---

Closing this for now, if it turns to be a problem specific to this package feel free to reopen.

**Comment by sinapis** [comment]
You are right. This has nothing to do with this package. I guess gcloud is buggy, since same function is deployed without error when using firebase. The strange thing is that gcloud works well with all the other packages I used. Thanks for your help and sorry for the inconvenience.

**Comment by MoMoWongHK** [comment]
@sinapis  Sorry, do you have any way to solve this, please?

**Comment by sinapis** [comment]
@MoMoWongHK I don't have access to the code I wrote to fix the problem but it was simply using firebase cli tool to deploy instead of gcloud
