### ISSUE TITLE
ETXTBSY

### ISSUE THREAD

**Issue by louisandkatherine** [alixaxel/chrome-aws-lambda#101]
Thanks for maintaining this awesome repo!

Just one thing, when I hit my lambda from a cold start I get this error:

`{ Error: spawn ETXTBSY
    at ChildProcess.spawn (internal/child_process.js:366:11)
    at Object.spawn (child_process.js:551:9)
    at BrowserRunner.start (/var/task/node_modules/puppeteer-core/lib/Launcher.js:77:30)
    at ChromeLauncher.launch (/var/task/node_modules/puppeteer-core/lib/Launcher.js:242:12) errno: 'ETXTBSY', code: 'ETXTBSY', syscall: 'spawn' }`

My code is as follows:

```
const browser = await chromium.puppeteer.launch({
    args: chromium.args,
    defaultViewport: chromium.defaultViewport,
    executablePath: await chromium.executablePath,
    headless: chromium.headless,
  });

  const page = await browser.newPage();

  const { body } = event;

  await page.setContent(body.html, { timeout: body.timeout || 10000 });

  await page.waitFor('body', { timeout: body.timeout || 10000 });

  const pdf = await page.pdf({
    format: 'A4',
    printBackground: true,
    margin: { top: '1cm', right: '1cm', bottom: '1cm', left: '1cm' },
    ...(body.options || {}),
  });
```

When I hit the lambda a second time its fine. My runtime is runtime: nodejs10.x

**Comment by alixaxel** [comment]
@louisandkatherine Is that the whole code?

Are you calling `chromium.executablePath` more than once?

**Comment by louisandkatherine** [comment]
It is wrapped in a middy function:

```
const Joi = require('joi');
const middy = require('middy');
const { httpErrorHandler } = require('middy/middlewares');
const requestValidator = require('./request-validator');
const apiKeyAuth = require('./api-key');
const base64Parser = require('./base64-parser');

const pdf = require('./pdf');

module.exports.pdf = middy(pdf)
  .use(apiKeyAuth())
  .use(base64Parser())
  .use(
    requestValidator({
      body: {
        html: Joi.string().required(),
        options: Joi.object().optional(),
        timeout: Joi.number().optional(),
      },
    })
  )
  .use(httpErrorHandler());
```

but i doubt thats causing an issue

Not calling chromium executable path twice

**Comment by alixaxel** [comment]
@louisandkatherine Can you share the contents of these?

```
const requestValidator = require('./request-validator');
const apiKeyAuth = require('./api-key');
const base64Parser = require('./base64-parser');

const pdf = require('./pdf');
```

**Comment by louisandkatherine** [comment]
You were right, got rid of middy and did everything inline and it all worked, no idea though why it failed using middy, thanks for helping!!!
