### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by nathan1uphealth** [alixaxel/chrome-aws-lambda#103]
## Environment
* `chrome-aws-lambda` Version: 2.1.1
* `puppeteer` / `puppeteer-core` Version: 2.1.1
* OS: mac 10.13.4
* Node.js Version: 10.x
* Lambda / GCF Runtime: Lambda 

## Expected Behavior
using page.waitForNavigation() should not cause errors when run in lambda. 
(Using the same code including waitForNavigation() locally with puppeteer does not cause errors and the tests pass)

EDIT: I get the same error locally if I do not include await before page.clickAndWaitForNavigation(). I dont know what this means for why the lambda is erroring  

## Current Behavior
invoking page.waitForNavigation() and/or any overload it is used in (i.e- page.clickAndWaitForNavigation() ) causes an error when deployed in Lambda 

## Possible Solution
Maybe the addition or removal of a flag when instantiating chromium.puppeteer.launch
currently have args set to chromium.args.   

## Outputted Lambda Runtime ERROR 
Error: Navigation failed because browser has disconnected!
      at CDPSession.LifecycleWatcher._eventListeners.helper.addEventListener (node_modules/puppeteer-core/lib/LifecycleWatcher.js:46:107)
      at CDPSession._onClosed (node_modules/puppeteer-core/lib/Connection.js:215:10)
      at Connection._onClose (node_modules/puppeteer-core/lib/Connection.js:138:15)
      at WebSocketTransport._ws.addEventListener.event (node_modules/puppeteer-core/lib/WebSocketTransport.js:48:22)
      at WebSocket.onClose (node_modules/ws/lib/event-target.js:124:16)
      at WebSocket.emitClose (node_modules/ws/lib/websocket.js:191:10)
      at Socket.socketOnClose (node_modules/ws/lib/websocket.js:850:15)
    -- ASYNC --
      at Frame.<anonymous> (node_modules/puppeteer-core/lib/helper.js:111:15)
      at Page.waitForNavigation (node_modules/puppeteer-core/lib/Page.js:692:49)
      at Page.<anonymous> (node_modules/puppeteer-core/lib/helper.js:112:23)
      at Page.Super.clickAndWaitForNavigation (node_modules/chrome-aws-lambda/source/puppeteer/lib/Page.js:21:10).

## Steps to Reproduce
The file below is being invoked by the handler which uses `lambda-mocha-runner`. `lambda-mocha-runner`'s functionality has been tested and validated for tests not using chrome-aws-lambda which leads me to believe it isnt what is causing the problem.

```javascript
const chai = require(`chai`);
const chaiHttp = require(`chai-http`);
const chromium = require('chrome-aws-lambda');
const config = require('../config.js');

chai.use(chaiHttp);
chai.should();

describe('Validating Patient App Functionality:', function() {
  this.timeout(210000);
  let page;
  let browser;

  before(async () => {
    browser = await chromium.puppeteer.launch({
      headless: false,
      args: chromium.args,
      defaultViewport: chromium.defaultViewport,
      executablePath: await chromium.executablePath,
    });
    page = await browser.newPage();
  });

  it('Logging into patient app', async () => {
    await page.goto(config.url);
    await page.waitUntilVisible('#login-form-login', 10000);
    await page.type('#login-form-login', `${config.user}`);
    await page.waitUntilVisible('#login-form-password', 10000);
    await page.type('#login-form-password', `${config.password}`);
    await page.clickAndWaitForNavigation('[name="login-button"]');
    page.url().should.equal('targetURL.com');
  });

  after(async () => {
    await browser.close();
    console.log('Browser Closed');
  });
});

```

**Comment by alixaxel** [comment]
@nathan1uphealth All the methods you're using should be well supported, so what you're seeing it's either caused by the specific page (`config.url`) or by some `chai` quirk (I also don't understand why you're using `chai-http` in your example).

Unfortunately I cannot provide support for how this package inter-operates with other packages.

If you'd like me to look deeper into this, please reopen this issue with a full repro (`config.js` contents).
