### ISSUE TITLE
[BUG] error while loading shared libraries: libnss3.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by timminkov** [alixaxel/chrome-aws-lambda#105]
## Environment
* `chrome-aws-lambda` Version: 2.1.1
* `puppeteer` / `puppeteer-core` Version: 2.1.1/2.1.1
* OS: Linux
* Node.js Version: 12.x
* Lambda / GCF Runtime: Linux

## Expected Behavior
Chrome should load.

## Current Behavior
```
{
    "errorType": "Error",
    "errorMessage": "Failed to launch the browser process!\n/tmp/chromium: error while loading shared libraries: libnss3.so: cannot open shared object file: No such file or directory\n\n\nTROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/master/docs/troubleshooting.md\n",
    "stack": [
        "Error: Failed to launch the browser process!",
        "/tmp/chromium: error while loading shared libraries: libnss3.so: cannot open shared object file: No such file or directory",
        "",
        "",
        "TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/master/docs/troubleshooting.md",
        "",
        "    at onClose (/var/task/node_modules/puppeteer-core/lib/Launcher.js:750:14)",
        "    at Interface.<anonymous> (/var/task/node_modules/puppeteer-core/lib/Launcher.js:739:50)",
        "    at Interface.emit (events.js:228:7)",
        "    at Interface.close (readline.js:402:8)",
        "    at Socket.onend (readline.js:180:10)",
        "    at Socket.emit (events.js:228:7)",
        "    at endReadableNT (_stream_readable.js:1185:12)",
        "    at processTicksAndRejections (internal/process/task_queues.js:81:21)"
    ]
}
```

Just started happening to me about an hour ago.  No changes to versions or the code that touches the browser, as far as I know. Has Amazon updated their environment?

**Comment by timminkov** [comment]
Hm, this seems to have been caused by adding `copy-webpack-plugin` to my project. Closing this. Sorry!

**Comment by santoshbachar** [comment]
> Hm, this seems to have been caused by adding `fs` and trying to copy fonts to `'/tmp/aws/.fonts'`. Closing this. Sorry!

How did you resolved the issue?

**Comment by timminkov** [comment]
I'm not sure unfortunately, but this code seems to work:
```
const fs = require('fs-extra');
await fs.copy(`./fonts`, '/tmp/aws/.fonts');
```

**Comment by alixaxel** [comment]
@timminkov FYI, `font()` method now supports local files too:

https://github.com/alixaxel/chrome-aws-lambda/blob/954ddb8989abf832a96f9f3586efd6e5ed7f2ca1/source/index.js#L48-L51
