### ISSUE TITLE
[BUG] Browser is not downloaded. Run "npm install" or "yarn install"

### ISSUE THREAD

**Issue by don-aot** [alixaxel/chrome-aws-lambda#106]
## Environment
* `chrome-aws-lambda` Version: ^2.1.1
* `puppeteer` / `puppeteer-core` Version: ^2.1.1
* OS: windows 
* Node.js Version: v10.15.0
* Lambda / GCF Runtime:

## Expected Behavior
Need to working as expected

## Current Behavior
Got following error "Browser is not downloaded. Run "npm install" or "yarn install""

## Steps to Reproduce
 while initializing the browser the above error occurs
Error in the following line 
`let browser = await chromium.puppeteer.launch({
      args: chromium.args,
      defaultViewport: chromium.defaultViewport,
      executablePath: await chromium.executablePath,
      headless: chromium.headless,
    });`

**Comment by gsouf** [comment]
Not an isolated case. Same here :+1:

**Comment by alixaxel** [comment]
@don-aot @gsouf Are you getting this on AWS Lambda? I recommend a read to this [wiki page](https://github.com/alixaxel/chrome-aws-lambda/wiki/HOWTO:-Local-Development).

**Comment by gsouf** [comment]
@alixaxel I'm getting this on my local machine, tried both of npm and yarn

**Comment by gsouf** [comment]
@alixaxel ok got it:

`Therefore the binary might not be compatible with your local system, making development trickier.`

I suggest you mention this on the readme as well as on this comment that is popular https://github.com/puppeteer/puppeteer/issues/3120#issuecomment-450575911.

**Comment by alixaxel** [comment]
@gsouf There's a section on the README about running locally, I guess most people just don't read it.

You can test the binary locally, you just have to make sure that you run it inside a host/container that shares the same architecture/OS as the one that's available on AWS Lambda.

There are already projects for this (lambdaci for instance) - other than that there's not much more I can do.

**Comment by alixaxel** [comment]
Which Linux distribution / version are you running?

**Comment by gsouf** [comment]
Nothing fancy, a pretty common Ubuntu 18.04.1 LTS

**Comment by gsouf** [comment]
I suggest you write it higher in the readme and also explicitely stating the same thing that you wrote in the wiki.

**Comment by alixaxel** [comment]
@gsouf Will consider that, thanks!

For Ubuntu LTS you should be able to run it locally, all you have to do is set the ENV variables.

**Comment by gsouf** [comment]
Confirm, adding env variables fixed.

**Comment by jagadeesh93** [comment]
@gsouf @alixaxel  I have the same issue . I am using chrome aws lambda for my serverless function . it was working fine previously now it is giving the above error. could you please tell what are those ENV variables ?

**Comment by gsouf** [comment]
@jagadeesh93 https://github.com/alixaxel/chrome-aws-lambda/wiki/HOWTO:-Local-Development

**Comment by hectare-agritech** [comment]
const chromium = require('chrome-aws-lambda')
const puppeteer = chromium.puppeteer

**Comment by jagadeesh93** [comment]
@hectare-agritech  @gsouf  Sorry guys.. The solution you give didn't worked for me

**Comment by alixaxel** [comment]
@jagadeesh93 Did you do `npm i puppeteer --save-dev`?
