### ISSUE TITLE
Chinese characters are displayed as blocks when printing To PDF in headless

### ISSUE THREAD

**Issue by yashutanna** [alixaxel/chrome-aws-lambda#108]
Hi Guys

firstly, thank you for a great library

Im not sure if i am posting this in the right forum as im not entirely sure where the issue lies

I am using chrome-aws-lmabda as a mechanism to headlessly navigate to one of my sites that is responsible for white-labelling content

however, when running the following snippet of code 

```
import chromium from 'chrome-aws-lambda';

export default async (url) => {
  const browser = await chromium.puppeteer.launch({
    args: chromium.args,
    defaultViewport: chromium.defaultViewport,
    executablePath: await chromium.executablePath,
    headless: true,
  });
  const page = await browser.newPage();
  page.emulateMedia('screen');
  await page.goto(url, { waitUntil: ['domcontentloaded', 'networkidle0'] });
  const height = await page.evaluate(
    // @ts-ignore
    () => document.documentElement.scrollHeight
  );

  await page.addStyleTag({
    content: '@page { size: auto; }',
  });
  
  return page.pdf({
    pageRanges: '1',
    printBackground: true,
    height: `${height * 1.1}px`
  });
};
```

i see that characters that are non-english are displayed as blocks

**this is what i see when i navigate to the URL in a normal browser on my laptop**
![image](https://user-images.githubusercontent.com/6696871/75867708-a987ef80-5e0f-11ea-9648-32677b508f97.png)

**and this is what i see when its rendered to a pdf using chrome-aws-lambda on the cloud lambda**
![image](https://user-images.githubusercontent.com/6696871/75867746-ba386580-5e0f-11ea-9d80-c36028a432aa.png)

I thought it may be the index.html of the white-label app that is the issue, but i think it looks fine:

```
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />
    <meta name="theme-color" content="#000000" />
    <link rel="manifest" href="%PUBLIC_URL%/manifest.json" />
    <title>White Labelled Documents</title>
  </head>
  <body>
    <noscript>You need to enable JavaScript to run this app.</noscript>
    <div id="root"></div>
  </body>
 
</html>```

## Environment
* `chrome-aws-lambda` Version: 2.1.1
* `puppeteer` / `puppeteer-core` Version: 2.1.1
* OS: MacOS
* Node.js Version: 10.15.1
* Lambda / GCF Runtime: Nodejs10.x

## Expected Behavior
should print chinese characters

## Current Behavior
prints chinese characters as blocks

**Comment by yashutanna** [comment]
I just ran across issue #94 

I have embedded my fonts as base64 - so i don't think its the same issue 🤔

**Comment by yashutanna** [comment]
I've ultimately settle for going down the following route:

set up a new lambda on AWS that handles the conversion of the URL to a pdf using this PR 

https://github.com/RafalWilinski/serverless-puppeteer-layers/pull/16

**Comment by alixaxel** [comment]
@yashutanna Apologies for the slow response.

The problem is definitively related to missing font faces with support for Chinese scripts.

These fonts are usually super big, so they should be installed on a need basis.
