### ISSUE TITLE
Loading default fonts

### ISSUE THREAD

**Issue by joelsmedberg** [alixaxel/chrome-aws-lambda#109]
Hi, 
Not sure if this is the right place to ask, 
I'm trying to get the standard webfonts to render into a pdf, but I assume none are installed by default using puppeteer core on lambda. Is there an easy way to get around this? I've tried to find a bundle with all websafe fonts.

Running version
    "chrome-aws-lambda": "2.1.1",
    "puppeteer-core": "2.1.1"

`const html = Hello World, no font family, defaults to Times New Roman
    p style="font-family:Times New Roman;">Hello World, Times New Roman
    p style="font-family:Arial;">Hello World, Arial
    p style="font-family:Helvetica;">Hello World, Helvetica
    p style="font-family:Courier;">Hello World, Courier
    p style="font-family:Verdana;">Hello World, Verdana
    p style="font-family:Tahoma;">Hello World, Tahoma
    p style="font-family:Arial Black;">Hello World, Arial Black
    p style="font-family:Comic Sans MS;">Hello World, Comic Sans MS
    p style="font-family:Georgia;">Hello World, Georgia
    p style="font-family:Impact;">Hello World, Impact
    p style="font-family:Palatino;">Hello World, Palatino
    p style="font-family:Bookman;">Hello World, Bookman;

const page = await browser.newPage();
await page.goto('data:text/html,' + html, { waitUntil: 'networkidle0' });
const pdf = await page.pdf({format: "A4"});
`
The results is that all lines come out with the same font regardless.

**Comment by alixaxel** [comment]
Hi @joelsmedberg - in a Lambda environment you don't have access to all these fonts.
Given that they would be dozens of MBs in size, it's unfeasible to have all of them by default.

By default you'll only get `DejaVu` on Node 8 and `Roboto` in Node >= 10.

_PS: I'm switching from `Roboto` to `Open Sans` in the upcoming release._

You can still install additional fonts by following the [instructions on the README](https://github.com/alixaxel/chrome-aws-lambda#fonts).

Hope that helps!
