### ISSUE TITLE
Failed to launch chrome on nodejs 12.x

### ISSUE THREAD

**Issue by don-aot** [alixaxel/chrome-aws-lambda#110]
## Environment
* `chrome-aws-lambda` Version:  ^2.1.1
* `puppeteer-core` Version: ^2.1.1
* OS:  Amazon Linux 2
* Node.js Version: nodejs12.x
* Lambda / GCF Runtime: 

## Expected Behavior
Run as expected 

## Current Behavior

Get the following error

  "Runtime.UnhandledPromiseRejection: Error: Failed to launch chrome!",
        "/tmp/chromium: error while loading shared libraries: libnss3.so: cannot open shared object file: No such file or directory",

## Steps to Reproduce
Code 
   const puppeteer = require('puppeteer-core');

`  const browser = await puppeteer.launch({
            args: chromium.args,
            defaultViewport: chromium.defaultViewport,
            executablePath: await chromium.executablePath,
            headless: chromium.headless,
        });
        const page = await browser.newPage();
        await page.setContent(renderedTemplate, {waitUntil: 'networkidle0'});`

**Comment by alixaxel** [comment]
@don-aot Still it seems that you're not running on Lambda: see this [wiki page](https://github.com/alixaxel/chrome-aws-lambda/wiki/HOWTO:-Local-Development).

**Comment by don-aot** [comment]
@alixaxel  

Yes, I got this error in the cloud watch logs. But the npm packages are coped from my local machine. Is it cause the above error?

**Comment by don-aot** [comment]
This issue is due to node js version issue

**Comment by chrismitchell** [comment]
@don-aot did you resolve the issue? Did you need to downgrade/upgrade node?

**Comment by andreafalzetti** [comment]
Any fix?

**Comment by pmakkar93** [comment]
> I solved by manually installing missing packages:
> 
> `sudo apt install -y gconf-service libasound2 libatk1.0-0 libc6 libcairo2 libcups2 libdbus-1-3 libexpat1 libfontconfig1 libgcc1 libgconf-2-4 libgdk-pixbuf2.0-0 libglib2.0-0 libgtk-3-0 libnspr4 libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 libxcomposite1 libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6 ca-certificates fonts-liberation libappindicator1 libnss3 lsb-release xdg-utils`

Can you please tell me on how to run this install command on my aws lambda function? Because I am facing the issue on my AWS Lambda function.

**Comment by alexdrans** [comment]
Fixed using runtime `nodejs10.x`

**Comment by cbosco** [comment]
I've found node14 supported with this approach:

https://github.com/alixaxel/chrome-aws-lambda/issues/193#issuecomment-781724065

Was getting this error until I packaged my own layer -- the public images seemed incompatible

**Comment by quangtuyendev** [comment]
> I solved by manually installing missing packages:
> 
> `sudo apt install -y gconf-service libasound2 libatk1.0-0 libc6 libcairo2 libcups2 libdbus-1-3 libexpat1 libfontconfig1 libgcc1 libgconf-2-4 libgdk-pixbuf2.0-0 libglib2.0-0 libgtk-3-0 libnspr4 libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 libxcomposite1 libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6 ca-certificates fonts-liberation libappindicator1 libnss3 lsb-release xdg-utils`

Only this solution works for me. Thanks
