### ISSUE TITLE
Failed to launch the browser process

### ISSUE THREAD

**Issue by don-aot** [alixaxel/chrome-aws-lambda#111]
## Environment
* `chrome-aws-lambda` Version: ^2.1.1
* `puppeteer` / `puppeteer-core` Version: ^2.1.1
* OS:  Amazon Linux 2
* Node.js Version: 12.x
* Lambda / GCF Runtime:

## Expected Behavior
Load HTML into the opened page and conveting into the pdf

## Current Behavior
Got following error 
"Error: Failed to launch the browser process!",
            "[0306/083156.482836:WARNING:resource_bundle.cc(427)] locale_file_path.empty() for locale ",
            "Fontconfig error: Cannot load default config file: No such file: (null)",
            "[0306/083156.522474:FATAL:platform_font_skia.cc(97)] Check failed: InitDefaultFont(). Could not find the default font",
            "#0 0x564c990e3939 <unknown>",
            "#1 0x564c99055443 <unknown>",
            "#2 0x564c990664d5 <unknown>",
            "#3 0x564c99d7ff2e <unknown>",
            "#4 0x564c99d8152b <unknown>",
            "#5 0x564c99d7542e <unknown>",
            "#6 0x564c98139e10 <unknown>",
            "#7 0x564c9825da2a <unknown>",
            "#8 0x564c97fa8f57 <unknown>",
            "#9 0x564c97fa87e1 <unknown>",
            "#10 0x564c97fa82b7 <unknown>",
            "#11 0x564c97f532b8 <unknown>",
            "#12 0x564c97f7b9b6 <unknown>",
            "#13 0x564c97f59b57 <unknown>",
            "#14 0x564c97f5945f <unknown>",
            "#15 0x564c9a7ea4e1 <unknown>",
            "#16 0x564c9917e6d7 <unknown>",
            "#17 0x564c9904d1f4 <unknown>",
            "#18 0x564c97cebb4f <unknown>",
            "#19 0x564c97374e77 <unknown>",
            "#20 0x564c97ed89fe <unknown>",
            "#21 0x564c990b70d9 <unknown>",
            "#22 0x564c99093a1b <unknown>",
            "#23 0x564c990a47ce <unknown>",
            "#24 0x564c990a4561 <unknown>",
            "#25 0x564c990fe279 <unknown>",
            "#26 0x564c990a5059 <unknown>",
            "#27 0x564c990815e2 <unknown>",
            "#28 0x564c97e27824 <unknown>",
            "#29 0x564c97e29372 <unknown>",
            "#30 0x564c9a7f2b88 <unknown>",
            "#31 0x564c9900f6bf <unknown>",
            "#32 0x564c9900f3fa <unknown>",
            "#33 0x564c9a700693 <unknown>",
            "#34 0x564c99008861 <unknown>",
            "#35 0x564c990517e5 <unknown>",
            "#36 0x564c990514ad <unknown>",
            "#37 0x7f7424b2d02a __libc_start_main",
            "#38 0x564c9730e8aa _start",
            "Task trace:",
            "#0 0x564c9904cd32 <unknown>",
            "#1 0x564c9904cd32 <unknown>",
            "",
            "Received signal 6",
            "#0 0x564c990e3939 <unknown>",
            "#1 0x564c99055443 <unknown>",
            "#2 0x564c990e3481 <unknown>",
            "#3 0x7f74258627e0 <unknown>",
            "#4 0x7f7424b3fae0 __GI_raise",
            "#5 0x7f7424b40f88 __GI_abort",
            "#6 0x564c990e2285 <unknown>",
            "#7 0x564c99066974 <unknown>",
            "#8 0x564c99d7ff2e <unknown>",
            "#9 0x564c99d8152b <unknown>",
            "#10 0x564c99d7542e <unknown>",
            "#11 0x564c98139e10 <unknown>",
            "#12 0x564c9825da2a <unknown>",
            "#13 0x564c97fa8f57 <unknown>",
            "#14 0x564c97fa87e1 <unknown>",
            "#15 0x564c97fa82b7 <unknown>",
            "#16 0x564c97f532b8 <unknown>",
            "#17 0x564c97f7b9b6 <unknown>",
            "#18 0x564c97f59b57 <unknown>",
            "#19 0x564c97f5945f <unknown>",
            "#20 0x564c9a7ea4e1 <unknown>",
            "#21 0x564c9917e6d7 <unknown>",
            "#22 0x564c9904d1f4 <unknown>",
            "#23 0x564c97cebb4f <unknown>",
            "#24 0x564c97374e77 <unknown>",
            "#25 0x564c97ed89fe <unknown>",
            "#26 0x564c990b70d9 <unknown>",
            "#27 0x564c99093a1b <unknown>",
            "#28 0x564c990a47ce <unknown>",
            "#29 0x564c990a4561 <unknown>",
            "#30 0x564c990fe279 <unknown>",
            "#31 0x564c990a5059 <unknown>",
            "#32 0x564c990815e2 <unknown>",
            "#33 0x564c97e27824 <unknown>",
            "#34 0x564c97e29372 <unknown>",
            "#35 0x564c9a7f2b88 <unknown>",
            "#36 0x564c9900f6bf <unknown>",
            "#37 0x564c9900f3fa <unknown>",
            "#38 0x564c9a700693 <unknown>",
            "#39 0x564c99008861 <unknown>",
            "#40 0x564c990517e5 <unknown>",
            "#41 0x564c990514ad <unknown>",
            "#42 0x7f7424b2d02a __libc_start_main",
            "#43 0x564c9730e8aa _start",
            "  r8: 0000000000000000  r9: 00007ffc7f669450 r10: 0000000000000008 r11: 0000000000000246",
            " r12: 00007ffc7f66a710 r13: 00007ffc7f6696f0 r14: 00007ffc7f66a718 r15: aaaaaaaaaaaaaaaa",
            "  di: 0000000000000002  si: 00007ffc7f669450  bp: 00007ffc7f6696a0  bx: 0000000000000006",
            "  dx: 0000000000000000  ax: 0000000000000000  cx: 00007f7424b3fae0  sp: 00007ffc7f669450",
            "  ip: 00007f7424b3fae0 efl: 0000000000000246 cgf: 002b000000000033 erf: 0000000000000000",
            " trp: 0000000000000000 msk: 0000000000000000 cr2: 0000000000000000",
            "[end of stack trace]",
            "Calling _exit(1). Core file will not be generated.",
            "",
            "",
            "TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/master/docs/troubleshooting.md",
            "",
            "    at onClose (/var/task/node_modules/puppeteer-core/lib/Launcher.js:750:14)",
            "    at Interface.<anonymous> (/var/task/node_modules/puppeteer-core/lib/Launcher.js:739:50)",
            "    at Interface.emit (events.js:228:7)",
            "    at Interface.close (readline.js:402:8)",
            "    at Socket.onend (readline.js:180:10)",
            "    at Socket.emit (events.js:228:7)",
            "    at endReadableNT (_stream_readable.js:1185:12)",
            "    at processTicksAndRejections (internal/process/task_queues.js:81:21)"
        ]
    }

## Steps to Reproduce
Code  : 
`const browser = await chromium.puppeteer.launch({
            args: chromium.args,
            defaultViewport: chromium.defaultViewport,
            executablePath: await chromium.executablePath,
            headless: chromium.headless,
        });
        const page = await browser.newPage();
        await page.setContent(renderedTemplate, {waitUntil: 'networkidle0'});
        const buffer = await page.pdf({
            format: "A4", printBackground: true, margin: {
                "top": "6mm",
                "bottom": "6mm",
            }
        });
        browser.close();`

**Comment by bschelling** [comment]
same issue here. tried to add `-disable-software-rasterizer` and `-disable-software-rasterizer` to no avail, otherwise using exactly the example code. output from cloudwatch logs is as follows.

`START RequestId: f6ebc2b7-ee6e-44e3-ad87-d84fd4e78c85 Version: $LATEST
2020-03-07T12:00:32.771Z	f6ebc2b7-ee6e-44e3-ad87-d84fd4e78c85	INFO	[
  '--disable-background-timer-throttling',
  '--disable-breakpad',
  '--disable-client-side-phishing-detection',
  '--disable-cloud-import',
  '--disable-default-apps',
  '--disable-dev-shm-usage',
  '--disable-extensions',
  '--disable-gesture-typing',
  '--disable-hang-monitor',
  '--disable-infobars',
  '--disable-notifications',
  '--disable-offer-store-unmasked-wallet-cards',
  '--disable-offer-upload-credit-cards',
  '--disable-popup-blocking',
  '--disable-print-preview',
  '--disable-prompt-on-repost',
  '--disable-setuid-sandbox',
  '--disable-speech-api',
  '--disable-sync',
  '--disable-tab-for-desktop-share',
  '--disable-translate',
  '--disable-voice-input',
  '--disable-wake-on-wifi',
  '--disk-cache-size=33554432',
  '--enable-async-dns',
  '--enable-simple-cache-backend',
  '--enable-tcp-fast-open',
  '--enable-webgl',
  '--hide-scrollbars',
  '--ignore-gpu-blacklist',
  '--media-cache-size=33554432',
  '--metrics-recording-only',
  '--mute-audio',
  '--no-default-browser-check',
  '--no-first-run',
  '--no-pings',
  '--no-sandbox',
  '--no-zygote',
  '--password-store=basic',
  '--prerender-from-omnibox=disabled',
  '--use-gl=swiftshader',
  '--use-mock-keychain',
  '--memory-pressure-off',
  '--single-process',
  '--disable-software-rasterizer',
  '--disable-gpu'
]
2020-03-07T12:00:36.241Z	f6ebc2b7-ee6e-44e3-ad87-d84fd4e78c85	ERROR	Invoke Error 	
{
    "errorType": "Error",
    "errorMessage": "Navigation failed because browser has disconnected!",
    "stack": [
        "Error: Navigation failed because browser has disconnected!",
        "    at CDPSession.<anonymous> (/var/task/node_modules/puppeteer-core/lib/LifecycleWatcher.js:46:107)",
        "    at CDPSession.emit (events.js:223:5)",
        "    at CDPSession._onClosed (/var/task/node_modules/puppeteer-core/lib/Connection.js:215:10)",
        "    at Connection._onClose (/var/task/node_modules/puppeteer-core/lib/Connection.js:138:15)",
        "    at WebSocket.<anonymous> (/var/task/node_modules/puppeteer-core/lib/WebSocketTransport.js:48:22)",
        "    at WebSocket.onClose (/var/task/node_modules/ws/lib/event-target.js:124:16)",
        "    at WebSocket.emit (events.js:223:5)",
        "    at WebSocket.emitClose (/var/task/node_modules/ws/lib/websocket.js:191:10)",
        "    at Socket.socketOnClose (/var/task/node_modules/ws/lib/websocket.js:850:15)",
        "    at Socket.emit (events.js:223:5)",
        "  -- ASYNC --",
        "    at Frame.<anonymous> (/var/task/node_modules/puppeteer-core/lib/helper.js:111:15)",
        "    at Page.goto (/var/task/node_modules/puppeteer-core/lib/Page.js:672:49)",
        "    at Page.<anonymous> (/var/task/node_modules/puppeteer-core/lib/helper.js:112:23)",
        "    at Runtime.exports.handler (/var/task/index.js:21:16)",
        "    at processTicksAndRejections (internal/process/task_queues.js:94:5)"
    ]
}

END RequestId: f6ebc2b7-ee6e-44e3-ad87-d84fd4e78c85
REPORT RequestId: f6ebc2b7-ee6e-44e3-ad87-d84fd4e78c85	Duration: 3497.54 ms	Billed Duration: 3500 ms	Memory Size: 3008 MB	Max Memory Used: 444 MB	Init Duration: 168.26 ms	`

**Comment by Sheryorov** [comment]
It same for me

**Comment by Sheryorov** [comment]
I changed memory in lambda service to 512 mb and its work for me.

**Comment by alixaxel** [comment]
@don-aot Without `renderedTemplate` I cannot reproduce your example.
