### ISSUE TITLE
[BUG] Load lambda's local font file

### ISSUE THREAD

**Issue by bendadaniel** [alixaxel/chrome-aws-lambda#112]
Hi,
is there some possibility how to load "local" font file uploaded in zip package (with serverless)?

Something like: `await chromium.font('/var/task/fonts/Montserrat-Regular.ttf');`

Fonts folder is uploaded to lambda in ZIP file and path is valid. (I can read and printcontent of ttf file to console, so there is no problem with TTF file).

Chromium returns ` Invalid URL: /var/task/fonts/Montserrat-Regular.ttf` so is there any other function for local files or this usecase is not possible?

PS: Is there any other way how to load fonts? For example if I want screenshot webpage, where I dont know which fonts are used on page (google fonts, @font-face or something)

Thanks

**Comment by Zeeeeta** [comment]
Yes, being able to support local font would be cool, so that we can package it into layer, and save bandwidth from the host/CDN every time a Lambda container is created, while local loading should be faster as well.

**Comment by alixaxel** [comment]
@bendadaniel @Zeeeeta Good idea!
