### ISSUE TITLE
Recommended usage for overloaded methods using TS?

### ISSUE THREAD

**Issue by TylerLH** [alixaxel/chrome-aws-lambda#114]
Any tips on how to best use the overloaded `Page` & `Frame` methods from this package in TypeScript? Right now I'm just tacking methods on in a new type myself but it's pretty hacky -- curious if anyone else has run into this and what approaches they've taken. Maybe I'm missing something ridiculously simple?

Would it be useful for this package to expose its own extended `Page` and `Frame` type definitions based off the ones from `puppeteer` and `puppeteer-core`?

**Comment by alixaxel** [comment]
Hi @TylerLH!

Since the newest version (3.0.4) of puppeteer is fully TS-aware, I'm also very keen on adding typings.

I will be following up on this tomorrow.

**Comment by TylerLH** [comment]
Hi @alixaxel, that's great to hear! Please feel free to ping me if I can help in any way.

**Comment by G-Rath** [comment]
@TylerLH I've made a PR that should fix this - you can test it locally if you wish by replacing the contents of `node_modules/chrome-aws-lambda/source/index.d.ts` with the typings in #126.

Let me know if that works for you :)

**Comment by alixaxel** [comment]
Typings should be fully provided now.
