### ISSUE TITLE
chrome-aws-lambda causing lambda to timeout 

### ISSUE THREAD

**Issue by EXPEpaher** [alixaxel/chrome-aws-lambda#115]
## Environment
* `chrome-aws-lambda` Version:2.1.1
* `puppeteer` / `puppeteer-core` Version:2.1.1
* OS:Amazon Linux 2
* Node.js Version: 10.x
* Lambda / GCF Runtime: nodejs10.x

## Expected Behavior
I am setting up a new aws lambda function for lighthouse audits. My team already has an aws lambda function that does exactly that. 

The configuration for this old & new lambda function is,
```
name: old-aws-lambda
nodejs8.10
2mins timeout
2048MB
61.5MB zip file size
us-west-2

"lighthouse": "4.3.1",
"@serverless-chrome/lambda": "1.0.0-55"
```

```
name: new-aws-lambda
nodejs10.x
15mins timesout
3008MB
60.3MB zip file size
us-east-1 

"lighthouse": "4.3.1",
"chrome-aws-lambda": "2.1.1"
"chrome-launcher": "0.13.0"
"puppeteer-core": "2.1.1"
```

## Current Behavior
My observation using the old vs new aws lambda is that the new aws lambda takes much longer to finish running. If I try to run a lighthouse audit for a page that is heavy the old aws lambda function finishes in ~80k milliseconds. **However, for the same URL on the new aws lambda the audit doesnt complete.** And if I try to load a lightweight page on the new lambda, the audit completes in time (18s). The configuration (timeout and memory) of the new lambda is better, yet degraded performance. I cannot figure out the root cause of this issue. I could use some inputs please, are other people experiencing this kind of slowness when using chrome-aws-lambda?

**Comment by alixaxel** [comment]
@EXPEpaher In the end both `@serverless-chrome/lambda` and `chrome-aws-lambda` are just providing the compiled Chromium binaries, the only difference is the the former is outdated.

In terms of environment, `nodejs10.x` requires a bit more patching and that could account for an extra 500ms perhaps (when in a cold state), but that doesn't explain the slowdown you're claiming.

Without a complete repro however, I'm afraid I cannot help you further.
