### ISSUE TITLE
[BUG] Failing to run on AWS lambda but working fine on local

### ISSUE THREAD

**Issue by ab73863** [alixaxel/chrome-aws-lambda#119]
## Environment
* `chrome-aws-lambda` Version: 2.1.1
* `puppeteer` / `puppeteer-core` Version: 2.1.1
* OS:
* Node.js Version: 12.x
* Lambda / GCF Runtime: Lambda

## Expected Behavior
Execute successfully on Lambda

## Current Behavior
Failed to execute on lambda with following error. 
`2020-04-08T02:52:20.302Z	7a804797-a80b-4f61-be2f-a4e2570afb32	ERROR	Unhandled Promise Rejection 	
{
    "errorType": "Runtime.UnhandledPromiseRejection",
    "errorMessage": "Error: Browser is not downloaded. Run \"npm install\" or \"yarn install\"",
    "reason": {
        "errorType": "Error",
        "errorMessage": "Browser is not downloaded. Run \"npm install\" or \"yarn install\"",
        "stack": [
            "Error: Browser is not downloaded. Run \"npm install\" or \"yarn install\"",
            "    at ChromeLauncher.launch (/var/task/node_modules/puppeteer-core/lib/Launcher.js:236:15)",
            "    at async puppeteer.handle (/var/task/node_modules/@kumologica/kumologica-contrib-puppeteer/lib/puppeteer.js:22:8)"
        ]
    },
    "promise": {},
    "stack": [
        "Runtime.UnhandledPromiseRejection: Error: Browser is not downloaded. Run \"npm install\" or \"yarn install\"",
        "    at process.<anonymous> (/var/runtime/index.js:35:15)",
        "    at process.emit (events.js:311:20)",
        "    at processPromiseRejections (internal/process/promises.js:209:33)",
        "    at processTicksAndRejections (internal/process/task_queues.js:98:32)"
    ]
}`

## Possible Solution
None

## Steps to Reproduce

Use below snippet of code.
`const chromium = require('chrome-aws-lambda');
      console.log("chromium.headless--"+chromium.headless)
      console.log("---"+this.operation)
       console.log("executable path"+chromium.executablePath)
       await chromium.puppeteer.launch({
          //  args: chromium.args,
          //  defaultViewport: chromium.defaultViewport,
          //  executablePath: await chromium.executablePath,
          //  headless: chromium.headless
        }).then((browser) => {
          msg.test = {
            browser
          }
          this.send(msg)
        })`

**Comment by ab73863** [comment]
Issue resolved. Missed to pass the executable path configuration during the launch.
Closing the ticket.

**Comment by G-Rath** [comment]
@ab73863 were you able to get your chrome working?

I'm just getting "Failed to launch the browser process!".

Unfortunately this repo seems to have gone a bit quiet, and doesn't have much troubleshooting documentation :/

**Comment by ab73863** [comment]
@G-Rath I am able to run the chromium-aws-lambda. Initially faced some hiccups but after some trial error was able to make it run.

**Comment by G-Rath** [comment]
@ab73863 thanks for the quick response.

Mine seems to actually have come right - here's hoping it continues :joy:

**Comment by Sagnik-Chaudhuri** [comment]
> Issue resolved. Missed to pass the executable path configuration during the launch.
> Closing the ticket.

Didn't quite get it. Could you please elaborate?

**Comment by G-Rath** [comment]
@Sagnik-Chaudhuri the `chromium.executablePath` property is actually a static getter on a class that triggers the extracting of the chrome binary.

Hence you need to explicitly provide the executablePath property when calling launch, for example:

```
import * as chromium from 'chrome-aws-lambda';
import type puppeteer from 'puppeteer-core';

export const launchBrowser = async ({
  extraArgs,
  width,
  height
}: { extraArgs?: string[]; width?: number; height?: number } = {}): Promise<
  puppeteer.Browser
> =>
  chromium.puppeteer.launch({
    args: [...chromium.args, ...(extraArgs ?? [])],
    defaultViewport: {
      ...chromium.defaultViewport,
      width: width ?? chromium.defaultViewport.width,
      height: height ?? chromium.defaultViewport.height
    },
    executablePath: await chromium.executablePath,
    headless: chromium.headless
  });
```

**Comment by Sagnik-Chaudhuri** [comment]
@G-Rath got it.Thanks :)

**Comment by Sagnik-Chaudhuri** [comment]
Hi @G-Rath , could you help me out with this too?
I have something like this `const executablePath = event.isOffline
    ? '../node_modules/puppeteer/.local-chromium/linux-722234'
    : await chromium.executablePath;`
Now, whenever I run `sls offline start` and make a post request through Postman, I get the following error:
`Failure: Failed to launch the browser process! spawn ../node_modules/puppeteer/.local-chromium/linux-722234 ENOENT`
As far as I understand, the path that I have provided for local chromium seems to be incorrect. 
This path is the same one which I get after I npm install puppeteer and it says something like:
`Chrome downloaded to {path_name}`
Where am I getting wrong?

**Comment by G-Rath** [comment]
Try passing `null` instead of your own path :)
