### ISSUE TITLE
Update to Puppeteer 3.0.0

### ISSUE THREAD

**Issue by ryanblock** [alixaxel/chrome-aws-lambda#120]
https://github.com/puppeteer/puppeteer/releases/tag/v3.0.0

Please and thank you! 💕

**Comment by bestplay9384** [comment]
@alixaxel there is also version 3.0.1 of puppeteer and it looks like it uses the same chromium version as 3.0.0 version :)

**Comment by NikolaiT** [comment]
Anyone compiled the most recent chromium binary for AWS and GCP ?

**Comment by ryanblock** [comment]
@NikolaiT:
- Lambda: https://github.com/alixaxel/chrome-aws-lambda/tree/master/_/ansible
- GCP: not sure why you're asking about GCP re. this project, this is pretty clearly just built for AWS Lambda

**Comment by StevenVeshkini** [comment]
+1. It's been a while since this issue was opened and there has been no progress. Does anyone have instructions on how to do this oneself?

**Comment by ryanblock** [comment]
@StevenVeshkini I posted the link above, again: https://github.com/alixaxel/chrome-aws-lambda/tree/master/_/ansible

**Comment by steida** [comment]
Maybe it's time to try Playwright (version 1 today) https://github.com/JupiterOne/playwright-aws-lambda

**Comment by fartbagxp** [comment]
Hi, I was able to run the ansible code, but I could use some eyes on validation.
I created a fork in #125, and I welcome anybody who has the time to try it out for v3.0.0 and above since they all align to the same chrome build.

**Comment by ryanblock** [comment]
Looks like @alixaxel has not been active on GitHub since before the pandemic. Alix, wherever you are, I hope you're well.

In the mean time, I'm starting to assume this project is safe to be considered abandoned indefinitely. I'm thinking maybe time to fork and see if this thing can run in GitHub Actions?

**Comment by alixaxel** [comment]
@ryanblock v3.0.4 just released, sorry about the delay but work has kept me extra busy lately.

@fartbagxp I had to tweak around some build flags to investigate some potential bugs and ended up recompiling Chromium several times, in the end the hash is exactly the same as yours tho. Thanks a lot!

**Comment by ryanblock** [comment]
Great news @alixaxel, glad you’re well!

I’m still wondering if the build process could be automated in GitHub actions?

**Comment by fartbagxp** [comment]
@alixaxel welcome back!
I was asked to add `libgbm-devel` to the build as part of the package dependency - for #125, can you check if that'll be necessary. I looked over the puppeteer bugs and it sounded like Google Cloud Functions (GCF) will fail without it.

Thanks!

**Comment by alixaxel** [comment]
@ryanblock I think it could, but that's something that I haven't spent much time looking at.

The whole process takes over an hour to finish, today I pushed some optimizations to the Ansible playbook to be able to reuse an AMI image with Chromium Git history already pre-fetched.

**Comment by alixaxel** [comment]
@fartbagxp I will confirm tomorrow.

The fact that you included `libgbm-devel` and I didn't, and both of our binaries yield exactly the same hash means that the library was not linked / included. Maybe because `libgbm-devel` -> `libgbm1`?

**Comment by fartbagxp** [comment]
Nope, the `swiftshader.tar.br` MD5 is different. 
Yours is yielding `9bbdbfd81897fa24397abfd4137fd5c5`, mine is `5570df5549a9faaebb3b2a3d4cbd4e84`
