### ISSUE TITLE
A method for caching resources [REQUEST]

### ISSUE THREAD

**Issue by ali-habibzadeh** [alixaxel/chrome-aws-lambda#129]
## What would you like to have implemented?
When used at scale (e.g. crawling the web) it is important to not request resources more than once. Would be nice to have a recipe to share user data. Like ability to integrate with Proxy cache, AWS caching services or some generic implementation.

Bonus would be to have a way to grouping caches so provide isolation between jobs. 

## Why would it be useful?
It would substantially reduce the overhead on chrome requests running.

**Comment by alixaxel** [comment]
@ali-habibzadeh Chromium already makes use of browser cache (on `/tmp`), so the same Lambda will not re-fetch resources it doesn't need to. I feel like adding a caching layer external to Lambda would not only be too opinionated but would also not be super beneficial (as it also would involve the network).

**Comment by ali-habibzadeh** [comment]
> @ali-habibzadeh Chromium already makes use of browser cache (on `/tmp`), so the same Lambda will not re-fetch resources it doesn't need to. I feel like adding a caching layer external to Lambda would not only be too opinionated but would also not be super beneficial (as it also would involve the network).

After some thoughts on my side I agree with you. This is more suited so small number invocations and for that purpose /tmp/ is just fine.
