### ISSUE TITLE
chrome-aws-lambda layer available for Python Language??

### ISSUE THREAD

**Issue by mgsaranraj87** [alixaxel/chrome-aws-lambda#130]
## What would you like to have implemented?

Can you help me getting the chrome version for python language to be used in AWS Lambda or you can guide me to right place where i can find chrome for python.

## Why would it be useful?
it will help alot of person who wants to use chrome in AWS lambda with Python.

**Comment by csreddy** [comment]
This would be very useful. Thanks for your work.

**Comment by alixaxel** [comment]
@mgsaranraj87 You can still use the binary that ships with this package:

```
curl --output chromium.br --silent https://raw.githubusercontent.com/alixaxel/chrome-aws-lambda/master/bin/chromium.br
```

And then decompress it with Brotli:

```
brotli --decompress --rm chromium.br
```

You can then use the binary to create your own Lambda Layer and use it with Python.

PS: You might also need to provision the rest of the stuff under [`/bin`](https://github.com/alixaxel/chrome-aws-lambda/tree/master/bin).
