### ISSUE TITLE
[REQUEST] Update to Puppeteer 3.1.X

### ISSUE THREAD

**Issue by bestplay9384** [alixaxel/chrome-aws-lambda#134]
Hey @alixaxel, new puppeteer version got released yesterday (again sic!).

- Puppeteer 3.1.0
- Chromium 83.0.4103.0 (r756035) (we have 2 versions up, wow - any big changes?)

https://github.com/puppeteer/puppeteer/releases/tag/v3.1.0

Can we update to new version? 🥇

**Comment by alixaxel** [comment]
It's coming today. :slightly_smiling_face:

**Comment by alixaxel** [comment]
@bestplay9384 Version 3.1.0 just released. :tada:
