### ISSUE TITLE
[BUG] Timezone override is already in effect

### ISSUE THREAD

**Issue by phiferd** [alixaxel/chrome-aws-lambda#137]
## Environment
* `chrome-aws-lambda` Version: 3.1.0
* `puppeteer` / `puppeteer-core` Version: 3.1.0
* OS: Linux
* Node.js Version: 12.x
* Lambda / GCF Runtime: `AWS_Lambda_nodejs12.x`

## Expected Behavior

browser.newPage should work

## Current Behavior

browser.newPage throws an exception. It looks like the new Page.js override is causing this issue.

## Steps to Reproduce

```js
const chromium = require('chrome-aws-lambda');

exports.handler = async (event, context, callback) => {
  let result = null;
  let browser = null;

  try {
    browser = await chromium.puppeteer.launch({
      args: chromium.args,
      defaultViewport: chromium.defaultViewport,
      executablePath: await chromium.executablePath,
      headless: chromium.headless,
      ignoreHTTPSErrors: true,
    });

    let page1 = await browser.newPage();

   // throws an exception here
    let page2 = await browser.newPage();

    await page.goto(event.url || 'https://example.com');

    result = await page.title();
  } catch (error) {
    return callback(error);
  } finally {
    if (browser !== null) {
      await browser.close();
    }
  }

  return callback(null, result);
};
```

## Possible Solution

Seems like emulateTimezone only needs to be called once per Browser instance, not once per page.  Not sure why the client is so unforgiving.

**Comment by alixaxel** [comment]
Thanks for the report @phiferd, I missed this detail (it's not documented on pptr anywhere AFAIK).

Just published a new patch version addressing this.
