### ISSUE TITLE
Suddenly not loading css and img resources

### ISSUE THREAD

**Issue by filenda** [alixaxel/chrome-aws-lambda#139]
It was all working pretty nice! Until today. Now only images from s3 are loaded but all external css, icon and images are not!

I have a service that receives an base64 encoded html payload (so it can easily be sent as json), converts it back to utf8 to finally set this as the puppeteer page content.

I double checked if utf8 html was wrong and it worked nicely saving the content as test.html and opening in chrome.

Coincidence or not, this same response in Postman preview mode is not loading css and img too

**Comment by alixaxel** [comment]
@filenda Can you share any sort of repro or URL I can look at?

**Comment by filenda** [comment]
@alixaxel tks for getting back to me! I've come to realize that it was something to do with SSL certificate that was expired/not valid from the host we were grabbing the assets. Uploaded the file to an S3 public bucket and voilá. I know there's a know property to ignore ssl/https errors, will try that too.
