### ISSUE TITLE
[REQUEST] Update Puppeteer to 3.3.X

### ISSUE THREAD

**Issue by GitRubb** [alixaxel/chrome-aws-lambda#141]
## What would you like to have implemented?
Please update to Puppeteer 3.3.X

**Comment by steida** [comment]
Puppeteer 5 pls

**Comment by shukhero1** [comment]
Puppeteer 5.1.0 got published 2 days ago

**Comment by alixaxel** [comment]
Sorry people, I've been busy. All these versions are now published.
