### ISSUE TITLE
[BUG] get an error `Could not find browser revision 756035`.

### ISSUE THREAD

**Issue by zhaoyi0113** [alixaxel/chrome-aws-lambda#143]
I am deploying typescript to AWS lambda nodejs12 and got this error when running the lambda: `"errorMessage": "Error: Could not find browser revision 756035. Run \"npm install\" or \"yarn install\" to download a browser binary.",`.

the package json file has below dependencies:

```

{
  "name": "properties-scrapy",
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT",
  "dependencies": {
    "aws-lambda": "^1.0.6",
    "chrome-aws-lambda": "^3.1.1",
    "puppeteer-core": "^3.1.0"
  },
  "devDependencies": {
    "@types/aws-lambda": "^8.10.55",
    "@types/node-fetch": "^2.5.7",
    "@types/puppeteer": "^3.0.0",
    "jest": "^26.0.1",
    "puppeteer": "^3.3.0",
    "typescript": "^3.9.5"
  },
  "scripts": {
    "build": "tsc --build tsconfig.json"
  }
}

```

my source code is importing like: `import chromium from 'chrome-aws-lambda';`

Why does it complain about browser revision? How can I specify a supported revision number?

**Comment by JimmyLaurent** [comment]
I had the same issue. On your lambda function, try to remove "puppeteer" folder from "node_modules" if you have it.

**Comment by zhaoyi0113** [comment]
I don't have `puppeteer` on lambda. I use `yarn install --prod` to exclude devDependencies.

**Comment by jawadst** [comment]
We are seeing the same issue, also installing with `NODE_ENV=production npm ci` so that there is no `puppeteer` in the Lambda package.

We are using puppeteer-core@3.1.0 and chrome-aws-lambda@3.1.1

**Comment by jawadst** [comment]
@zhaoyi0113 I found what the issue was on our side: make sure that you pass the `executablePath` `from chrome-aws-lambda` to puppeteer.

Our code was:
```js
browser = await chromium.puppeteer.launch({
      args: chromium.args,
      defaultViewport: chromium.defaultViewport,
      headless: chromium.headless,
      ignoreHTTPSErrors: true,
    });
```

We added the `executablePath` from the doc:
```js
browser = await chromium.puppeteer.launch({
      args: chromium.args,
      defaultViewport: chromium.defaultViewport,
      executablePath: await chromium.executablePath,
      headless: chromium.headless,
      ignoreHTTPSErrors: true,
    });
```

The chromium executable is added to the env when `chromium.executablePath` is called so that part is important. Hope it was the same issue for you :)

**Comment by zhaoyi0113** [comment]
@jawadst you are right, your solution fix my problem. Thanks.

**Comment by firnandessicepat** [comment]
Hi, I am still having this problem with dependencies:

```
"chrome-aws-lambda": "^3.1.1",
"puppeteer-core": "^3.1.0"
```

Running code with this way:
```
browser = await chromium.puppeteer.launch({
      args: chromium.args,
      defaultViewport: chromium.defaultViewport,
      executablePath: await chromium.executablePath,
      headless: chromium.headless,
      ignoreHTTPSErrors: true,
    });
```

Error details:
`ERROR	Error: Could not find browser revision 756035. Run "npm install" or "yarn install" to download a browser binary.
    at ChromeLauncher.launch (/var/task/node_modules/puppeteer-core/lib/Launcher.js:59:23)
    at async /var/task/index.js:120:27
2020-07-21T23:57:04.540Z	12d6dfe8-8b45-454b-8933-14bf941b64a6	ERROR	Error: Could not find browser revision 756035. Run "npm install" or "yarn install" to download a browser binary.
    at ChromeLauncher.launch (/var/task/node_modules/puppeteer-core/lib/Launcher.js:59:23)
    at async /var/task/index.js:120:27
2020-07-21T23:57:04.541Z	12d6dfe8-8b45-454b-8933-14bf941b64a6	ERROR	Invoke Error 	{"errorType":"Error","errorMessage":"Could not find browser revision 756035. Run \"npm install\" or \"yarn install\" to download a browser binary.","stack":["Error: Could not find browser revision 756035. Run \"npm install\" or \"yarn install\" to download a browser binary.","    at ChromeLauncher.launch (/var/task/node_modules/puppeteer-core/lib/Launcher.js:59:23)","    at async /var/task/index.js:120:27"]}
END RequestId: 12d6dfe8-8b45-454b-8933-14bf941b64a6
REPORT RequestId: 12d6dfe8-8b45-454b-8933-14bf941b64a6	Duration: 283.84 ms	Billed Duration: 300 ms	Memory Size: 3008 MB	Max Memory Used: 132 MB	Init Duration: 890.91 ms	`

I use aws lambda nodejs 12x runtime.

Please help thanks.

**Comment by zachguo** [comment]
If you run into this issue locally, you probably need to install `puppeteer` as dev dependency.
https://github.com/alixaxel/chrome-aws-lambda/wiki/HOWTO:-Local-Development#workaround

**Comment by JonathanWbn** [comment]
In the end, running this command fixed it for me:
```shell
node node_modules/puppeteer-core/install.js
```

🤷‍♂️

**Comment by GeoBrodas** [comment]
> In the end, running this command fixed it for me:
> 
> ```shell
> node node_modules/puppeteer-core/install.js
> ```
> 
> 🤷‍♂️

And I don't need to do anything else for production right? (This worked for me btw thanks)

Edit: I'm having problems while deploying in prodcution, what should I do?

![image](https://user-images.githubusercontent.com/68821192/179382198-c99e33cc-9ae6-4263-bc24-f68dead373af.png)
