### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Sheryorov** [alixaxel/chrome-aws-lambda#144]
Here is  dependency list

> 
    "@babel/cli": "^7.8.4",
    "@babel/core": "^7.9.0",
    "@babel/preset-env": "^7.9.0",
    "@babel/register": "^7.10.1",
    "@babel/runtime": "^7.9.2",
    "async-disk-cache": "^2.0.0",
    "aws-sdk": "^2.648.0",
    "aws4-axios": "^1.12.0",
    "awscred": "^1.5.0",
    "axios": "^0.19.2",
    "babel-plugin-transform-html-import-to-string": "0.0.1",
    "chrome-aws-lambda": "^3.1.1",
    "dateformat": "^3.0.3",
    "dinero.js": "^1.8.1",
    "handlebars": "^4.7.3",
    "i18n-iso-countries": "^5.1.0",
    "i18next": "^19.3.4",
    "i18next-node-fs-backend": "^2.1.3",
    "lambda-tester": "^4.0.1",
    "loglevel": "^1.6.7",
    "node-fetch": "^2.6.0",
    "puppeteer-core": "^4.0.0",
    "rimraf": "^3.0.2"

After running `npm audit` its throw error:

>                                                                            

┌──────────────────────────────────────────────────────────────────────────────┐
│                                Manual Review                                 │
│            Some vulnerabilities require your attention to resolve            │
│                                                                              │
│         Visit https://go.npm.me/audit-guide for additional guidance          │
└──────────────────────────────────────────────────────────────────────────────┘
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ Low           │ Prototype Pollution                                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ minimist                                                     │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >=0.2.1 <1.0.0 || >=1.2.3                                    │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ chrome-aws-lambda                                            │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ chrome-aws-lambda > lambdafs > tar-fs > mkdirp > minimist    │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://npmjs.com/advisories/1179

**Comment by alixaxel** [comment]
This has been sorted out in 5.2.1 - thanks for the heads up.
