### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by chumanhquang** [alixaxel/chrome-aws-lambda#145]
#Environment
* `chrome-aws-lambda` Version: v3.1.1
* Lambda  <!-- `nodejs12.x`

## Current Behavior
This is my site: https://builder.ladipage.com/editor/banner/5ee1dd5c55d2af3149d0f571
Error font Japanese. It seems not like Lambda instance. I try to run a 1 instance Amazon Linux 2 and curl to my site. Text Japanese display is good.

When I screenshot, text in Japanese is the wrong font. Below is my screenshot.
[https://drive.google.com/file/d/16TT15RAS73Ziis8eCTYip8FRpWlp03v6/view?usp=sharing](url)

**Comment by alixaxel** [comment]
@chumanhquang Sorry for the long - AWS Lambda doesn't ship with any font faces unlike your EC2 instance.

This project ships with fonts to handle Arabic, Cyrillic, Greek and Latin.

For Japanese scripts, you'll need to [provision your own font](https://github.com/alixaxel/chrome-aws-lambda#fonts).

**Comment by MahmoudEzzatAbdul-Rahman** [comment]
> @chumanhquang Sorry for the long - AWS Lambda doesn't ship with any font faces unlike your EC2 instance.
> 
> This project ships with fonts to handle Arabic, Cyrillic, Greek and Latin.
> 
> For Japanese scripts, you'll need to [provision your own font](https://github.com/alixaxel/chrome-aws-lambda#fonts).

@alixaxel It won't handle my Arabic letters out of the box, any ideas?

**Comment by bushev** [comment]
Same here, Arabic fonts don't work.

chrome-aws-lambda: 10.1.0

<img width="788" alt="Frame 8" src="https://user-images.githubusercontent.com/7535766/137025271-ed7451fe-405a-47af-af0f-de1183456e8d.png">
