### ISSUE TITLE
Running with a sandbox

### ISSUE THREAD

**Issue by williamjulianvicary** [alixaxel/chrome-aws-lambda#148]
## What would you like to have implemented?
Is it possible to run Chromium without the --no-sandbox flag? 

## Why would it be useful?
For safety when executing foreign code.

## When attempting to run without a sandbox:
```
 ERROR   Error: Failed to launch the browser process!
[0703/095854.412457:WARNING:resource_bundle.cc(435)] locale_file_path.empty() for locale 
[0703/095854.412718:FATAL:zygote_host_impl_linux.cc(116)] No usable sandbox! Update your kernel or see https://chromium.googlesource.com/chromium/src/+/master/docs/linux/suid_sandbox_development.md for more information on developing with the SUID sandbox. If you want to live dangerously and need an immediate workaround, you can try using --no-sandbox.
#0 0x5620dd3b8b29 (/tmp/chromium+0x48e4b28)
#1 0x5620dd328173 (/tmp/chromium+0x4854172)
#2 0x5620dd338d25 (/tmp/chromium+0x4864d24)
#3 0x5620de8be36e (/tmp/chromium+0x5dea36d)
#4 0x5620dd2cb110 (/tmp/chromium+0x47f710f)
#5 0x5620de8c5157 (/tmp/chromium+0x5df1156)
#6 0x5620dd2c4801 (/tmp/chromium+0x47f0800)
#7 0x5620dd32449d (/tmp/chromium+0x485049c)
#8 0x5620dd3241bc (/tmp/chromium+0x48501bb)
#9 0x7f94f470a02a __libc_start_main
#10 0x5620db4aea2a _start
```

**Comment by Dadidam** [comment]
@williamjulianvicary it seems like you're trying to overwrite default args provided by chromium-aws package.
When **launch()** it you could exclude/include any flags. Can you provide your args you passing to it?

**Comment by williamjulianvicary** [comment]
@Dadidam I was actually using the package to do the extraction only, ignoring the wrapping and essentially calling the await for the chromiumPath manually and pushing that to the relevant ENV var for puppeteer core.

In the end I tweaked the approach and instead I'm now overriding the `launch()` method on puppeteer with this:
```
puppeteer.launch = async function launch(options = {}) {

    const newOptions = {
        args: chromium.args,
        defaultViewport: chromium.defaultViewport,
        executablePath: process.env.CHROMIUM_PATH,
        headless: true,
        ignoreHTTPSErrors: true
    };

    return await this._launcher.launch(newOptions);
}
```

Ideally I was hoping to be able to include the sandbox, but I have a feeling thats just not a supported approach with AWS.

**Comment by Dadidam** [comment]
According to the error you've got - something wrong with your **CHROMIUM_PATH**. Have you got the same error using `chromium.executablePath` locally for instance?

**Comment by williamjulianvicary** [comment]
It was the args that are provided by `chromium.args` that were missing from my initial call (I wasn't launching with the above options before - which works fine now).

It seems the options provided by `chromium.args` aren't just a suggestion, they're required by the packaged Chromium instance (at least some of them).

**Comment by alixaxel** [comment]
@williamjulianvicary It's not possible unfortunately (this is a limitation of the AWS Lambda environment).

And yes, about half of the `chromium.args` are required, the rest are there to make it more consistent or performant.
