### ISSUE TITLE
Incognito suppport

### ISSUE THREAD

**Issue by nonyy** [alixaxel/chrome-aws-lambda#15]
Is it disabled?

**Comment by alixaxel** [comment]
@nonyy Not exactly, but yes... AWS Lambda only gives us one CPU, which means we are forced to use the `--single-process` argument. On the other hand, incognito mode won't work in `--single-process` mode.

**Comment by Bnaya** [comment]
@alixaxel can you elaborate please regarding `single-process`?
lambda with more than 1.5GB (or 2GB?) have access to 2 vCores
Dose it means we will be able to run it without `single-process`?
Why can't more than one process on a single core?

Thank you for that amazing project

**Comment by alixaxel** [comment]
@Bnaya This was the very first thing I tested when AWS announced 3GB Lambdas with multi-core support.

> Why can't more than one process on a single core?

This is just the design of Chromium itself, back in the day this was a major win compared to Firefox.

> Dose it means we will be able to run it without single-process?

Unfortunately no, if you try to launch without `--single-process` on a 3GB Lambda:

```js
browser = await puppeteer.launch({
  args: chromium.args.filter((arg) => arg !== '--single-process'),
  defaultViewport: chromium.defaultViewport,
  executablePath: await chromium.executablePath,
  headless: chromium.headless,
});
```

You'll get a timeout:

> Task timed out after 30.03 seconds

Looking at `/proc/cpuinfo` on the same Lambda:

```
processor: 0
vendor_id: GenuineIntel
cpu family: 6
model: 62
model name: Intel(R) Xeon(R) Processor @ 2.50GHz
stepping: 4
microcode: 0x1
cpu MHz: 2500.010
cache size: 33792 KB
physical id: 0
siblings: 2
core id: 0
cpu cores: 2
apicid: 0
initial apicid: 0
fpu: yes
fpu_exception: yes
cpuid level: 13
wp: yes
flags: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx rdtscp lm constant_tsc rep_good nopl xtopology nonstop_tsc cpuid tsc_known_freq pni pclmulqdq ssse3 cx16 pcid sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm cpuid_fault pti ibrs ibpb fsgsbase tsc_adjust smep erms mpx avx512dq smap clflushopt clwb avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves arat pku ospke arch_capabilities
bugs: cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf
bogomips: 5000.02
clflush size: 64
cache_alignment: 64
address sizes: 46 bits physical, 48 bits virtual
power management:

processor: 1
vendor_id: GenuineIntel
cpu family: 6
model: 62
model name: Intel(R) Xeon(R) Processor @ 2.50GHz
stepping: 4
microcode: 0x1
cpu MHz: 2500.010
cache size: 33792 KB
physical id: 0
siblings: 2
core id: 1
cpu cores: 2
apicid: 1
initial apicid: 1
fpu: yes
fpu_exception: yes
cpuid level: 13
wp: yes
flags: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx rdtscp lm constant_tsc rep_good nopl xtopology nonstop_tsc cpuid tsc_known_freq pni pclmulqdq ssse3 cx16 pcid sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm cpuid_fault pti ibrs ibpb fsgsbase tsc_adjust smep erms mpx avx512dq smap clflushopt clwb avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves arat pku ospke arch_capabilities
bugs: cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf
bogomips: 5000.02
clflush size: 64
cache_alignment: 64
address sizes: 46 bits physical, 48 bits virtual
power management:
```

We can indeed see 2 CPU cores, but it still doesn't work.

**Comment by Bnaya** [comment]
So i believe we can assume its not (only) the cores number but also something else on Lambda?
any ideas how to try and debug it?

I will play with it again when lambda node 10 support is ready :)

**Comment by alixaxel** [comment]
@Bnaya These [related](https://github.com/GoogleChrome/puppeteer/issues/1523) [issues](https://github.com/GoogleChrome/puppeteer/issues/85#issuecomment-432552000) might be helpful, this one particularly: https://github.com/GoogleChrome/puppeteer/issues/2608#issuecomment-393419208

**Comment by Bnaya** [comment]
I'm following these issues for long time :)
They even say that we might loose` --single-proccess`, maybe without notice, because its not really maintained anymore
