### ISSUE TITLE
[REQUEST] I would like to know how to make chrome-aws-lambda

### ISSUE THREAD

**Issue by heathera2016** [alixaxel/chrome-aws-lambda#153]
Rather than waiting for updating to Puppeteer 5.0, I would like to make chrome-aws-lambda package on my end.
How can I make Chrome-aws-lambda? Is there any guide or could you give me some tips?
Many thanks :)

Best regards,
Heathera

**Comment by Dadidam** [comment]
@heathera2016 this is described in README file, [here](https://github.com/alixaxel/chrome-aws-lambda#compiling).

**Comment by heathera2016** [comment]
@Dadidam Thanks for your answer. I wonder Chronium binary and puppeteer-core are enough for prerequisite. Is there anything I have to consider?

**Comment by alixaxel** [comment]
@heathera2016 As @Dadidam said, this is fully described [here](https://github.com/alixaxel/chrome-aws-lambda/tree/master/_/ansible).

Besides `puppeteer-core`, you will also need to patch AWS Lambda environment with [`aws.tar.br`](https://github.com/alixaxel/chrome-aws-lambda/blob/master/bin/aws.tar.br).
