### ISSUE TITLE
[BUG] Interface 'Browser' incorrectly extends interface 'BrowserContext'

### ISSUE THREAD

**Issue by benlongmire** [alixaxel/chrome-aws-lambda#156]
## Environment
* `chrome-aws-lambda` Version: `5.2.0`
* `puppeteer` / `puppeteer-core` Version: `5.2.1`
* OS: Mac
* Node.js Version:  `12.x`
* Lambda / GCF Runtime: `nodejs12.x`

## Expected Behavior
TypeScript should compile without mismatched interface

## Current Behavior
Upon compile, it seems `interface Browser` isn't typed properly.
```bash
node_modules/@types/puppeteer/index.d.ts:1814:18 - error TS2430: Interface 'Browser' incorrectly extends interface 'BrowserContext'.
  The types returned by 'targets()' are incompatible between these types.
    Type 'Promise<Target[]>' is missing the following properties from type 'Target[]': length, pop, push, concat, and 26 more.

1814 export interface Browser extends EventEmitter, TargetAwaiter {
```

## Steps to Reproduce
```json
{
  "devDependencies": {
    "@types/node": "^12",
    "@types/puppeteer": "3.0.1",
    "@typescript-eslint/eslint-plugin": "^3.6.1",
    "@typescript-eslint/parser": "^3.6.1",
    "aws-sdk": "^2.725.0",
    "eslint": "^7.4.0",
    "puppeteer": "^5.2.1",
    "typescript": "^3.9.7"
  },
  "dependencies": {
    "chrome-aws-lambda": "5.2.0",
    "puppeteer-core": "5.2.1"
  }
}
```

```typescript
import chromium from "chrome-aws-lambda";
export async function example(): Promise<void> {
  const browser = await chromium.puppeteer.launch({
    executablePath: await chromium.executablePath,
    args: chromium.args,
    defaultViewport: chromium.defaultViewport,
    headless: chromium.headless,
    ignoreHTTPSErrors: true,
  });
}
```

## Possible Solution
I'm honestly not sure if this is a bug or I'm doing something wrong. Please advise.

**Comment by benlongmire** [comment]
I'd be keen to help out with this if you can point me in the right direction.

**Comment by deldrid1** [comment]
I'm running into the same bug.  I'm new to typescript so I'm not exactly sure what is going on here, but simply commenting the block out in `node_modules/chrome-aws-lambda/source/index.d.ts` gets things building again (which I imagine is not the correct fix):

```typescript
// declare module 'puppeteer' {
//   export interface Browser extends BrowserContext {
//     /**
//      * Returns a new page overloaded with browser-context methods.
//      *
//      * @param hooks - Optional hooks to apply on the new page.
//      */
//     newPage(...hooks: ((page: Page) => Page)[]): Promise<Page>;
//   }

//   export interface Page extends Chromium.Page {}
//   export interface Frame extends Chromium.Frame {}
// }
```

**Comment by benlongmire** [comment]
> I'm running into the same bug.  I'm new to typescript so I'm not exactly sure what is going on here, but simply commenting the block out in `node_modules/chrome-aws-lambda/source/index.d.ts` gets things building again (which I imagine is not the correct fix):
> 
> ```typescript
> // declare module 'puppeteer' {
> //   export interface Browser extends BrowserContext {
> //     /**
> //      * Returns a new page overloaded with browser-context methods.
> //      *
> //      * @param hooks - Optional hooks to apply on the new page.
> //      */
> //     newPage(...hooks: ((page: Page) => Page)[]): Promise<Page>;
> //   }
> 
> //   export interface Page extends Chromium.Page {}
> //   export interface Frame extends Chromium.Frame {}
> // }
> ```

Ok, thanks. I'll take a look at this hopefully within 12 hours

**Comment by deldrid1** [comment]
It seems like #157 could be a part of the problem (without using that branch with `puppeteer-core` 5.2.1 I got a unable to resolve module error when deployed to GCF), but it also looks like there could be an issue with the puppeteer types:

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/736981c8f81a1c483abb50392c1d925cad03ad9e/types/puppeteer/index.d.ts#L1883-L1884

This typing doesn't seem to align to https://pptr.dev/#?product=Puppeteer&version=v5.2.1&show=api-browsertargets, which says that the correct return type is of `Target[]` instead of `Promise<Target[]>`.

Changing `node_modules/@types/puppeteer/index.d.ts` line 1884 to `  targets(): Target[];` does get `tsc` happy as well.

Unfortunately, I still haven't gotten anything to work on Google Cloud Functions...  (I'm trying to use `chrome-aws-lambda`, `puppeteer-extra`, `puppeteer-cluster`, and TypeScript and it just isn't quite coming togeter...

**Comment by benlongmire** [comment]
Thanks for the extra info. Unfortunately I haven't had a chance to look at this.

I'll be able to spend some limited time on this starting tomorrow (it's Friday today in Australia).

I'll let you know how I go ASAP.

**Comment by alixaxel** [comment]
@benlongmire This should be handled now on the latest version (5.2.1).

The problem is `@types/puppeteer` is still lagging behind and `puppeteer` haven't yet shipped their typings. 🤷🏻‍♂️
