### ISSUE TITLE
[BUG] MODULE_NOT_FOUND in puppeteer-core - wrong path.

### ISSUE THREAD

**Issue by h1f1x** [alixaxel/chrome-aws-lambda#158]
## Environment
* `chrome-aws-lambda` Version: 5.2.0
*  `puppeteer-core` Version: 5.2.1
* Lambda Runtime: `nodejs12.x`

## Expected Behavior
Returns: `Example Domain`.

So it should not fail with MODULE_NOT_FOUND.

## Current Behavior

```
Invoke Error 	
{
    "errorType": "Error",
    "errorMessage": "Cannot find module 'puppeteer-core/lib/cjs/common/Browser'\nRequire stack:\n- /var/task/node_modules/chrome-aws-lambda/source/puppeteer/lib/Browser.js\n- /var/task/node_modules/chrome-aws-lambda/source/index.js\n- /var/task/handler.js\n- /var/runtime/UserFunction.js\n- /var/runtime/index.js",
    "code": "MODULE_NOT_FOUND",
    "requireStack": [
        "/var/task/node_modules/chrome-aws-lambda/source/puppeteer/lib/Browser.js",
        "/var/task/node_modules/chrome-aws-lambda/source/index.js",
        "/var/task/handler.js",
        "/var/runtime/UserFunction.js",
        "/var/runtime/index.js"
    ],
    "stack": [
        "Error: Cannot find module 'puppeteer-core/lib/cjs/common/Browser'",
        "Require stack:",
        "- /var/task/node_modules/chrome-aws-lambda/source/puppeteer/lib/Browser.js",
        "- /var/task/node_modules/chrome-aws-lambda/source/index.js",
        "- /var/task/handler.js",
        "- /var/runtime/UserFunction.js",
        "- /var/runtime/index.js",
        "    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:966:15)",
        "    at Function.Module._load (internal/modules/cjs/loader.js:842:27)",
        "    at Module.require (internal/modules/cjs/loader.js:1026:19)",
        "    at require (internal/modules/cjs/helpers.js:72:18)",
        "    at Object.<anonymous> (/var/task/node_modules/chrome-aws-lambda/source/puppeteer/lib/Browser.js:6:11)",
        "    at Module._compile (internal/modules/cjs/loader.js:1138:30)",
        "    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)",
        "    at Module.load (internal/modules/cjs/loader.js:986:32)",
        "    at Function.Module._load (internal/modules/cjs/loader.js:879:14)",
        "    at Module.require (internal/modules/cjs/loader.js:1026:19)"
    ]
}
```
## Possible Solution

Correct the modules paths to match the current ones. 
This is `puppeteer-core/lib/cjs/puppeteer/common/Browser` etc.
Done in PR #157 !

**Comment by alixaxel** [comment]
Just released v5.2.1 - sorry about the blunder! 😳

**Comment by omri08** [comment]
Hello   :) I'm using:
  "chrome-aws-lambda": "^5.2.1",
   "puppeteer-core": "^5.2.1",
And still got the same error, which version should I use?
The error I'm getting:
Error: Cannot find module '/var/task/src/handlers/puppeteer/lib/Browser'

**Comment by taegyumin** [comment]
Hello, I'm using:
- "chrome-aws-lambda": "^5.2.1",
- "puppeteer-core": "^5.2.1",
- "puppeteer": "^5.2.1",
And still got the same error... which version should I use?
The error I'm getting:
Error: Cannot find module '.../src/handlers/puppeteer/lib/Browser' (not in puppeteer-core, but in pupeteer)

**Comment by sam-cross** [comment]
Same here. Will update if I find a fix.

**Comment by luizwhite** [comment]
`Error: Failed to launch the browser process!`
`/tmp/chromium: error while loading shared libraries: libnss3.so: cannot open shared object file: No such file or directory`

Error i get when trying to use it with vercel api functions

**Comment by hoonoh** [comment]
Came across this recently on `esbuild` bundled lambda function with `chreom-aws-lambda` and `puppeteer-core` as externals and had it solved with layers as described in readme: https://github.com/alixaxel/chrome-aws-lambda#aws-lambda-layer
