### ISSUE TITLE
Emoji Support

### ISSUE THREAD

**Issue by styfle** [alixaxel/chrome-aws-lambda#16]
Hello 👋 This is a really great tool you built! 😄 

I found a related issue (#4) but the solution is to add a custom font in the `.fonts` directory.

Which font would I use to get emoji support? Have you had any success with rendering emoji? 🤔

**Comment by j** [comment]
Built-in support for this would be pretty awesome.

**Comment by alixaxel** [comment]
@styfle I suppose [Noto Emoji](https://github.com/googlei18n/noto-emoji) is what you need, specifically the [Noto Color Emoji](https://github.com/googlei18n/noto-emoji/blob/master/fonts/NotoColorEmoji.ttf) font.

I haven't had the need to use custom fonts yet, but if you try it, let me know how it goes. :smile: 

---

@j Even compressed, the TTF file is still over 7MB in size (no surprise there) and given that the main purpose of this package is to be as lightweight as possible, I'd rather delegate that choice to the end-user.

**Comment by styfle** [comment]
@alixaxel That Noto Color Emoji font worked, thanks! 🎉 🎉 🎉 

If anyone is interested how to add this font, see these two pull requests (I missed a couple things on the first one 😉 )

https://github.com/styfle/og-image/pull/52

https://github.com/styfle/og-image/pull/54

**Comment by alixaxel** [comment]
@styfle Did you try adding the font under `$HOME/.fonts/` and it didn't work?

**Comment by styfle** [comment]
@alixaxel No, I did not try that because that doesn’t work very nicely for local development (putting font files in the user’s home dir) and then deployment would require an additional build step to copy to the home dir.

**Comment by alixaxel** [comment]
@styfle Not sure if you still need it, but I figured the newest addition might be interesting to you:

https://github.com/alixaxel/chrome-aws-lambda#fonts

**Comment by styfle** [comment]
@alixaxel Thanks for adding that method!

I'm currently [reading the file](https://github.com/zeit/og-image/blob/13a95a409f8ba3ae1d4d448cf48bd0b0b21c6d8d/src/template.ts#L11) as base64 and injecting into css font-face.

With this new function, how do you specify the name of the font-face so that it can be used in [css classes below](https://github.com/zeit/og-image/blob/13a95a409f8ba3ae1d4d448cf48bd0b0b21c6d8d/src/template.ts#L58)?

**Comment by alixaxel** [comment]
@styfle Fonts have their font-face name encoded in the file itself (don't ask me specifics tho!).

![image](https://user-images.githubusercontent.com/262782/53816400-69233680-3f5b-11e9-855d-34107ad396dd.png)

**Comment by styfle** [comment]
@alixaxel Alright! I'll have to give this a try and see if it performs better than my css solution.

Does this only work with URLs or can I give it a relative path to the font file?

**Comment by alixaxel** [comment]
Just URLs (and HTTPS ones).

**Comment by ed-sparkes** [comment]
@styfle did you ever try the chromium.font method? i cant seem to get it to work, sometimes it seems to run fine but the font is not reflected, other times i get a symlink err ERREXIST or something,

**Comment by vvo** [comment]
For anyone still coming up here:
- as for fonts support, I've had better success in building my page with @font-face than trying to use chromium.font(). Mainly because the font would not be loaded on the first load but on successive loads..
- as for emoji support, the easiest is to build your page with https://github.com/twitter/twemoji

**Comment by clathrop** [comment]
@vvo Hey, I'm currently trying to get twemoji to load in a headless browser but as you mentioned, chromium.font() is not working with the ttf i've generated using the method here: https://github.com/mozilla/twemoji-colr.

For background, I've gotten the Noto Color Emoji to work but it is not widely supported for all emojis nor all PDF viewers.

So moving on to an @font-face & twemoji option like you suggested is my next bet. Question though, did you load the font face via cdn or load it from local file system in your build? Wondering exactly how you ended up setting up your solution. Thanks!

**Comment by vvo** [comment]
(I have no idea sorry)
