### ISSUE TITLE
[BUG] Example doesn't work "puppeteer.launch is not a function"

### ISSUE THREAD

**Issue by braco** [alixaxel/chrome-aws-lambda#166]
Setup:
`npm install chrome-aws-lambda --save-prod`
`npm install puppeteer-core --save-prod`

Running code in README yields:
`"TypeError: puppeteer.launch is not a function","    at /var/task/puppeteer.js:4:37"`

5.3.1, latest everything

Something to clarify in the README is this:

```
This will ship with appropriate binary for the latest stable release of puppeteer (usually updated within a few days).
You will also need to install the corresponding version of puppeteer (or puppeteer-core):
```

I'm interpreting this like "this ships with the latest version. And then you need to install the latest version"

**Comment by braco** [comment]
```
const chromium = require('chrome-aws-lambda');
exports.image = async () => {
  console.log('puppet', typeof chromium.puppeteer);
  return {
    statusCode: 200,
    body: 'Bye',
  };
};
```

yields

```
INFO	puppet object
ERROR	Unhandled Promise Rejection 	{"errorType":"Runtime.UnhandledPromiseRejection","errorMessage":"TypeError: puppeteer.launch is not a function","reason":{"errorType":"TypeError","errorMessage":"puppeteer.launch is not a function","stack":["TypeError: puppeteer.launch is not a function","    at /var/task/puppeteer.js:4:37","    at Object.<anonymous> (/var/task/puppeteer.js:36:3)","    at Module._compile (internal/modules/cjs/loader.js:1137:30)","    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)","    at Module.load (internal/modules/cjs/loader.js:985:32)","    at Function.Module._load (internal/modules/cjs/loader.js:878:14)","    at Module.require (internal/modules/cjs/loader.js:1025:19)","    at require (internal/modules/cjs/helpers.js:72:18)","    at Function.get puppeteer [as puppeteer] (/opt/nodejs/node_modules/chrome-aws-lambda/source/index.js:206:14)","    at Runtime.exports.image [as handler] (/var/task/handler.js:22:41)"]},"promise":{},"stack":["Runtime.UnhandledPromiseRejection: TypeError: puppeteer.launch is not a function","    at process.<anonymous> (/var/runtime/index.js:35:15)","    at process.emit (events.js:315:20)","    at processPromiseRejections (internal/process/promises.js:209:33)","    at processTicksAndRejections (internal/process/task_queues.js:98:32)"]}
[ERROR] [1602448532999] LAMBDA_RUNTIME Failed to post handler success response. Http response code: 403.
```

**Comment by alixaxel** [comment]
@braco Sorry for the terribly late reply. 🙏 

> I'm interpreting this like "this ships with the latest version. And then you need to install the latest version"

So basically, `puppeteer` will only only guarantee compatibility with the Chromium binary version they ship with.

This project provides the patched binary for AWS Lambda, some needed extra dependencies, and a thin layer of Javascript to make the instantiation easier on serverless environments. When calling `launch()`, `chrome-aws-lambda` delegates that responsibility to `puppeteer` or `puppeteer-core` (whichever you choose to install), and in your case it seems that you haven't installed either one of them, so simply doing `npm i puppeteer-core` should solve your problem.

Regarding the layer, I cannot speak for shelfio/chrome-aws-lambda-layer as I don't know the contents of the layer.

But if you [build your own layer](https://github.com/alixaxel/chrome-aws-lambda#aws-lambda-layer), you'll end up with a layer that contains all the needed dependencies:

* lambdafs
* puppeteer-core
* chrome-aws-lambda

Hope this helps!
