### ISSUE TITLE
[BUG] Static assets from S3 not rendering 403

### ISSUE THREAD

**Issue by luucv** [alixaxel/chrome-aws-lambda#174]
## Environment
* `chrome-aws-lambda` Version: 5.3.1
* `puppeteer-core` Version: 5.4.1
* OS: Mac
* Node.js Version: 12.x
* Lambda / GCF Runtime: `nodejs12.x`

## Expected Behavior
I would expect static assets that are pointing to an S3 url to be rendered.

## Current Behavior
Static assets that are pointing to an S3 url are returning a 403 error.

## Steps to Reproduce

```js
const chromium = require('chrome-aws-lambda');

exports.handler = async (event, context, callback) => {
  let result = null;
  let browser = null;

  try {
    browser = await chromium.puppeteer.launch({
      args: chromium.args,
      defaultViewport: chromium.defaultViewport,
      executablePath: await chromium.executablePath,
      headless: chromium.headless,
      ignoreHTTPSErrors: true,
    });

    let page = await browser.newPage();

    await page.setContent(`<html><img src="https://bucket.region.amazonaws.com/image.jpg" /></html>`);

    result = await page.title();
  } catch (error) {
    return callback(error);
  } finally {
    if (browser !== null) {
      await browser.close();
    }
  }

  return callback(null, result);
};
```

## Possible Solution
I presume it has to do with the roles and policies. Any pointers in how I should configure those? I rather not use presigned urls as I'm rendering many images.

**Comment by sebastian-bojara** [comment]
It doesn't seem related to this repo. Anyway, take a look at this https://aws.amazon.com/premiumsupport/knowledge-center/lambda-execution-role-s3-bucket/

**Comment by alixaxel** [comment]
Hey @luucv, as Sebastian mentioned, the issue you're facing is not related to puppeteer or this project. HTTP status code 403 is Forbidden, which means your bucket security policies are not allowing the Lambda to access that specific file (you should see the same behaviour from any other computer).

I suggest you look into [S3 Security Policies](https://docs.aws.amazon.com/AmazonS3/latest/dev/example-bucket-policies.html) to change the visibility of your bucket or access the file via a [pre-signed URL](https://docs.aws.amazon.com/AmazonS3/latest/dev/ShareObjectPreSignedURL.html).
