### ISSUE TITLE
Does this still work?

### ISSUE THREAD

**Issue by AdityaAnand1** [alixaxel/chrome-aws-lambda#175]
There seems to be a lot of open bugs, does this still work?

Any gotchas?

**Comment by alixaxel** [comment]
@AdityaAnand1 Yes, it does still work (and it's still being maintained). 🙂 

Most of the open issues are questions about usage and/or issues unrelated to this project (API Gateway, S3, puppeteer, etc).

In terms of gotchas, there are mainly three things that you need to be aware of:

* **Lambda is not provisioned with any fonts.**

This project ships with a default font (Open Sans), but if you want 100% parity with what you see on your browser (including emojis or non-supported scripts) you will have to either rely on web fonts being downloaded or [provision the fonts yourself](https://github.com/alixaxel/chrome-aws-lambda#fonts).

* **Lambda is limited to one CPU thread.**

This means that you'll not be able to use different browser contexts (aka incognito) in the same Lambda.

* **Lambda is limited to 3GB of RAM.**

So if you're generating full-page screenshots of **_huge_** pages you'll hit OOM errors.

There are workarounds for this but they require extra work.
