### ISSUE TITLE
[REQUEST] Use zlib module instead of iltorb

### ISSUE THREAD

**Issue by VoidMonk** [alixaxel/chrome-aws-lambda#178]
## What would you like to have implemented?
The `iltorb` package seems to be a dependency for using `chrome-aws-lambda` in Google Cloud Functions, but `iltorb` has been deprecated.

As per its author, "the zlib module provides APIs for brotli compression/decompression starting with Node.js v10.16.0, please use it over iltorb." https://www.npmjs.com/package/iltorb

## Why would it be useful?
Use of a native module over a deprecated dependency will result in better performance and cleaner code.

**Comment by alixaxel** [comment]
@VoidMonk This is already the case:

https://github.com/alixaxel/lambdafs/blob/2cc20dca75bfd023767740f4588672bfa143089e/source/index.ts#L5

Seems like I forgot to remove the `iltorb` reference from the README tho, so thanks for the heads up!

**Comment by VoidMonk** [comment]
@alixaxel Thanks, that's good. So, that `lambdafs` package (with de/compression code) also applies to GCP Functions along with AWS Lambda?
