### ISSUE TITLE
[BUG] EROFS: read-only file system, mkdir '/opt/fonts/.fonts'

### ISSUE THREAD

**Issue by QAnders** [alixaxel/chrome-aws-lambda#181]
## Environment
* `chrome-aws-lambda` Version: 5.5.0
* `puppeteer` / `puppeteer-core` Version: 5.5.0
* OS: Linux
* Node.js Version: 12.x
* Lambda / GCF Runtime: `nodejs12.x`
## Expected Behavior
Using `font` should load the font

## Current Behavior
AWS Lambda throws an error

```
"EROFS: read-only file system, mkdir '/opt/fonts/.fonts'"
```

## Steps to Reproduce

```js
const chromium = require('chrome-aws-lambda');

exports.handler = async (event, context, callback) => {
  let result = null;
  let browser = null;

  try {
    browser = await chromium.puppeteer.launch({
      args: chromium.args,
      defaultViewport: chromium.defaultViewport,
      executablePath: await chromium.executablePath,
      headless: chromium.headless,
      ignoreHTTPSErrors: true,
    });

    await chromium.font('./fonts/Arial.ttf'); // Or any valid URL with a font in it

    let page = await browser.newPage();

    await page.goto(event.url || 'https://example.com');

    result = await page.title();
  } catch (error) {
    return callback(error);
  } finally {
    if (browser !== null) {
      await browser.close();
    }
  }

  return callback(null, result);
};
```

**Comment by hoangtrieukd** [comment]
i had same issue

**Comment by QAnders** [comment]
I did a work-around, @hoangtrieukd , by altering lines 7-9 here https://github.com/alixaxel/chrome-aws-lambda/blob/0515e36b384bf3c005c94759e8ba141e677e0f6d/source/index.js#L8
```
// if (process.env.FONTCONFIG_PATH === undefined) {
    process.env.FONTCONFIG_PATH = '/var/task/fonts';  // <-- was /tmp/aws which is not working
// }
```

I run the `chrome-aws-lambda` as a Layer so in the "main" project you add a `fonts` directory in the root of the project and in that the *.ttf file(s) and a `fonts.conf` file containg:
```
<?xml version="1.0"?>
<!DOCTYPE fontconfig SYSTEM "fonts.dtd">
<fontconfig>
  <dir>/var/task/fonts</dir>
  <cachedir>/tmp/fonts-cache/</cachedir>
  <config></config>
</fontconfig>
```

If you load `chrome-aws-lambda` as a module in your project, just add the `fonts` directory in that project.

**Comment by bestplay9384** [comment]
I think you should use this functions as it was developed to :) Just add environment variable `FONTCONFIG_PATH` to lambda that is using your layer, path should be overwritten. There is no need to change code of chrome-aws-lambda project then :) If you are using AWS CodePipeline & AWS CloudFormation to deploy your lambda changes you can also overwrite this path in your lambda runtime file just before requiring chrome-aws-lambda dependency, that should work too :)

**Comment by QAnders** [comment]
The `fonts` should just go as a directory in the root of your project (not in the Layer!).

You don't need to add it at all in the YML file so remove any reference to the `fonts` in your YML.

When AWS unpacks your Lambda it will find and "install" the fonts found in the `fonts.config` from the fonts directory automatically.

**Comment by hoangtrieukd** [comment]
1. I had changed HOME env /opt/fonts to /tmp and its working.
2. I stored some fonts in layer for headless run. is that correct?

**Comment by alixaxel** [comment]
@QAnders Apologies for only now getting to this. A few pointers:

* The fonts will be placed under `$HOME/.fonts/` (as it is usually in any other POSIX system).
  * On Lambda, `$HOME` is not set, and because it needs to be writable, it's set to `/tmp` by this package.
* The local fonts should be passed to `font()` with *absolute* paths (I will add this note to the README).
* The fontconfig file will look for fonts under `/tmp/aws/.fonts` and `/tmp/.fonts`.
  * I will be adding support for `/opt/.fonts` in the fontconfig, which will make provisioning fonts via Layers easier.
