### ISSUE TITLE
[REQUEST] Use headless false ("headful") in AWS

### ISSUE THREAD

**Issue by andresfloid** [alixaxel/chrome-aws-lambda#188]
## What would you like to have implemented?
Launch a browser with headless false in AWS (or any other Cloud provider) the same way it can be done with `puppeteer` or `puppeteer-extra`

## Why would it be useful?
I have experienced different results with websites depending on if it is headless or not, so that you can try two different approaches and compare them. I do not know if running "headful" is a limitation of using Lambda but I have not found anything related in the docs or issues

Cheers

**Comment by NikolaiT** [comment]
I also want to do exactly this.

However, headful on AWS Lambda is only possible if there is also a Xvfb or X virtual framebuffer running (Xvfb is a display server implementing the X11 display server protocol without showing any screen output).

A possible approach would be to use an custom Lambda Docker Container that installs Xvfb. 

See [this GIST reply](https://gist.github.com/cpsubrian/3aa40f6f3d6ce2c707b9d8e34c652dcf#gistcomment-3553963) for details.

I will test if that works and get back here later.

**Comment by deldrid1** [comment]
@NikolaiT - did you ever try this?

I’m wondering if headful would get me over the hump on #184...

**Comment by alixaxel** [comment]
@andresfloid As @NikolaiT mentioned, you'd need a display server which currently is not supported out of the box with Lambda. With the new container support for Lambda, it might be possible to hack something out but this is not something I wish to support at this time. There already some basic measures in place, like removing "Headless" from the User Agent:

https://github.com/alixaxel/chrome-aws-lambda/blob/0dee7fec540341c75652ebd58d3651a2572587f0/source/puppeteer/lib/Browser.js#L18-L21

Also, I would consider packages like [`puppeteer-extra-plugin-stealth`](https://www.npmjs.com/package/puppeteer-extra-plugin-stealth) before moving to more drastic evasive measures.

**Comment by andresfloid** [comment]
Thanks for the answer @alixaxel, I will try your suggestions!
