### ISSUE TITLE
[BUG] Error: Cannot find module 'chrome-aws-lambda'

### ISSUE THREAD

**Issue by pavelloz** [alixaxel/chrome-aws-lambda#192]
```
{
    "errorType": "Runtime.ImportModuleError",
    "errorMessage": "Error: Cannot find module 'chrome-aws-lambda'\nRequire stack:\n- /var/task/index.js\n- /var/runtime/UserFunction.js\n- /var/runtime/index.js",
    "stack": [
        "Runtime.ImportModuleError: Error: Cannot find module 'chrome-aws-lambda'",
        "Require stack:",
        "- /var/task/index.js",
        "- /var/runtime/UserFunction.js",
        "- /var/runtime/index.js",
        "    at _loadUserApp (/var/runtime/UserFunction.js:100:13)",
        "    at Object.module.exports.load (/var/runtime/UserFunction.js:140:17)",
        "    at Object.<anonymous> (/var/runtime/index.js:43:30)",
        "    at Module._compile (internal/modules/cjs/loader.js:1015:30)",
        "    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10)",
        "    at Module.load (internal/modules/cjs/loader.js:879:32)",
        "    at Function.Module._load (internal/modules/cjs/loader.js:724:14)",
        "    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)",
        "    at internal/main/run_main_module.js:17:47"
    ]
}
```

## Environment
* `chrome-aws-lambda` Version: 5.5.0
* `puppeteer` / `puppeteer-core` Version: 5.5.0
* OS: 

* Lambda / GCF Runtime: `nodejs12.x`

I was using aws-chrome-lambda 3 with puppeteer-core 3.0.4 for a long time, now decided to upgrade to 5.5.0 but it looks like layer is seen.

In my js code im importing it this way:

```
const chromium = require('chrome-aws-lambda');
const puppeteer = require('puppeteer-core');
```

Are there any known issues with module visibility while upgrading?
Ive checked zip structure, looks good. Correct layer is used. Correct node version. Im out of ideas, to my knowledge it should work as before.

**Comment by JonnyBGod** [comment]
@pavelloz How did you solve this? I am getting the same error.

**Comment by pavelloz** [comment]
Yes, it turned out i checked the wrong zip when investigating. I went to s3, downloaded and it turned out that my serverless framework package had excluded layer files in the .zip file. So i rebuilt how i package layer zip and it works fine now.

Double check the final zip that you are uploading, it should have proper directory structure inside of it: `nodejs/node_modules/x`

**Comment by massi-css** [comment]
hey im trying to deploy my  app that is using puppeteer-core to vercel but the same probleme appearing can you help me
