### ISSUE TITLE
Version 8

### ISSUE THREAD

**Issue by steida** [alixaxel/chrome-aws-lambda#198]
## What would you like to have implemented?

Puppeteer 8 was released two weeks ago. I am not sure it's ok to use chrome-aws-lambda 7, it is?

**Comment by alixaxel** [comment]
@steida Version 8 will be released today, since puppeteer got rewritten in Typescript, I'm also following suit.

Just need to iron out some last quirks.

**Comment by alixaxel** [comment]
@steida Version 8.0.0 just released, please watch out for some breaking changes in the [overloaded API](https://github.com/alixaxel/chrome-aws-lambda#overloading). 🙂
