### ISSUE TITLE
[BUG] Intermittent issue while generating PDF

### ISSUE THREAD

**Issue by prashanthkalidindi84** [alixaxel/chrome-aws-lambda#202]
@baharev @alixaxel

## Environment
* `chrome-aws-lambda` Version: 2.1.1
* `puppeteer` / `puppeteer-core` Version:   2.1.1 (puppeteer-core`)
* OS:  (Linux) on AWS Lambda function
* Node.js Version:  12.x 
* Lambda / GCF Runtime: nodejs12

## Expected Behavior

PDF should be created

## Current Behavior

PDF creating at Intermittent intervals. 
Sometimes PDF is generating properly and sometimes PDF is generating with blank content 

## Possible Solution

I checked the code for generating html method 'fetchHtml', and uploading pdf file to S3 functions separately they works as expected  but at Intermittent intervals generating pdf fails. I mean PDF created with blank data.

Specifically it fails at

const pdf = await page.pdf({
      format: "A4",
      printBackground: true,
      margin: { top: "1cm", right: "1cm", bottom: "1cm", left: "1cm" }
    });
    console.log('pdf json stringify' + JSON.stringify(pdf));

Root Cause :

Comparison done for both 'pdf' objects when pdf is generated and when pdf is blank, compared by converting both pdf objects into buffer data and both buffer data are not the same. Thats the reason sometimes it is working and sometimes not. And this pdf object that we are creating is as per documentation only, if its not consistently creating same data , then I think the problem might be with library itself. 

package.json dependancies:

dependencies": {
    "chrome-aws-lambda": "^2.1.1",
    "pug": "^2.0.4",
    "puppeteer-core": "^2.1.1"
  }

If i can get any help from this post, kindly appreciated.

**Comment by baharev** [comment]
@prashanthkalidindi84  I see nothing under **Steps to Reproduce**.

**Comment by prashanthkalidindi84** [comment]
@baharev 
@mithundas79
@alixaxel

my issue is fixed after adding this { waitUntil: 'networkidle0' }
await page.setContent(html, { waitUntil: 'networkidle0' });

**Comment by alixaxel** [comment]
Glad you figured it out @prashanthkalidindi84, closing this issue.
