### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by roshansourav** [alixaxel/chrome-aws-lambda#212]
I am trying to download a file with this chrome-aws-lambda npm package.
So,  I am using `await page._client.send('Page.setDownloadBehavior', { behavior: 'allow', downloadPath: './' });` 
.
And I am getting error : "Page.setDownloadBehaviour wasnt found

![Screenshot212](https://user-images.githubusercontent.com/63939356/114141831-bee31d80-992f-11eb-9f67-6a1d07fa55d1.png)

"

**Comment by alixaxel** [comment]
@roshansourav For me, both CDP calls are invoked without any errors:

![image](https://user-images.githubusercontent.com/262782/114333273-d1cc3c80-9b3f-11eb-9a62-3c3f173ea179.png)

Can you share a full repro snippet?

**Comment by roshansourav** [comment]
"Browser.setDownloadBehavior"  worked for me.
