### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by deepakrana47** [alixaxel/chrome-aws-lambda#218]
Hello,

I am trying to run the chrome-aws-lambda package with my code but i am getting error. **Here is the code given below**:

`const chromium = require('chrome-aws-lambda');`
`const printpdf = async (buildPathHtml, footertxt) => {`
`  const browser = await chromium.puppeteer.launch({`
`    args: chromium.args,`
`    defaultViewport: chromium.defaultViewport,`
`    executablePath: await chromium.executablePath,`
`    headless: chromium.headless,`
`    ignoreHTTPSErrors: true,`
`  });`
`};`
`printpdf("build-0.html");`

**The package.json:**
`{`
`  "name": "test-html2pdf-creation_1",`
`  "version": "1.0.0",`
`  "description": "",`
`  "main": "app.js",`
`  "scripts": {`
`    "test": "echo \"Error: no test specified\" && exit 1"`
`  },`
`  "keywords": [],`
`  "author": "",`
`  "license": "ISC",`
`  "dependencies": {`
`    "chrome-aws-lambda": "^9.0.0",`
`    "puppeteer-core": "^9.0.0"`
`  }`
`}`

**The error:**

> (node:8178) UnhandledPromiseRejectionWarning: Error: Could not find expected browser (chrome) locally. Run `npm install` to download the correct Chromium revision (869685).
>    at ChromeLauncher.launch (/home/zero/Desktop/Datastore/ng-Report/test-html2pdf-creation-1/node_modules/puppeteer-core/lib/cjs/puppeteer/node/Launcher.js:82:27)
>    at async printpdf (/home/zero/Desktop/Datastore/ng-Report/test-html2pdf-creation-1/app.js:5:19)
> (Use `nodejs --trace-warnings ...` to show where the warning was created)
> (node:8178) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:8178) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by deepakrana47** [comment]
it was an implementation error

**Comment by ghost** [comment]
I'm having the same issue. What did you do to make it work?

edit: fixed it by installing puppeteer as a dev-dependency as described here: https://github.com/alixaxel/chrome-aws-lambda/wiki/HOWTO:-Local-Development#workaround

**Comment by deepakrana47** [comment]
These is packages and code I used to solve this problem

##### package.json #####
{
  "name": "report_generator_layer",
  "version": "1.0.0",
  "private": true,
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "jest"
  },
  "devDependencies": {
    "jest": "^26.6.3"
  },
  "author": "deepak",
  "license": "ISC",
  "dependencies": {
    "chrome-aws-lambda": "^9.0.0",
    "date-and-time": "^1.0.1",
    "html-pdf": "^3.0.1",
    "path": "^0.12.7",
    "playwright-core": "^1.8.1",
    "puppeteer-core": "^9.0.0"
  }
}

##### code ####
const chromium = require('chrome-aws-lambda');

const browser = await chromium.puppeteer.launch({
    args: chromium.args,
    defaultViewport: chromium.defaultViewport,
    executablePath: await chromium.executablePath,
    headless: chromium.headless,
    ignoreHTTPSErrors: true,
});
const page = await browser.newPage();

await page.setContent(html_text);

const pdf = await page.pdf({format: 'A4',
    displayHeaderFooter: true,
    printBackground: true,
    landscape: true,
    headerTemplate: '<div></div>',
    footerTemplate: '<div id="footer-template" style="font-family:sans-serif !important; font-weight: 535;  letter-spacing: -0.5px; font-size:8px !important; color:#cacbce; padding-left:30px">' + footertxt + '</span></div><span class="pageNumber"></span><span class="totalPages"></span>',
    margin: {
        top: '50px',
        bottom: '50px',
        right: '0px',
        left: '0px',
    }
});

await browser.close();
return pdf;
