### ISSUE TITLE
How to compile for lambda Node 14?

### ISSUE THREAD

**Issue by lajpatshah** [alixaxel/chrome-aws-lambda#221]
I am extremely sorry for the stupid question. Please can someone guide me how to compile the package for lambda node 14?

Last time i had downloaded the binaries hence the creation part was skipped.

do i have to do the following on EC2 or can I do locally? Exactly where am I supposed to run the below code?
```
git clone --depth=1 https://github.com/alixaxel/chrome-aws-lambda.git && \
cd chrome-aws-lambda && \
make chrome_aws_lambda.zip
```

**Comment by alixaxel** [comment]
@lajpatshah There's nothing specific that you need to compile for Node 14, this package is compatible with Node 10/12/14 out of the box. If you want to package your own layer, you should run those commands on any Posix-like system (Mac, Linux, WSL).

**Comment by alixaxel** [comment]
@lajpatshah From the README:

> Alternatively, you can also download the layer artifact from one of our CI workflow runs.

https://github.com/alixaxel/chrome-aws-lambda/actions/workflows/aws.yml?query=is%3Asuccess+branch%3Amaster
