### ISSUE TITLE
[BUG] Can't find the file on Lambda

### ISSUE THREAD

**Issue by gabrielenosso** [alixaxel/chrome-aws-lambda#222]
I am not able to launch Chrome, seems that the code to find the bin file is broken.

AWS STEPS:
- Download artifact 10.0.0 (https://github.com/alixaxel/chrome-aws-lambda/actions/runs/913612003)
- Extacted the file "chrome-aws-lambda.zip" from the artifact
- Created new Lambda layer for Node 14, uploading the zip file (renamed to "chrome.zip") to create the new Layer
- Added Layer to the Lambda function (Node 14)

CODE OF THE LAMBDA FUNCTION:
`
browser = await chromium.puppeteer.launch({
      args: chromium.args,
      defaultViewport: chromium.defaultViewport,
      executablePath: await chromium.executablePath,
      headless: chromium.headless,
      ignoreHTTPSErrors: true,
    });
`

from package.json:
`
"dependencies": {
    "chrome-aws-lambda": "^10.0.0",
    "puppeteer-core": "^10.0.0"
  }
`

IMPORTANT: before deploying the lambda, I remove the chromium.br file from the lambda.zip file (as the Lambda function should use the chromium.br file in the Lambda Layer)

Error when running the lambda:
`{
  "errorType": "Error",
  "errorMessage": "Error: ENOENT: no such file or directory, open '/var/task/node_modules/chrome-aws-lambda/bin/chromium.br'",
  "trace": [
    "Error: Error: ENOENT: no such file or directory, open '/var/task/node_modules/chrome-aws-lambda/bin/chromium.br'",
    "    at /var/task/index.js:59:15",
    "    at Generator.throw (<anonymous>)",
    "    at rejected (/var/task/index.js:6:65)"
  ]
}`

What am I missing?

**Comment by gabrielenosso** [comment]
I made steps forward: I found out that the steps noted as "IMPORTANT" was wrong (to be used with this module).
I am now removing all the "node_modules/chrome-aws-lambda/bin" folder before uploading the Lambda function code.

It finds now the binary file, but I get a new error:
ERROR	Error: spawn ETXTBSY

Stuck again.

**Comment by gabrielenosso** [comment]
Same error (ETXTBSY) using the lambda function code in the README file.

**Comment by alixaxel** [comment]
@gabrielenosso If you are using the Lambda Layer, then you shouldn't be bundling `chrome-aws-lambda` and `puppeteer-core` in your Lambda code. Quick solution to this is to change your package.json `dependencies` to `devDependencies`:

```
"devDependencies": { "chrome-aws-lambda": "^10.0.0", "puppeteer-core": "^10.0.0" }
```

And then just ship production dependencies.

If you remove `node_modules/chrome-aws-lambda/bin` it's expected that you get the `ENOENT` error.
