### ISSUE TITLE
[DOCUMENTATION] Unable to use with Lambda Layer in Node 14

### ISSUE THREAD

**Issue by gabrielenosso** [alixaxel/chrome-aws-lambda#223]
Could anyone write how to use this package with a Lambda layer?

The documentation doesn't mention anywhere the path that the file should have in the Layer zip file.

The files downloaded from the CI system, as written in the documentation, have something like:
chrome-aws-lambda.zip -> chrome-aws-lambda.zip -> nodejs/node_modules/chrome-aws-lambda/bin

If I create the layer by myself following the documentation command, then I get this:
chrome-aws-lambda.zip -> bin

With both of them I can't make Chrome start properly...
What is the correct path for the layer?

And how does the package get the right path?
(Seems that "executablePath" is failing in finding the proper one)

Maybe it doesn't work properly with Node14?

**Comment by jeffreyroshan** [comment]
When making a Layer:

1. Wrap your entire "project" folder within a "nodejs" folder.
2. Install node modules within your "project" folder.
3. Now ZIP the "nodejs" folder --> This is what you need to upload to AWS Lambda Layers

To Verify:
Unzip the folder -> It should have a "nodejs" folder extracted and everything else within that.

Attached screenshot

![Screenshot 2021-06-20 at 1 52 10 PM](https://user-images.githubusercontent.com/2136271/122667128-e592bf80-d1ce-11eb-8d4e-db033803e711.png)

**Comment by alixaxel** [comment]
@gabrielenosso If you run the provided command verbatim it should work (make sure you are using a recent NPM version).

Alternatively, you can also fetch a Layer artifact from the [AWS Lambda CI GitHub Action](https://github.com/alixaxel/chrome-aws-lambda/actions/runs/913612003):

![image](https://user-images.githubusercontent.com/262782/125048047-71de2700-e097-11eb-81ea-799c75b7f1d3.png)
