### ISSUE TITLE
[BUG] Webpack 5: Currently no loaders are configured to process this file

### ISSUE THREAD

**Issue by joostmeijles** [alixaxel/chrome-aws-lambda#224]
## Environment
* `chrome-aws-lambda` Version: 10.0.0
* `puppeteer` / `puppeteer-core` Version: 10.0.0 / 10.0.0
* OS: Linux
* Node.js Version: 14.x
* Lambda / GCF Runtime: `nodejs12.x`

## Expected Behavior

I am upgrading to NextJS 11 which uses Webpack 5 I expect to build without errors, but error below.

## Current Behavior

info  - Creating an optimized production build .(node:26790) [DEP0148] DeprecationWarning: Use of deprecated folder mapping "./" in the "exports" field module resolution of the package at /home/joost/node_modules/es-abstract/package.json.
Update this package.json to use a subpath pattern like "./*".
(Use `node --trace-deprecation ...` to show where the warning was created)
(node:26766) [DEP_WEBPACK_CHUNK_HAS_ENTRY_MODULE] DeprecationWarning: Chunk.hasEntryModule: Use new ChunkGraph API
(Use `node --trace-deprecation ...` to show where the warning was created)
(node:26766) [DEP_WEBPACK_CHUNK_ADD_MODULE] DeprecationWarning: Chunk.addModule: Use new ChunkGraph API
info  - Creating an optimized production build
Failed to compile.

./node_modules/chrome-aws-lambda/build/puppeteer/lib/Browser.js.map
Module parse failed: Unexpected token (1:10)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> {"version":3,"file":"Browser.js","sourceRoot":"","sources":["../../../source/puppeteer/lib/Browser.ts"],"names":[],"mappings":";;AAGA,IAAI,KAAK,GAAuB,IAAI,CAAC;AAErC,IAAI;IACF,KAAK,GAAG,OAAO,CAAC,4CAA4C,CAAC,CAAC,OAAO,CAAC;CACvE;AAAC,OAAO,KAAK,EAAE;IACd,KAAK,GAAG,OAAO,CAAC,iDAAiD,CAAC,CAAC,OAAO,CAAC;CAC5E;AAED,KAAK,CAAC,SAAS,CAAC,WAAW,GAAG,KAAK,WAAW,GAAG,KAAa;IAC5D,IAAI,IAAI,GAAS,IAAI,CAAC;IACtB,IAAI,KAAK,GAAW,MAAM,IAAI,CAAC,KAAK,EAAE,CAAC;IAEvC,IAAI,KAAK,CAAC,MAAM,KAAK,CAAC,EAAE;QACtB,KAAK,GAAG,CAAC,MAAM,IAAI,CAAC,OAAO,EAAE,CAAC,CAAC;KAChC;IAED,IAAI,GAAG,KAAK,CAAC,KAAK,EAAE,CAAC;IAErB,IAAI,KAAK,IAAI,IAAI,IAAI,KAAK,CAAC,OAAO,CAAC,KAAK,CAAC,KAAK,IAAI,EAAE;QAClD,KAAK,IAAI,IAAI,IAAI,KAAK,EAAE;YACtB,IAAI,GAAG,MAAM,IAAI,CAAC,IAAI,CAAC,CAAC;SACzB;KACF;IAED,OAAO,IAAI,CAAC;AACd,CAAC,CAAC;AAEF,IAAI,OAAO,GAAQ,KAAK,CAAC,SAAS,CAAC,OAAO,CAAC;AAE3C,KAAK,CAAC,SAAS,CAAC,OAAO,GAAG,KAAK,WAAW,GAAG,KAAa;IACxD,IAAI,IAAI,GAAS,MAAM,OAAO,CAAC,KAAK,CAAC,IAAI,EAAE,SAAS,CAAC,CAAC;IAEtD,IAAI,KAAK,IAAI,IAAI,IAAI,KAAK,CAAC,OAAO,CAAC,KAAK,CAAC,KAAK,IAAI,EAAE;QAClD,KAAK,IAAI,IAAI,IAAI,KAAK,EAAE;YACtB,IAAI,GAAG,MAAM,IAAI,CAAC,IAAI,CAAC,CAAC;SACzB;KACF;IAED,OAAO,IAAI,CAAC;AACd,CAAC,CAAC"}

> Build error occurred
Error: > Build failed because of webpack errors
    at /home/joost/node_modules/next/dist/build/index.js:15:924
    at async Span.traceAsyncFn (/home/joost/node_modules/next/dist/telemetry/trace/trace.js:6:584)

## Steps to Reproduce
```
const chromium = require('chrome-aws-lambda');
const browser = await chromium.puppeteer.launch({
            headless: chromium.headless, // Returns true when serverless
            args: chromium.args,
            executablePath: await chromium.executablePath,
        });
```

**Comment by joostmeijles** [comment]
Turned out to be a next config issue: https://github.com/vercel/next.js/discussions/26478

**Comment by derekslarson** [comment]
I am seeing this same error attempting to bundle functions to deploy to GCP. Next.js is not involved.

**Comment by rdsedmundo** [comment]
Solution is to mark this package as an external so webpack doesn't bundle it.

**webpack.config.js**
```
module.exports = ... {
  ...
  externals: ['chrome-aws-lambda'],
}
```

**Comment by minlare** [comment]
> Solution is to mark this package as an external so webpack doesn't bundle it.
> 
> **webpack.config.js**
> 
> ```
> module.exports = ... {
>   ...
>   externals: ['chrome-aws-lambda'],
> }
> ```

Worked for me and I added the package as a layer on AWS Lambda
