### ISSUE TITLE
How to work with time zones?

### ISSUE THREAD

**Issue by maxmoore14** [alixaxel/chrome-aws-lambda#227]
Trying to use .toLocaleString("en-AU") but still getting UTC/GMT. Is there a way to build this to include internationalization options and/or simply specify a local time zone?

**Comment by alixaxel** [comment]
@maxmoore14 If you don't specify a timezone it will default to the environment timezone (which for Lambda is UTC).

You need to use [`await page.emulateTimezone('Australia/Sydney');`](https://pptr.dev/#?product=Puppeteer&version=v10.1.0&show=api-pageemulatetimezonetimezoneid).
