### ISSUE TITLE
ERR_CONNECTION_CLOSED when loading sample code

### ISSUE THREAD

**Issue by JordanYankovich** [alixaxel/chrome-aws-lambda#23]
Here are the steps to reproduce, owe a drink if anyone can help me out. 

1. Create new node project with index file with sample code provided 
`const chromium = require('chrome-aws-lambda');
const puppeteer = require('puppeteer-core');

exports.handler = async (event, context) => {
    let result = null;
    let browser = null;

    try {
        browser = await puppeteer.launch({
            args: chromium.args,
            defaultViewport: chromium.defaultViewport,
            executablePath: await chromium.executablePath,
            headless: chromium.headless,
        });

        let page = await browser.newPage();

        await page.goto(event.url || 'https://example.com');

        result = await page.title();
    } catch (error) {
        return context.fail(error);
    } finally {
        if (browser !== null) {
            await browser.close();
        }
    }

    return context.succeed(result);
};
execute();`
2. run npm install for both "chrome-aws-lambda" and "puppeteer-core"
3. Zip the index.js and node_modules folder into s3 bucket
4. Create lambda function that references s3 bucket. 
5. Create test event, get connection error

Here is the full error I am receiving 
`{
  "errorMessage": "net::ERR_CONNECTION_CLOSED at https://example.com",
  "errorType": "Error",
  "stackTrace": [
    "navigate (/var/task/node_modules/puppeteer-core/lib/FrameManager.js:101:37)",
    "<anonymous>",
    "process._tickDomainCallback (internal/process/next_tick.js:228:7)",
    "  -- ASYNC --",
    "Frame.<anonymous> (/var/task/node_modules/puppeteer-core/lib/helper.js:108:27)",
    "Page.goto (/var/task/node_modules/puppeteer-core/lib/Page.js:662:49)",
    "Page.<anonymous> (/var/task/node_modules/puppeteer-core/lib/helper.js:109:23)",
    "exports.handler (/var/task/index.js:18:20)",
    "<anonymous>",
    "process._tickDomainCallback (internal/process/next_tick.js:228:7)"
  ]
}`

**Comment by alixaxel** [comment]
Hi @JordanYankovich, thanks for reporting this. It seems to be related to https://github.com/GoogleChrome/puppeteer/issues/3880.

Basically Chromium revision `r624487` (introduced in puppeteer 1.12.0 / 1.12.1) has this problem, and it's supposedly addressed in revision `r624492` (puppeteer 1.12.2). Oddly enough, both revisions map to the same Chromium version (`73.0.3679.0`) that's why it went unnoticed.

I will recompile Chromium and should have the new binary in a few hours.
