### ISSUE TITLE
Dynamic Injection of Fonts

### ISSUE THREAD

**Issue by alixaxel** [alixaxel/chrome-aws-lambda#24]
Explore the idea of providing an additional method to this package that will take a URL to a font and:

- download it once into the appropriate directory
- patch the environment variables so that Chromium knows where to look for it

Would address #4 and #16 in a consistent and easy way.

**Comment by dattto** [comment]
Is the font storing and loading be done in the following manner?
https://github.com/adieuadieu/serverless-chrome/issues/49#issuecomment-378371782

**Comment by alixaxel** [comment]
@dattto Probably not to `/var/task` but yeah, similar concept.

This is something I still need to investigate and test.
