### ISSUE TITLE
[QUESTION] Procedure for updating software

### ISSUE THREAD

**Issue by mifisignal** [alixaxel/chrome-aws-lambda#256]
What is the procedure for updating and maintaining the artifacts in the `bin` folder of this repository? Is there a script you're using that's in this repository? If so, I am having difficulty locating it.

**Comment by bestplay9384** [comment]
There are ansible automation scripts that @alixaxel provided here: https://github.com/alixaxel/chrome-aws-lambda/tree/master/_/ansible 

They are starting up big AWS EC2 with Amazon Linux 2 and the compilation executes there :)

**Comment by mifisignal** [comment]
Thanks so much! Closing.
