### ISSUE TITLE
Caching fonts in layers

### ISSUE THREAD

**Issue by j** [alixaxel/chrome-aws-lambda#26]
How can I keep the cached fonts in a layer?

**Comment by alixaxel** [comment]
@j Not really possible with the current approach, as the data needs to live in `/tmp`.

**Comment by tobiaslins** [comment]
@j You can serve font's with a layer aswell. The layer should include a `.fonts` directory containing all your font files. Puppeteer will pick them up automatically

**Comment by davej** [comment]
@tobiaslins Are there any additional steps? I added a `.fonts` directory to the root of my layer but Puppeteer is not picking them up.

**Comment by bendadaniel** [comment]
+1

**Comment by alixaxel** [comment]
Since version 3.0.4 you can use the `font()` method to symlink a local font path to the right folder.
