### ISSUE TITLE
Error: spawn EACCES

### ISSUE THREAD

**Issue by tarikbellamine** [alixaxel/chrome-aws-lambda#28]
Hey there. Thanks for building this out...obviously it has been very helpful to a lot people :)

I am having an issue launching a browser both when attempting to launch locally and when deployed to Lambda.

My setup:
Node: v8.10

```javascript
const puppeteer = require('puppeteer-core');
const chromium = require('chrome-aws-lambda');

const browser = await puppeteer.launch({
    args: chromium.args,
    defaultViewport: chromium.defaultViewport,
    executablePath: await chromium.executablePath,
    headless: chromium.headless,
  });
```

The error message from Lambda console:
```
(node:1) UnhandledPromiseRejectionWarning: Error: spawn EACCES
    at _errnoException (util.js:1022:11)
    at ChildProcess.spawn (internal/child_process.js:323:11)
    at Object.exports.spawn (child_process.js:502:9)
    at Launcher.launch (/var/task/node_modules/puppeteer-core/lib/Launcher.js:126:40)
    at <anonymous>
```

I also got this error the first time I ran it locally but wasn't able to recreate:
```
Error --------------------------------------------------
 
  Cannot find module 'iltorb'
```

I've maxed out my memory allocation but still doesn't work. Any ideas?

**Comment by joseph4tw** [comment]
I'm having the exact same issue. I tried reverting to version `1.12.0` for both `chrome-aws-lambda` and `puppeteer-core`, but I'm still having the same issue. I also cannot reproduce this locally.

This was working fine a couple of weeks ago. I'm really not sure what changed (maybe something in AWS Lambda changed, too, but I'm not sure yet).

**Comment by joseph4tw** [comment]
I just figured it out. Somehow, my Lambda function's memory got reduced to 128 MB. I reset this back to 2048 MB and it's working again.

**Comment by alixaxel** [comment]
The error you get locally is expected, regarding the other one I'll take a look shortly and get back to you.

**Comment by mbaudin** [comment]
We are having the same issue. It not related to memory size of lambda. All our lambdas run with 2000MB

**Comment by alixaxel** [comment]
I cannot reproduce this issue, just launched a brand new 1.13 version and everything works as expected.

@tarikbellamine You only shared a snippet so I cannot really be sure, but I suspect the issue might be that you are not executing the `await`s inside an `async` scope? Could you try with the sample code shared on the README and tell me if the issue is gone?

**Comment by mbaudin** [comment]
Just found what causes it for us, it’s when we add tracing from https://epsagon.com/. Works when we disable that.

**Comment by crsepulv** [comment]
this solved this problem for me: [https://github.com/alixaxel/chrome-aws-lambda/issues/67#issuecomment-544902016](url)
