### ISSUE TITLE
Issue running with webpack + typescript

### ISSUE THREAD

**Issue by jrbarnard** [alixaxel/chrome-aws-lambda#29]
I'm currently having trouble getting this running with webpack + typescript with serverless framework.

It seems to be having issues with the including iltorb binary file.

Example error on webpack build
<img width="705" alt="Screenshot 2019-03-27 at 17 22 32" src="https://user-images.githubusercontent.com/6758366/55098062-097cfe80-50b5-11e9-8b69-7adbce8742a4.png">

Let me know what additional info you need.

**Comment by jrbarnard** [comment]
It was fine, I messed up and didn't add node-loader to webpack for .node files

**Comment by robophil** [comment]
> It was fine, I messed up and didn't add node-loader to webpack for .node files

And how did you go about this @jrbarnard ?

**Comment by jrbarnard** [comment]
@robophil In webpack.config.js I added the node-loader under module->rules so that webpack can load and process .node files.
```
{
        test: /\.node$/,
        loader: 'node-loader'
}
```

**Comment by robophil** [comment]
I did this and still the same

```
 ⨯ ModuleNotFoundError: Module not found: Error: Can't resolve 'iltorb' in '/path2project/node_modules/chrome-aws-lambda/source'
```

**Comment by robophil** [comment]
I had to install `iltorb` to get this to work 👍 
Now, running this on AWS i see
```
{
  "errorMessage": "path2project/node_modules/chrome-aws-lambda/source/iltorb/build/bindings/iltorb.node: Error: path2project/node_modules/chrome-aws-lambda/source/iltorb/build/bindings/iltorb.node: cannot open shared object file: No such file or directory",
  "errorType": "Error",
  "stackTrace": [
    "Object.eval (webpack:////path2project/node_modules/chrome-aws-lambda/source/iltorb/build/bindings/iltorb.node?:1:240)",
    "eval (webpack:////path2project/node_modules/chrome-aws-lambda/source/iltorb/build/bindings/iltorb.node?:2:30)",
    "Object.../../node_modules/chrome-aws-lambda/source/iltorb/build/bindings/iltorb.node (/var/task/lib/index.js:1399:1)",
}
```

**Comment by jrbarnard** [comment]
I did also add `'chrome-aws-lambda': 'chrome-aws-lambda',` in the externals section of my webpack.config.js in order for it to get deployed with the package up to lambda.

**Comment by robophil** [comment]
Webpack simply just excluded it by adding it to externals

![Screenshot 2019-05-07 at 15 41 17](https://user-images.githubusercontent.com/6032018/57303951-af714f00-70de-11e9-9294-e79a0d6da2a8.png)

**Comment by jrbarnard** [comment]
Is includeModules set in your serverless config? https://github.com/serverless-heaven/serverless-webpack#node-modules--externals.

(I'm assuming you're using serverless + serverless-webpack based on my original issue).
