### ISSUE TITLE
"Core" version

### ISSUE THREAD

**Issue by schris403** [alixaxel/chrome-aws-lambda#31]
Would it be possible for you to create a "core" version of this package like puppeteer-core did or create a flag where the chromium binary isn't downloaded? We want to build our own AWS layer with the chromium version built in (extracting it from this package). This way we can include your package (without chromium pre-installed) in our package.json and still keep our bundle size small.

**Comment by alixaxel** [comment]
@schris403 The main purpose of this package is to provide a statically compiled version of Chromium. So I'm not sure I understand your use case...

You know that there are instructions to build a AWS Layer of this package with puppeteer-core, right?

If you could explain better what your goal is, it would be helpful.

**Comment by hermanho** [comment]
I have similar case. I want to reduce the deployment size of the lambda package. To archive that, I remove the binary "bin/chromium-75.0.3738.0.br" in node_modules before pack in AWS SAM and download the binary when running on lambda from github hot-linking / s3. 

It is similar to installing "puppeteer" with PUPPETEER_SKIP_CHROMIUM_DOWNLOAD environment variable.

**Comment by alixaxel** [comment]
I feel like using an AWS Lambda Layer would be the most appropriate way of decreasing deployment size:

https://github.com/alixaxel/chrome-aws-lambda#aws-lambda-layer
