### ISSUE TITLE
Error: Cannot find module 'iltorb'

### ISSUE THREAD

**Issue by steida** [alixaxel/chrome-aws-lambda#33]
When I updated to chrome-aws-lambda 1.15.0. Is it my error or something else?

**Comment by alixaxel** [comment]
My bad, will push a fix shortly.

**Comment by alixaxel** [comment]
@steida This should be addressed in 1.15.1.

**Comment by NWRichmond** [comment]
I'm also getting `Error: Cannot find module 'iltorb'`, but with 1.19.0

**Comment by imhuyqn** [comment]
> @alixaxel I'm also getting `Error: Cannot find module 'iltorb'`, but with 1.19.0
> 
> **UPDATE**
> 
> I am using Zeit Now and it was defaulting to node v 10.x - `chrome-aws-lambda` started working beautifully once I specified node v 8.10.x by adding:
> 
> ```js
> "engines": {
>     "node": "8.10.x"
>   },
> ```
> 
> to `package.json`

I am having the same problem but updating the Node version doesn't work for me :/

**Comment by NWRichmond** [comment]
@imhuyqn are you using Zeit Now 2.0 or AWS? Or something different?

**Comment by imhuyqn** [comment]
> @imhuyqn are you using Zeit Now 2.0 or AWS? Or something different?

I am using Zeit Now 2. I tried to change the engines to node 8.10.x too. But it didn't work. Weird. I had another solution but it costs about $30/month.
