### ISSUE TITLE
Error: Chromium revision is not downloaded. Run "npm install" or "yarn install"

### ISSUE THREAD

**Issue by ludbek** [alixaxel/chrome-aws-lambda#34]
While trying the example code in readme file I got following error

`Error: Chromium revision is not downloaded. Run "npm install" or "yarn install"`

Update
------------
Turns out the path to chrome is null for non lambda environment.
I am using docker image which is similar to aws lambda. Is there a way to get the path to the chrome installed by `chrome-aws-lambda`?

**Comment by alixaxel** [comment]
Yes, you can set the following environment variables in order to trick it into thinking it's within Lambda:

- `AWS_EXECUTION_ENV = "AWS_Lambda_nodejs8.10"`
- `AWS_LAMBDA_FUNCTION_NAME = "..."`

**Comment by ludbek** [comment]
Awesome thanks.

**Comment by alixaxel** [comment]
For anyone who comes across this, here's a better explanation:

https://github.com/alixaxel/chrome-aws-lambda/wiki/HOWTO:-Local-Development
