### ISSUE TITLE
node10.x

### ISSUE THREAD

**Issue by nelson-andrew** [alixaxel/chrome-aws-lambda#36]
Currently does not support node10.x

**Comment by alixaxel** [comment]
Version 1.16.0 now supports Node 10.x.

**Comment by alixaxel** [comment]
Duplicate of #37.

**Comment by alixaxel** [comment]
@nelson-andrew Just FYI - latest version now supports node10.x.

**Comment by nelson-andrew** [comment]
Thanks so much for letting me know.

Cheers
Andrew
