### ISSUE TITLE
GCP Cloud Functions Node10 environment does not anymore set FUNCTION_NAME env

### ISSUE THREAD

**Issue by hixus** [alixaxel/chrome-aws-lambda#38]
GCP Cloud Functions Node10 environment does not anymore set FUNCTION_NAME environment variable (https://cloud.google.com/functions/docs/env-var)

This is used for setting correct launch parameters so the check should be replaced with FUNCTION_TARGET

Workaround for this is to set it by yourself when running `gcloud functions deploy myfunc --runtime nodejs10 --memory 2048MB --trigger-http --set-env-vars=FUNCTION_NAME=myfunc`

**Comment by alixaxel** [comment]
@hixus Thanks for reporting this, the 1.17.0 release should already handle the new ENV variable.
