### ISSUE TITLE
Support for video tags.

### ISSUE THREAD

**Issue by TimotheeJeannin** [alixaxel/chrome-aws-lambda#39]
From the ansible playbook it looks like the proprietary codecs are bundled in the Chromium build:

https://github.com/alixaxel/chrome-aws-lambda/blob/9fe9b7014a2327402937e9570fdb3d9682ed3314/_/ansible/plays/chromium.yml#L232

But `<video>` tags don't seem to load. 

For example, [the demo from mozilla](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/video) doesn't load. 

Is this expected?

**Comment by alixaxel** [comment]
@TimotheeJeannin To be honest, I haven't tested it yet.

Could you provide an example repro so that I can look into this?

**Comment by TimotheeJeannin** [comment]
@alixaxel I will add an example as soon as I have time.

**Comment by TimotheeJeannin** [comment]
@alixaxel Here is an example that reproduces the issue. 

```javascript
const chromium = require('chrome-aws-lambda');

exports.handler = async (event, context) => {
    let result = null;
    let browser = null;

    try {
        browser = await chromium.puppeteer.launch({
            args: chromium.args,
            defaultViewport: chromium.defaultViewport,
            executablePath: await chromium.executablePath,
            headless: chromium.headless,
        });

        let page = await browser.newPage();

        await page.goto('https://developer.mozilla.org/en-US/docs/Web/HTML/Element/video');

        result = await page.screenshot({encoding: 'base64'});
    } catch (error) {
        return context.fail(error);
    } finally {
        if (browser !== null) {
            await browser.close();
        }
    }

    return context.succeed(result);
};
```
On the right side of the screenshot, on AWS Lambda, the video is blank/empty. 
With the bundled chromium that comes with puppeteer, the video is properly loaded.

**Comment by alixaxel** [comment]
@TimotheeJeannin Thanks! So yeah, I can replicate this:

![image](https://user-images.githubusercontent.com/262782/59710817-ab6a3e00-9201-11e9-8900-379274c5eddb.png)

---

![image](https://user-images.githubusercontent.com/262782/59710828-b0c78880-9201-11e9-895f-9e98dbc76b43.png)

In the next build I will attempt to tweak around with some flags to see if that helps.

Otherwise, seems like the only sensible thing to do it to disable `proprietary_codecs`.

**Comment by TimotheeJeannin** [comment]
Thank you @alixaxel for investigating this. 

Regarding YouTube, I think the video tag displays correctly if you add the `--disable-gpu` flag. I'm not sure there is a GPU on AWS Lambda and what exact effect this flag has, but it makes youtube works. 

![image](https://user-images.githubusercontent.com/1969368/59741675-f325af80-926b-11e9-83d7-94b44762af35.png)

But for the [Mozilla demo](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/video) adding the `--disable-gpu` flag does not help.

**Comment by alixaxel** [comment]
@TimotheeJeannin 

If I blindly replace the URL with a YouTube one on your snippet, I also see this:

![image](https://user-images.githubusercontent.com/262782/59977571-965b2980-95ca-11e9-8447-17e8c714de95.png)

However, I believe this is simply a placeholder image for the video / ads, when I start video playback with:

```javascript
await page.waitFor('video');

await page.evaluate(() => {
    return document.querySelector('video').play();
});

await page.waitFor(5000); // play this much
```

I get this black screen:

![image](https://user-images.githubusercontent.com/262782/59977593-d6baa780-95ca-11e9-8fab-f249e9a1c46a.png)

If I increase the 5 seconds of playtime to 15 seconds (to ensure ads finalize), I get the blank screen:

![image](https://user-images.githubusercontent.com/262782/59977619-2ef1a980-95cb-11e9-92fb-066645f2722e.png)

Which is the same I shared previously. The `--disable-gpu` flag doesn't seem to have any effect.

So it seems that video playback is simply not supported at all in headless / serverless.

I'm curious if you are in fact getting different results?

**Comment by TimotheeJeannin** [comment]
Hi @alixaxel, my bad, I incorrectly concluded that the `--disable-gpu`  had an effect on youtube videos, but it turns out I messed up my testing. 

I tried with and without the `--disable-gpu` after playing the video and I do have the same blank space:

![image](https://user-images.githubusercontent.com/1969368/60517749-7de0c280-9ce0-11e9-938f-dcdc63aeb629.png)

**Comment by TimotheeJeannin** [comment]
Hi @alixaxel, any news on this issue? Is there any way I can help? Should I try to rebuild Chrome with your playbook?

Some websites also use the video tags on their home page. (for example: [https://giffordneurology.com/](https://giffordneurology.com))

**Comment by alixaxel** [comment]
@TimotheeJeannin Sorry, forgot to follow up on this. Unfortunately no, I tested several different combinations of build and runtime parameters and my conclusion is that the culprit is the `--single-process` flag (which is a requirement in AWS Lambda). Even on local with the default `puppeteer` bundle, if you pass this flag to Chrome, it will behave the same way and show a white block instead of the video.

I have removed the `proprietary_codecs` build flag on 1.18.0, at least that will save up some KBs.

**Comment by mhart** [comment]
So I've done some testing and I don't think it's the `<video>` tag per se, but rather something to do with audio being loaded. You can actually screengrab video tags *IF* the video file in question has no audio track. If it does have an audio track, then Chromium crashes with this:

```
[0220/183001.341768:FATAL:service.cc(56)] Check failed: !base::SystemMonitor::Get(). 
#0 0x5562725f8939 <unknown>
#1 0x55627256a443 <unknown>
#2 0x55627257b4d5 <unknown>
#3 0x5562718709b1 <unknown>
#4 0x556271872fe6 <unknown>
#5 0x556272526e26 <unknown>
#6 0x556272527c54 <unknown>
#7 0x556273d2692c <unknown>
#8 0x5562725a8a1b <unknown>
#9 0x5562725b97ce <unknown>
#10 0x5562725b9561 <unknown>
#11 0x55627257f9ca <unknown>
#12 0x5562725ba059 <unknown>
#13 0x5562725965e2 <unknown>
#14 0x5562725ce037 <unknown>
#15 0x556272607f1e <unknown>
#16 0x7fbb222e040b start_thread
#17 0x7fbb21680e7f __GI___clone
Task trace:
#0 0x556273d2645a <unknown>
#1 0x556272e74c85 <unknown>
#2 0x556272e8b921 <unknown>
#3 0x556273d241b8 <unknown>
#4 0x5562725253f9 <unknown>
IPC message handler context: 0x1D6C7CD1
```

Which I'm guessing is crashing on this line here in src/services/audio/service.cc:

https://cs.chromium.org/chromium/src/services/audio/service.cc?dr&sq=package:chromium&q=service.cc&g=0&l=53

I haven't found any flags yet to disable the audio service entirely and prevent this line from running. If no flag exists, then another route *might* be to see if including certain audio libraries would help (ie, alsa libs)

**Comment by bestplay9384** [comment]
> So I've done some testing and I don't think it's the `<video>` tag per se, but rather something to do with audio being loaded. You can actually screengrab video tags (thanks to proprietary_codecs being re-enabled) _IF_ the video file in question has no audio track. If it does have an audio track, then Chromium crashes with this:
> 
> ```
> [0220/183001.341768:FATAL:service.cc(56)] Check failed: !base::SystemMonitor::Get(). 
> #0 0x5562725f8939 <unknown>
> #1 0x55627256a443 <unknown>
> #2 0x55627257b4d5 <unknown>
> #3 0x5562718709b1 <unknown>
> #4 0x556271872fe6 <unknown>
> #5 0x556272526e26 <unknown>
> #6 0x556272527c54 <unknown>
> #7 0x556273d2692c <unknown>
> #8 0x5562725a8a1b <unknown>
> #9 0x5562725b97ce <unknown>
> #10 0x5562725b9561 <unknown>
> #11 0x55627257f9ca <unknown>
> #12 0x5562725ba059 <unknown>
> #13 0x5562725965e2 <unknown>
> #14 0x5562725ce037 <unknown>
> #15 0x556272607f1e <unknown>
> #16 0x7fbb222e040b start_thread
> #17 0x7fbb21680e7f __GI___clone
> Task trace:
> #0 0x556273d2645a <unknown>
> #1 0x556272e74c85 <unknown>
> #2 0x556272e8b921 <unknown>
> #3 0x556273d241b8 <unknown>
> #4 0x5562725253f9 <unknown>
> IPC message handler context: 0x1D6C7CD1
> ```
> 
> Which I'm guessing is crashing on this line here in src/services/audio/service.cc:
> 
> https://cs.chromium.org/chromium/src/services/audio/service.cc?l=53&rcl=69e064cc806c109e1dded4ab73447c2c1888d476
> 
> I haven't found any flags yet to disable the audio service entirely and prevent this line from running. If no flag exists, then another route _might_ be to see if including certain audio libraries would help (ie, alsa libs)
> 
> EDIT: also posted on headless-dev at https://groups.google.com/a/chromium.org/forum/#!topic/headless-dev/AhLcox2p-u8

Hey @mhart,

I have the same issue since last puppeteer update i made - from 2.0.0 to 2.1.1 version. I got the same crash error e.g. here: [EXAMPLE URL](https://www.alza.cz/oral-b-genius-8000-d4336166.htm) just by going to this url...

There are **videos** that are **autoplayed** - i think it can cause this crash, on different urls on this shop where no autoplayed videos are available issue does not exist.

Any idea?

**Comment by mhart** [comment]
Yeah, totally have an idea – like I said, I think it's the audio device issue. If the video's not autoplayed, then it won't be trying to access the audio device yet.

**Comment by bestplay9384** [comment]
@mhart, yes you're totally right. The only "solution" i've came up with is to set request interceptor that aborts all request for media resourceType (<video> & <audio> elements). For my case i only use links for these sources so it works for me for now, however they should fix the crash of course... 👍

**Comment by alixaxel** [comment]
Thanks @mhart, you pointed me to the right direction: https://github.com/alixaxel/chrome-aws-lambda/issues/104#issuecomment-625999698

The above argument seems to work even with previous versions of Chromium.

**Comment by mhart** [comment]
Ooh, thanks for the tip @alixaxel – I'll have to try that
