### ISSUE TITLE
Build chrome with non-latin characters support

### ISSUE THREAD

**Issue by mxcoder** [alixaxel/chrome-aws-lambda#4]
Hi @alixaxel , thanks a lot for your work, its been really useful and easy to use.

Although I have one request, could you give me some pointers to build chrome with support for japanase, korean, chinese, etc and other non-latin characters? While using puppeteer + chrome-aws-lambda on some japanase pages, when I take a screenshot, characters are not correctly rendering:

![image](https://user-images.githubusercontent.com/1393626/48669345-4eba6f80-eac8-11e8-8792-b5176c6b8a97.png)

I'm guessing I'd need to tweak the ansible play, then run it to get the expected build. But it might be beyond my experience, I'll try tho, so if you have any pointers I'd appreciate it, if possible I'll try to submit the corresponding PR.

**Comment by mxcoder** [comment]
Nevermind, found the solution :)
Pretty much this comment and the following 2: https://github.com/adieuadieu/serverless-chrome/issues/49#issuecomment-378371782

Thanks again

**Comment by kirilledelman** [comment]
@mxcoder 
I'm also struggling with this: https://github.com/adieuadieu/serverless-chrome/issues/49#issuecomment-443798557

Where do I put `.fonts` directory?

Is Chrome supposed to use the fonts in this dir as fallback if the font on the page it's rendering doesn't contain the characters?

Thank you.

**Comment by mxcoder** [comment]
Hi @kirilledelman , yes! just put the .fonts file in the root of your zip package that you upload to lambda.
At least, I didn't do anything else. You might need to test different formats, but for me .otf fonts worked fine.
