### ISSUE TITLE
v1.17.0 throws 'Printing is not enabled' rendering PDFs

### ISSUE THREAD

**Issue by tspacek** [alixaxel/chrome-aws-lambda#41]
On v1.17.0, a call to `page.pdf` fails with `Protocol error (Page.printToPDF): Printing is not enabled`, which [I think](https://chromium.googlesource.com/chromium/src.git/+/62.0.3178.1/headless/lib/browser/headless_devtools_manager_delegate.cc#299) is due to https://github.com/alixaxel/chrome-aws-lambda/commit/d5b969be8cc109ee133567d517cc3deb810fcf31#diff-a562799028e672851e8b32af90205952R588

Works fine on v1.16.0.

Code that reproduces it:

```
browser = await puppeteer.launch({
        args: [
          '--headless',
          '--disable-gpu',
          '--unlimited-storage',
          '--no-sandbox',
          '--disable-setuid-sandbox',
          '--disable-dev-shm-usage',
          '--disable-extensions',
          '--single-process'
        ],
        defaultViewport: chromium.defaultViewport,
        executablePath: await chromium.executablePath,
        headless: true,
      });
const page = await browser.newPage();
await page.goto("http://example.com", {
        waitUntil: [
          'load'
        ],
        timeout: 0
      });
await page.pdf({
        printBackground: false,
        format: 'A4',
        displayHeaderFooter: false,
      });
```

**Comment by alixaxel** [comment]
Thanks for spotting this, I will run some checks and should have a new patch version available by tomorrow.
