### ISSUE TITLE
Ansible version

### ISSUE THREAD

**Issue by alex88** [alixaxel/chrome-aws-lambda#42]
Thanks for the great library, I was trying to build chromium myself and I'm having a few issues starting ansible due missing vpc, wrong values (e.g. in the Registering host) step.
I've seen latest ansible have different things like ec2_instance instead of ec2, other tasks are deprecated..
Which version of Ansible did you run this with? Just to hopefully make everything easier on my side

**Comment by alixaxel** [comment]
@alex88 I'm running Ansible 2.8.0 and the playbook seems to work fine.

Where did you spot those deprecated tasks?

**Comment by alex88** [comment]
I'm using `ansible-playbook` 2.8 too, for example I had to use `ec2_instance` instead of `ec2` because it wasn't returning the `instances` variables to be used in `add_host`, anyway I'm new to ansible so I might just be using wrong. First issue I had is that I had to use a VPC to start it
