### ISSUE TITLE
Bitbucket + lambda

### ISSUE THREAD

**Issue by rchancey** [alixaxel/chrome-aws-lambda#43]
So wondering how you all manage this when you run a bitbucket pipeline before deploying to lambda. We do our initial testing using bitbucket on a docker image and this package only works on lambda?

I installed this and then added the sample code but then I get:

_Detected an unhandled promise rejection Error: Chromium revision is not downloaded. Run "npm install" or "yarn install"_

and the chromium-76.0.3803.0.br is there.. so I assume somehow this only runs on lambda?

any suggestions?
```

(async () => {
  console.log(`loading chrome `);
  const chromium = require('chrome-aws-lambda');
  browser = await chromium.puppeteer.launch({
    args: chromium.args,
    defaultViewport: chromium.defaultViewport,
    executablePath: await chromium.executablePath,
    headless: chromium.headless,
  });

  let page = await browser.newPage();

  await page.goto(event.url || 'https://example.com');

  result = await page.title();
  console.log(`result `, result);
})();


```

**Comment by alixaxel** [comment]
@rchancey Yeah, the binary is compiled to be compatible with Lambda, so by default it only runs there.

If your Docker image is based on Node 8.10, you could try to define the following environment variables:

- `AWS_EXECUTION_ENV=AWS_Lambda_nodejs8.10`
- `AWS_LAMBDA_FUNCTION_NAME=docker`

That should trick it into thinking it's running in a Lambda environment.

**Comment by rchancey** [comment]
I know this is closed but I ended up going with this solution: https://jsreport.net/learn/aws-lambda-serverless

I am using JSReport and needed to update to Chrome. 

For others who end up here and are looking for solutions to this challenge.
