### ISSUE TITLE
Defaults chrome to USA time

### ISSUE THREAD

**Issue by arrayoutofbounds** [alixaxel/chrome-aws-lambda#48]
Just want to apologise if I am missing any information.

Basically, I am trying to scrape a website that loads new data every day. The issue is that it seems to be giving me the data from the day before.

`await page.evaluate(() => document.body.innerHTML);`

The result of the command above gives me the data from the day before, instead of my current day.
I live in australia, but end up getting the previous day's data until its 12 am in USA.

To check that if I was wrong, I installed the full version of puppeteer and did a test. It got me the updated data for my current location. I was just curious to know if there is a way to fix the locale or region in the chrome bundled. I would be more than happy to help.

**Comment by alixaxel** [comment]
@arrayoutofbounds 

All AWS Lambda instances, regardless of which region they are in, have their timezone set to UTC/GMT.

You can check this, by looking into the `TZ` environment variable:

```javascript
// ":UTC"
console.log(process.env.TZ);
```

Chrome inherits this timezone, as confirmed by the following snippet:

```javascript
// "Sun Jun 23 2019 13:31:35 GMT+0000 (Coordinated Universal Time)"
console.log(await page.evaluate(() => (new Date()).toString()));
```

It seems that you issue is specific to the page you're parsing, but without the actual URL it's hard to tell.
