### ISSUE TITLE
Setup `user-data-dir` flag

### ISSUE THREAD

**Issue by Kikobeats** [alixaxel/chrome-aws-lambda#53]
I'm reading a [blog post about puppeteer perfomance](https://docs.browserless.io/blog/2019/05/03/improving-puppeteer-performance.html) and feeling makes totally sense point `--user-data-dir` to `/tmp` into an AWS Lambda scenario.

Thoughts?

**Comment by TimotheeJeannin** [comment]
Puppeteer already creates a temporary user data dir. See [Launcher.js line 113](https://github.com/GoogleChrome/puppeteer/blob/2abaac10aadbc36e6cb35a712c9558854e1159d2/lib/Launcher.js#L113).

I think it's good to provide a default set of arguments that make the chromium binary work well with AWS Lambda but setting a default user data directory is too much. Some people might want to have only one data dir reused across invocations some other might want to have a new one for each invocation. I don't think this package should be responsible for this.

**Comment by alixaxel** [comment]
@Kikobeats As @TimotheeJeannin mentioned, puppeteer already sets a `user-data-dir` by default:

https://github.com/GoogleChrome/puppeteer/blob/2abaac10aadbc36e6cb35a712c9558854e1159d2/lib/Launcher.js#L36
