### ISSUE TITLE
Not working on AWS Lambda with Node 8 + Layers

### ISSUE THREAD

**Issue by AdamAH** [alixaxel/chrome-aws-lambda#54]
Hi, we're in the process of migrating from puppeteer-lambda to this framework, but cannot seem to get it to work. We followed the lambda layer instructions and uploaded the zip to the layer, then attached the layer to our lambda. When using the lib and attempting to spin up a browser we get 

```
Error: Chromium revision is not downloaded. Run \"npm install\" or \"yarn install\"\n at Launcher.launch (/opt/nodejs/node_modules/puppeteer-core/lib/Launcher.js:120:15)\n at "} 
```

Not sure what we're missing. Commands followed to create layer zip:

```
git clone --depth=1 https://github.com/alixaxel/chrome-aws-lambda.git && \
cd chrome-aws-lambda && \
make chrome_aws_lambda.zip
```

Zip is then directly uploaded to layer and layer is attached to lambda. Nothing in the lambda codebase is different other than this:

```
import * as chromium from "chrome-aws-lambda";
```

**Comment by AdamAH** [comment]
Was resolved after deflating chromium before putting into layer

**Comment by ericpinet** [comment]
Hi @AdamAH, I run in the same issues. Can you explain how you deflating chromium before putting into layer?
