### ISSUE TITLE
[REQUEST] Expose iltorb

### ISSUE THREAD

**Issue by Kikobeats** [alixaxel/chrome-aws-lambda#57]
## What would you like to have implemented?

This library is using `iltorb` for uncompressing brotli format, optimized for AWS Lambda. It could be exposed to be consumed out of the library for uncompressing brotli stuff and take the advantages

## Why would it be useful?

Something like

```
const { brotli } = require('chrome-aws-lambda')

brotli.compress
brotli.uncompress
```

**Comment by alixaxel** [comment]
@Kikobeats Wouldn't `require('chrome-aws-lambda/source/iltorb/')` do the trick for you?

**Comment by Kikobeats** [comment]
Yes, the `required` path is a bit tricky, but works 🙂
