### ISSUE TITLE
Running Mocha Tests

### ISSUE THREAD

**Issue by waqas-syed** [alixaxel/chrome-aws-lambda#58]
I am trying to run Mocha tests and provided the [environment variables](https://github.com/alixaxel/chrome-aws-lambda/wiki/HOWTO:-Local-Development) when I execute them:

`AWS_LAMBDA_FUNCTION_NAME=Lambda AWS_EXECUTION_ENV==AWS_Lambda_nodejs8.10 mocha 'Tests/**/*.js'`

But I get the following error:
```
Error: Cannot find module 'iltorb'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:580:15)
    at Function.Module._load (internal/modules/cjs/loader.js:506:25)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18) ...
```
Is there a way to run these tests?

**Comment by alixaxel** [comment]
@waqas-syed Can you retry with the extra `=` in `AWS_EXECUTION_ENV` removed?

**Comment by waqas-syed** [comment]
My bad, I fixed it and I now have new findings. I am testing on 2 environments and getting different errors, I will go by them one-by-one:

AWS Cloud9(Linux):
```
The module '/home/ec2-user/environment/deploy-api/node_modules/chrome-aws-lambda/source/iltorb/build/bindings/iltorb.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 57. This version of Node.js requires
NODE_MODULE_VERSION 64. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
Error: The module '/home/ec2-user/environment/deploy-api/node_modules/chrome-aws-lambda/source/iltorb/build/bindings/iltorb.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 57. This version of Node.js requires
NODE_MODULE_VERSION 64. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:717:18)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/home/ec2-user/environment/deploy-api/node_modules/chrome-aws-lambda/source/iltorb/index.js:10:40)
    at Module._compile (internal/modules/cjs/loader.js:688:30)...
```
Now I tried `npm rebuild chrome-aws-lambda --update-binary`, deleted and reinstalled npm dependencies, even downgraded node version from `10.16.0` to `10.14.1`, but nothing helped.

-----------------------------------------------------
Mac OS:
With node version = 10.14.1, I am getting different problem on Mac:

```
dlopen(/Users/syedwaqas/Documents/Repos/deploy-api/node_modules/chrome-aws-lambda/source/iltorb/build/bindings/iltorb.node, 1): no suitable image found.  Did find:
        /Users/syedwaqas/Documents/Repos/deploy-api/node_modules/chrome-aws-lambda/source/iltorb/build/bindings/iltorb.node: unknown file type, first eight bytes: 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x00
        /Users/syedwaqas/Documents/Repos/deploy-api/node_modules/chrome-aws-lambda/source/iltorb/build/bindings/iltorb.node: unknown file type, first eight bytes: 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x00
Error: dlopen(/Users/syedwaqas/Documents/Repos/deploy-api/node_modules/chrome-aws-lambda/source/iltorb/build/bindings/iltorb.node, 1): no suitable image found.  Did find:
        /Users/syedwaqas/Documents/Repos/deploy-api/node_modules/chrome-aws-lambda/source/iltorb/build/bindings/iltorb.node: unknown file type, first eight bytes: 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x00
        /Users/syedwaqas/Documents/Repos/deploy-api/node_modules/chrome-aws-lambda/source/iltorb/build/bindings/iltorb.node: unknown file type, first eight bytes: 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x00
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:717:18)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
```
Lastly, I am giving the name of the Lambda function as it is provided in template.yaml, like `AWS_LAMBDA_FUNCTION_NAME=VericacheGeocachingScan` but I also tried `AWS_LAMBDA_FUNCTION_NAME=VericacheGeocachingScan/index.handler` but didn't help. 

Hope this gives more insight.

**Comment by alixaxel** [comment]
@waqas-syed This is why I asked about your environment.

This package is specifically targeting `nodejs8.10` AWS Lambda environment, if you deviate from it, this kinds of errors are to be expected. The bundled `iltorb` is incompatible with your Node.js versions.

What you can try doing in this case is drop the `AWS_EXECUTION_ENV` entirely and add `iltorb`:

```shell
npm install iltorb --save-dev
```

Alternatively, you can consider downgrading your Node.js version to match AWS Lambda version (8.10).

**Comment by alixaxel** [comment]
@waqas-syed With the 1.20.0 version, this package should now work using the native Brotli module of Node 10.16.0+, so no need for bundled `iltorb` dependency on your local system (Chrome binary might still not be compatible though), for that refer to [the Local Development Wiki page](https://github.com/alixaxel/chrome-aws-lambda/wiki/HOWTO:-Local-Development).
