### ISSUE TITLE
Running on Azure Functions

### ISSUE THREAD

**Issue by NikolaiT** [alixaxel/chrome-aws-lambda#62]
Recently I wanted puppeteer deployed to the Azure functions cloud. I read the blog articles that suggest to use a containerized docker approach as demonstrated [here](https://medium.com/@bogdanbujdea/running-puppeteer-in-azure-container-instances-b24fb0a8d3e).

It seems that it is currently impossible to use puppeteer the standard way on Azure as this [issue](https://github.com/GoogleChrome/puppeteer/issues/515) suggests.

Is there anything we can do besides using  a docker approach?

I do not like the docker approach, because downloading more than 300MB chromium binaries each time my Azure Function runs is simply not economical.

**Comment by alixaxel** [comment]
@NikolaiT I'm confident it would be possible to run puppeteer on Azure Functions, however due to Azure/Microsoft not letting me change the country associated with my account and, at the same time, also not accepting a credit card from the county I'm based, I'm effectively unable to get a working Azure account and therefore can't test or do any sort of development for it.

If you're willing to sponsor an Azure test account, I'd be more than happy to give it a go. 😉

Otherwise, we should close this issue and blame Microsoft for it and their terrible user flows.

**Comment by alixaxel** [comment]
@NikolaiT I managed to get myself a new Azure account.

I managed to extract Chromium and some necessary dependencies.
Besides the ones included on the [`AWS_Lambda_nodejs10.x` shim](https://github.com/alixaxel/chrome-aws-lambda/blob/master/bin/aws.tar.br), Azure also [requires](https://github.com/alixaxel/chrome-aws-lambda/files/3746915/azure_libs.zip):

- `libplds4.so`
- `libnspr4.so`
- `libplc4.so`

I'd be willing to include these as an additional shim for Azure functions, but it doesn't seem to be enough:

> Failed to launch chrome! /tmp/chromium: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.25' not found (required by /tmp/aws/lib/libexpat.so.1) /tmp/chromium: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.25' not found (required by /tmp/aws/lib/libuuid.so.1)

![image](https://user-images.githubusercontent.com/262782/67148388-03d84780-f297-11e9-825e-8f696b5f2408.png)

After also including `libc.so.6` the error is lacking any meaningful details:

> Failed to launch chrome! TROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md 

Even if it was possible to overcome this (pretty sure it is), it doesn't seem to be worth it:

![image](https://user-images.githubusercontent.com/262782/67148524-48181780-f298-11e9-966e-d6280da713e6.png)

It takes 10+ seconds to inflate Chromium with 2GB, something that's 10x faster on AWS Lambda.

So in light of all of this, I don't think Azure is something that I want to support, sorry. :confused:

**Comment by jeffhollan** [comment]
Thanks for this @alixaxel - I’m a PM on the Azure Functions team and came across this library yesterday.  We’ve got a few major perf improvements that are lined up, as well as defaulting to Linux infra (not sure if you manually selected linux infra) for node apps.  I’m happy to help look into this.  Do you have an easy way to repro what you were testing with Azure Functions?  I can start with just creating an app and including the package, and then including the 4 files you mentioned in last comment?  Let me know - happy to chat more and see if anything we can do to help here.

**Comment by ile** [comment]
Hoping for this!

**Comment by alixaxel** [comment]
@jeffhollan Sorry seems like I missed your message.

Seems like Azure finally fixed the country / credit card bug so I was able to get my account activated. The whole Azure Functions experience is still kinda shitty however, starting with this `Create undefined`:

![image](https://user-images.githubusercontent.com/262782/72007849-821b0900-324a-11ea-8bdd-c33d117285a5.png)

I had a bunch of problems deploying the function (manually or via VSCode), but finally managed...

![image](https://user-images.githubusercontent.com/262782/72008584-0f129200-324c-11ea-9f6d-61a301c12e6b.png)

As you can see, it's seems that I'm running on Linux (although I get Windows paths in the VM?):

![image](https://user-images.githubusercontent.com/262782/72013750-674e9180-3256-11ea-84e1-f333e96e9beb.png)

I had to manually patch this package and add the extra libs I mentioned before.

Chromium gets extracted and stops complaining about missing shared libs, until missing `libc`:

```
Failed to launch chrome!
/tmp/chromium: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.25' not found (required by /tmp/aws/lib/libexpat.so.1)


TROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md
```

The whole experience is very frustrating for me to pursue it further, but I'll leave you with the whole workspace if you want to test it on your end: https://fil.email/G5HH69GM (link expires in 7 days).

PS: I tried everything I read to pin the environment to Node 10, but I only got Node 8.

**Comment by thiagomeireless** [comment]
Any news on this? Sadly our company is migrating from AWS to Azure due to costs and we need to migrate our Lambda functions which uses this package.
