### ISSUE TITLE
[REQUEST] Add or document use-case with webdriver.io

### ISSUE THREAD

**Issue by Drewster727** [alixaxel/chrome-aws-lambda#65]
## What would you like to have implemented?
I've been working with webdriver.io (https://webdriver.io/) -- a popular node.js test framework. Has anyone gotten this to play nice with it? I'm heavily looking at exploring lambda to run tests in different regions, and would love to get this working.

## Why would it be useful?
Allow us to easily embed chrome inside a lambda and allow a popular test framework to utilize it.

**Comment by alixaxel** [comment]
@Drewster727 Unfortunately I have zero experience with WebDriver.

Could you can provide a ZIP file with a minimal setup for WebDriver? That way I could try to expand on it.

**Comment by Drewster727** [comment]
@alixaxel  sorry for such a late reply. I made a public repo with a test project. I cannot quite get it to work in lambda, but works fine locally:
https://github.com/Drewster727/wdio-lambda
