### ISSUE TITLE
[REQUEST] Using with puppeteer-extra

### ISSUE THREAD

**Issue by daveroberts** [alixaxel/chrome-aws-lambda#75]
## What would you like to have implemented?
I'd like to be able to use chrome-aws-lambda with the plugins from [berstend/puppeteer-extra](https://github.com/berstend/puppeteer-extra), but it seems this is not possible as chrome-aws-lambda forces you to use the built in puppeteer

**Comment by alixaxel** [comment]
@daveroberts This package doesn't ship with puppeteer built-in, so you should be able to use `puppeteer-extra`. The only problem I see is that `puppeteer-extra` depends on `puppeteer` (and not `puppeteer-core` so you might have to do some pruning to remove the default Chromium binary.

**Comment by daveroberts** [comment]
Thanks for the reply @alixaxel .  The code sample in the README looks like puppeteer is built in.  Do you know how I can "bring my own" puppeteer?

**Comment by alixaxel** [comment]
@daveroberts Oh, it's not. The `chromium.puppeteer` bit is simply requiring `puppeteer[-core]` (that you bring) and overloading some of the APIs (similar to `puppeteer-extra` I guess). Here's an example:

```js
const chromium = require('chrome-aws-lambda');
const puppeteer = require('puppeteer-core');

exports.handler = async (event, context) => {
  let result = null;
  let browser = null;

  try {
    browser = await puppeteer.launch({
      args: chromium.args,
      defaultViewport: chromium.defaultViewport,
      executablePath: await chromium.executablePath,
      headless: chromium.headless,
    });
  } catch (error) {
    return context.fail(error);
  } finally {
    if (browser !== null) {
      await browser.close();
    }
  }

  return context.succeed(result);
};
```

**Comment by daveroberts** [comment]
I'm still a bit confused.  In the example you posted, `chromium.puppeteer` isn't being called.  Does this mean that the APIs are no longer overloaded the way they would be if `chromium.puppeteer` was being called?

How can I control which Chromium binary will be packaged and used for AWS Lambda, in order to stay under the size limit?

**Comment by alixaxel** [comment]
@daveroberts 

> Does this mean that the APIs are no longer overloaded the way they would be if chromium.puppeteer was being called?

Yes, that's [exactly what it means](https://github.com/alixaxel/chrome-aws-lambda#overloading). The `executablePath` will inflate and return you the path to the binary, besides that you probably want to rely on `args` as well, as there are some critical ones that must be enumerated.

**Comment by NikolaiT** [comment]
> I'm still a bit confused. In the example you posted, `chromium.puppeteer` isn't being called. Does this mean that the APIs are no longer overloaded the way they would be if `chromium.puppeteer` was being called?
> 
> How can I control which Chromium binary will be packaged and used for AWS Lambda, in order to stay under the size limit?
> 
> Edit: Is it as simple as `executablePath: await chromium.executablePath`? If so, can I mix and match where executablePath is the ONLY part I take from chrome-aws-lambda, or are some other args required in order to make it work? Thank you for creating this and taking the time to patiently explain it to me

It doesn't matter that `chromium.puppeteer` is not being called. That becomes apparent when we see what `chromium.puppeteer` actually is:

```javascript
  /**
   * Overloads puppeteer with useful methods and returns the resolved package.
   */
  static get puppeteer() {
    for (let overload of ['FrameManager', 'Page']) {
      require(`${__dirname}/puppeteer/lib/${overload}`);
    }

    try {
      return require('puppeteer');
    } catch (error) {
      if (error.code !== 'MODULE_NOT_FOUND') {
        throw error;
      }

      return require('puppeteer-core');
    }
  }
```

**Comment by ioannist** [comment]
If you are using webpack to upload your code to lambda, you should also check this post
https://github.com/berstend/puppeteer-extra/issues/93

Also, don't we need to remove --disable-notifications from the puppeteer args in order to load Stealth?

**Comment by berstend** [comment]
Just wanted to chime in and mention that the latest versions of `puppeteer-extra` provide an `addExtra` method, to make patching non-standard puppeteer-compatible libs easier:

```js
const chromium = require('chrome-aws-lambda')
const { addExtra } = require('puppeteer-extra')
const puppeteerExtra = addExtra(chromium.puppeteer)

const launch = async () => {
  puppeteerExtra
    .launch({
      args: chromium.args,
      defaultViewport: chromium.defaultViewport,
      executablePath: await chromium.executablePath,
      headless: chromium.headless
    })
    .then(async browser => {
      const page = await browser.newPage()
      await page.goto('https://www.spacejam.com/archive/spacejam/movie/jam.htm')
      await page.waitFor(10 * 1000)
      await browser.close()
    })
}

launch() // Launch Browser
```

The webpack story is still not perfect as `puppeteer-extra` currently uses dynamic requires but there are several workarounds being mentioned in https://github.com/berstend/puppeteer-extra/issues/93 :)

**Comment by daveroberts** [comment]
This code works locally, but throws an error in AWS lambda:

```
{
    "errorType": "Error",
    "errorMessage": "Failed to launch chrome!\n\n\nTROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md\n",
    "stack": [
        "Error: Failed to launch chrome!",
        "",
        "",
        "TROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md",
        "",
        "    at onClose (/var/task/node_modules/puppeteer-core/lib/Launcher.js:348:14)",
        "    at Interface.<anonymous> (/var/task/node_modules/puppeteer-core/lib/Launcher.js:337:50)",
        "    at Interface.emit (events.js:215:7)",
        "    at Interface.EventEmitter.emit (domain.js:476:20)",
        "    at Interface.close (readline.js:403:8)",
        "    at Socket.onend (readline.js:180:10)",
        "    at Socket.emit (events.js:215:7)",
        "    at Socket.EventEmitter.emit (domain.js:476:20)",
        "    at endReadableNT (_stream_readable.js:1183:12)",
        "    at processTicksAndRejections (internal/process/task_queues.js:80:21)"
    ]
}
```

**Comment by alixaxel** [comment]
@daveroberts What code are you referring to?

**Comment by daveroberts** [comment]
The code in the comment directly above

**Comment by lu3do** [comment]
> @daveroberts What code are you referring to?



> This code works locally, but throws an error in AWS lambda:
> 
> ```
> {
>     "errorType": "Error",
>     "errorMessage": "Failed to launch chrome!\n\n\nTROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md\n",
>     "stack": [
>         "Error: Failed to launch chrome!",
>         "",
>         "",
>         "TROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md",
>         "",
>         "    at onClose (/var/task/node_modules/puppeteer-core/lib/Launcher.js:348:14)",
>         "    at Interface.<anonymous> (/var/task/node_modules/puppeteer-core/lib/Launcher.js:337:50)",
>         "    at Interface.emit (events.js:215:7)",
>         "    at Interface.EventEmitter.emit (domain.js:476:20)",
>         "    at Interface.close (readline.js:403:8)",
>         "    at Socket.onend (readline.js:180:10)",
>         "    at Socket.emit (events.js:215:7)",
>         "    at Socket.EventEmitter.emit (domain.js:476:20)",
>         "    at endReadableNT (_stream_readable.js:1183:12)",
>         "    at processTicksAndRejections (internal/process/task_queues.js:80:21)"
>     ]
> }
> ```

You need to change the memory settings on your lambda function, it fails because it runs out of memory. Also change the timeout to something like 30 seconds to make sure it doesn't time out.

**Comment by daveroberts** [comment]
> You need to change the memory settings on your lambda function, it fails because it runs out of memory. Also change the timeout to something like 30 seconds to make sure it doesn't time out.

Memory is set to 1664MB and timeout is set to 15 minutes

**Comment by StevenVeshkini** [comment]
I would like to reopen this issue if possible, as I am having the same issue (not able to run with 
puppeteer-extra).  I tried the solution in https://github.com/alixaxel/chrome-aws-lambda/issues/75#issuecomment-562868578, but kept getting a `Protocol error (Runtime.callFunctionOn): Target closed.` error. I then commented out my `// const puppeteer = require("puppeteer-extra");` and the stealth plugin, and changed `puppeteer.launch` to `chromium.puppeteer.launch` and it worked.

However, this is less than ideal, as I want to use the stealth plugin. Does anyone have any advice?

**Comment by shiqwang** [comment]
@daveroberts hey, i also had those problems, did you solve it ?

**Comment by daveroberts** [comment]
@shiqwang no

**Comment by biznickman** [comment]
I got a similar error to @daveroberts : 

```
{
  "errorType":"Runtime.UnhandledPromiseRejection",
  "errorMessage":"Error: Protocol error (Emulation.setDeviceMetricsOverride): Session closed. Most likely the page has been closed.",
  "reason":{
    "errorType":"Error",
    "errorMessage":"Protocol error (Emulation.setDeviceMetricsOverride): Session closed. Most likely the page has been closed.",
    "stack": [
      "Error: Protocol error (Emulation.setDeviceMetricsOverride): Session closed. Most likely the page has been closed.",
      "    at CDPSession.send (/var/task/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Connection.js:195:35)",
      "    at EmulationManager.emulateViewport (/var/task/node_modules/puppeteer-core/lib/cjs/puppeteer/common/EmulationManager.js:20:26)",
      "    at Page.setViewport (/var/task/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Page.js:973:58)",
      "    at Function.create (/var/task/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Page.js:170:24)",
      "    at processTicksAndRejections (internal/process/task_queues.js:97:5)"
    ]
  },
  "promise":{},
  "stack":[
    "Runtime.UnhandledPromiseRejection: Error: Protocol error (Emulation.setDeviceMetricsOverride): Session closed. Most likely the page has been closed.",
    "    at process.<anonymous> (/var/runtime/index.js:35:15)",
    "    at process.emit (events.js:314:20)",
    "    at processPromiseRejections (internal/process/promises.js:209:33)",
    "    at processTicksAndRejections (internal/process/task_queues.js:98:32)"
  ]
}
```

@daveroberts did you ever resolve this?

**Comment by daveroberts** [comment]
I gave this another try recently and got it to work.  I don't know if it was simply the passage of time, but here's what I did differently:
The puppeteer-extra-plugin-stealth README tells you to first install the dependencies with: 
`npm install puppeteer puppeteer-extra puppeteer-extra-plugin-stealth`
When I did this, it would install node_modules/puppeteer and zipping this up would always give an error in Lambda.  Instead, I added puppeteer-extra and puppeteer-extra-plugin-stealth to my package.json file.  If you `npm install`, your node_modules directory will include a puppeteer directory.  If I zipped this up and sent it to lambda, I got the error described above.  If I cleared the node_modules directory then `npm install --production`, the node_modules/puppeteer directory was never created, and the zipped up directory would work on lambda as expected

**Comment by renschler** [comment]
@daveroberts i got it to run in a lambda function, i tried you instructions but it failed, what I ended up doing was adding `node_modules/puppeteer/*` to a zip exclude file, so that it wouldnt be uploaded to AWS.

However... when I inspect the runtime logs, I don't think the StealthPlugin is actually working. My user agent is always the same (and it says Headless). Did you run into a similar issue?

**Comment by bestplay9384** [comment]
@renschler are you checking it on "second" tab or the default one? puppeter-extra inject its stealth plugins on all BUT default chrome tab.

**Comment by daveroberts** [comment]
> Did you run into a similar issue?

@renschler   No.  Even while using the Stealth plugin I manually set my user agent with page.setUserAgent, and it seems to be respecting what I set

**Comment by renschler** [comment]
thanks @bestplay9384 @daveroberts 

I was using `browser.userAgent()` but now I realize that's incorrect. You are right the stealth plugin user agent is working 

unfortunately still getting blocked by cloudflare though, might have to try using a proxy

**Comment by renschler** [comment]
@daveroberts @bestplay9384 
hmm actually i'm not sure it's working
```
const chromium = require("chrome-aws-lambda");
const { addExtra } = require("puppeteer-extra");
const StealthPlugin = require("puppeteer-extra-plugin-stealth");
const { v4: uuidv4 } = require("uuid");

const puppeteerExtra = addExtra(chromium.puppeteer);
puppeteerExtra.use(StealthPlugin());

let chromePath = await chromium.executablePath;
let args = chromium.args.filter((x) => x !== "--disable-notifications");
let tmpDir = `/tmp/puppeteer-${uuidv4()}`;
let windowX = String(Math.floor(Math.random() * 400 + 800));
let windowY = String(Math.floor(Math.random() * 400 + 600));

let browser = await puppeteerExtra.launch({
      args: args, //chromium.args,
      defaultViewport: {
        width: Number(windowX),
        height: Number(windowY),
      },
      executablePath: chromePath,
      headless: chromium.headless,
      ignoreHTTPSErrors: true,
      userDataDir: tmpDir,
    });

let page = await browser.newPage();
let currentUA = await page.evaluate(() => {
      return navigator.userAgent;
    });
console.log(currentUA);
```

When I run the above code, I'm always getting
`Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4469.0 Safari/537.36`

My understanding was that this user agent should be randomized? Am I missing something obvious? Thank you so much for the help.

**Comment by daveroberts** [comment]
@renschler Like I said, I'm setting the user agent explicitly, so I can't speak to the behavior when it's not being set.  It looks like puppeteer-stealth has an evasion to set the userAgent.  The [README ](https://github.com/berstend/puppeteer-extra/blob/master/packages/puppeteer-extra-plugin-stealth/evasions/user-agent-override/readme.md) for that evasion and its [code which sets the user agent](https://github.com/berstend/puppeteer-extra/blob/880c9ab3882346782e678520edc55cbe2ff48d4c/packages/puppeteer-extra-plugin-stealth/evasions/user-agent-override/index.js).

From the README:

> If you don't provide any values this plugin will default to using the regular UserAgent string (while stripping the headless part).

That doesn't imply a random user agent to me.  Looking at the code, I don't see any mention of randomization.  I don't see any other code which sets the user agent in stealth.  I'm not an expert in the stealth plugin, you'll probably have more luck asking how puppeteer-stealth works on the puppeteer-stealth page

**Comment by hodovani** [comment]
> thanks @bestplay9384 @daveroberts
> 
> I was using `browser.userAgent()` but now I realize that's incorrect. You are right the stealth plugin user agent is working
> 
> unfortunately still getting blocked by cloudflare though, might have to try using a proxy

@renschler, could you please share if you found the solution with the proxy?

**Comment by fabioselau077** [comment]
> > I'm still a bit confused. In the example you posted, `chromium.puppeteer` isn't being called. Does this mean that the APIs are no longer overloaded the way they would be if `chromium.puppeteer` was being called?
> > How can I control which Chromium binary will be packaged and used for AWS Lambda, in order to stay under the size limit?
> > Edit: Is it as simple as `executablePath: await chromium.executablePath`? If so, can I mix and match where executablePath is the ONLY part I take from chrome-aws-lambda, or are some other args required in order to make it work? Thank you for creating this and taking the time to patiently explain it to me
> 
> It doesn't matter that `chromium.puppeteer` is not being called. That becomes apparent when we see what `chromium.puppeteer` [actually is](https://github.com/alixaxel/chrome-aws-lambda/blob/master/source/index.js):
> 
> ```js
>   /**
>    * Overloads puppeteer with useful methods and returns the resolved package.
>    */
>   static get puppeteer() {
>     for (let overload of ['FrameManager', 'Page']) {
>       require(`${__dirname}/puppeteer/lib/${overload}`);
>     }
> 
>     try {
>       return require('puppeteer');
>     } catch (error) {
>       if (error.code !== 'MODULE_NOT_FOUND') {
>         throw error;
>       }
> 
>       return require('puppeteer-core');
>     }
>   }
> ```
> 
> Therefore, a full example that combines **chrome-aws-lambda** and **puppeteer-extra** could be the following:
> 
> ```js
> const chromium = require('chrome-aws-lambda');
> // puppeteer-extra is a drop-in replacement for puppeteer,
> // it augments the installed puppeteer with plugin functionality.
> // Any number of plugins can be added through `puppeteer.use()`
> const puppeteer = require('puppeteer-extra');
> 
> // Add stealth plugin and use defaults (all tricks to hide puppeteer usage)
> const StealthPlugin = require('puppeteer-extra-plugin-stealth');
> puppeteer.use(StealthPlugin());
> 
> async function handler(event, context) {
>   let result = null;
>   let browser = null;
> 
>   try {
> 
>     let args = chromium.args;
>     let viewport = chromium.defaultViewport;
>     let exec_path = await chromium.executablePath;
>     let headless = chromium.headless;
> 
>     // we are running locally
>     if (process.env.AWS_EXECUTION_ENV === undefined) {
>       exec_path = process.env.LOCAL_CHROMIUM;
>     }
> 
>     browser = await puppeteer.launch({
>       args: args,
>       defaultViewport: viewport,
>       executablePath: exec_path,
>       headless: headless,
>     });
> 
>     const page = await browser.newPage();
>     await page.setViewport({ width: 800, height: 600 });
> 
>     console.log(`Testing the stealth plugin..`);
>     await page.goto('https://bot.sannysoft.com');
>     await page.waitFor(5000);
>     await page.screenshot({ path: 'stealth.png', fullPage: true });
> 
>     console.log(`All done, check the screenshots. ✨`);
> 
>   } catch (error) {
>     console.error(error);
>   } finally {
>     if (browser !== null) {
>       await browser.close();
>     }
>   }
> }
> 
> module.exports = handler;
> 
> (async () => {
>   await handler({}, {});
> })();
> ```

Error: Build failed with 1 error:
node_modules/@puppeteer/browsers/lib/cjs/CLI.js:49:40: ERROR: Do not know how to load path: node_modules/@puppeteer/browsers/node_modules/yargs/yargs

**Comment by shahnawaz2057** [comment]
@fabioselau077, did you manage to find the solution. I also get this error. can someone help please. Using puppeteer-extra with typescript.

Build failed with 2 errors:

Do not know how to load path: node_modules/@puppeteer/browsers/node_modules/yargs/yargs
    node_modules/@puppeteer/browsers/lib/cjs/CLI.js:49:40:
      49 │ const yargs_1 = __importDefault(require("yargs/yargs"));

Do not know how to load path: node_modules/puppeteer-core/node_modules/yargs/yargs
    node_modules/puppeteer-core/node_modules/@puppeteer/browsers/lib/cjs/CLI.js:61:40:
      61 │ const yargs_1 = __importDefault(require("yargs/yargs"));
