### ISSUE TITLE
[REQUEST] Use Docker for compiling

### ISSUE THREAD

**Issue by richarddd** [alixaxel/chrome-aws-lambda#77]
## What would you like to have implemented?
Compile the required binaries using Docker

## Why would it be useful?
* Compile locally
* Easy update to newer AWS runtimes
* No need to launch an ec2 instance
* Easier maintenance
* More cost effective?

**Comment by alixaxel** [comment]
@richarddd Compiling Chromium on Docker is possible but it requires a very powerful host.

If you check the [system requirements](https://chromium.googlesource.com/chromium/src/+/master/docs/linux_build_instructions.md#System-requirements) you'll see that the recommended **minimum** is:

- 16GB+ of RAM
- 100GB of free disk space

Not to mention CPU power. I usually rely on `c5d.4xlarge` (16 vCPUs, 32GB RAM) or `c5d.9xlarge` (36 vCPUs, 76GB RAM) instances to compile Chromium, and even with all that raw performance it still takes over one hour to finish - granted about half of it is just for cloning the huge repo, but still...

Using Docker is a neat idea but I don't think it's a very practical one. :sweat_smile:

I'll gladly accept a PR if you're keen on submitting one though.

**Comment by richarddd** [comment]
> @richarddd Compiling Chromium on Docker is possible but it requires a very powerful host.
> 
> If you check the [system requirements](https://chromium.googlesource.com/chromium/src/+/master/docs/linux_build_instructions.md#System-requirements) you'll see that the recommended **minimum** is:
> 
> * 16GB+ of RAM
> * 100GB of free disk space
> 
> Not to mention CPU power. I usually rely on `c5d.4xlarge` (16 vCPUs, 32GB RAM) or `c5d.9xlarge` (36 vCPUs, 76GB RAM) instances to compile Chromium, and even with all that raw performance it still takes over one hour to finish - granted about half of it is just for cloning the huge repo, but still...
> 
> Using Docker is a neat idea but I don't think it's a very practical one. 😅
> 
> I'll gladly accept a PR if you're keen on submitting one though.

Holy ****. I had no idea it required such a machine to compile! Seems like a bad idea to do it in Docker  👍
