### ISSUE TITLE
[BUG] No such file or directory (...../../bin/chromium.br)

### ISSUE THREAD

**Issue by abdulg** [alixaxel/chrome-aws-lambda#80]
## Environment
* `chrome-aws-lambda` Version: 2.0.1
* `puppeteer` / `puppeteer-core` Version: 2.0.0/2.0.0
* OS: Built on Fedora 29, NodeJS 10.17.0, Serverless 1.58.0, serveless-webpack 5.3.1
* Node.js Version: 10.x
* Lambda / GCF Runtime: Lambda

## Expected Behavior
Chromium should have been launched

## Current Behavior
Inflating chromium raised an error:
```
2019-11-25T21:11:33.586Z	233af41f-a717-499e-818f-08acb732ee55	INFO	{ [Error: ENOENT: no such file or directory, open 'node_modules/chrome-aws-lambda/source/../bin/chromium.br']
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: 'node_modules/chrome-aws-lambda/source/../bin/chromium.br' }
```

## Possible Solution
Use `let input = join(__dirname, '..', 'bin');` [here](https://github.com/alixaxel/chrome-aws-lambda/blob/master/source/index.js#L161)

## Steps to Reproduce
Create a `webpack` + `serverless` package that does not use layers, ie. the compressed files are included in the package at `node_modules/chrome-aws-lambda/bin`

**Comment by alixaxel** [comment]
This is not a bug, your webpack setup is likely stripping away the `chromium.br`.

Just make sure you whitelist these files.

**Comment by abdulg** [comment]
Those files are present in the package. Also confirmed they're at the correct location on Lambda. PR fixes the problem.

**Comment by alixaxel** [comment]
@abdulg That's oddly weird because `join(__dirname, '..', 'bin')` and `${__dirname}/../bin` should yield exactly the same string. Can you explain why you think your PR solves your problem?

**Comment by abdulg** [comment]
I don't really know. I did not dig much into it. I assume `join` is doing additional validation. I do know that if I hard coded the path then `node_modules/chrome-aws-lambda/source/../bin` failed and `node_modules/chrome-aws-lambda/bin` worked, so some handling of `..`. I left it once `join` worked as that seems more platform agnostic solution anyway.

**Comment by abdulg** [comment]
@alixaxel The two methods do not yield the same string:
```
> str1 = 'this/is/a/path/../to/something'
'this/is/a/path/../to/something'
> str2 = path.join('this', 'is', 'a', 'path', '..', 'to', 'something')
'this/is/a/to/something'
```

**Comment by campidelli** [comment]
Hi there, I am facing the same issue here. Do you plan to release this PR soon? Thanks.

**Comment by campidelli** [comment]
Hi there, just in case this problem happens to anyone else, I worked around it by configuring my `webpack.config.js` as follows:
```
var CopyWebpackPlugin = require('copy-webpack-plugin');

module.exports = {
  entry: './handler.js',
  target: 'node',
  module: {
    loaders: [{
      test: /\.js$/,
      loaders: ['babel-loader'],
      include: __dirname,
      exclude: /node_modules/,
    }]
  },
  output: {
    libraryTarget: 'commonjs',
    path: __dirname + '/.webpack',
    filename: 'handler.js'
  },
  externals: {
    'chrome-aws-lambda': 'chrome-aws-lambda',
    'lambdafs': 'lambdafs',
  },
  plugins: [
    new CopyWebpackPlugin([
      { from: 'node_modules/chrome-aws-lambda', to: 'node_modules/chrome-aws-lambda' },
      { from: 'node_modules/lambdafs', to: 'node_modules/lambdafs' },
    ])
  ]
};
```

**Comment by abdulg** [comment]
@campidelli Thanks for this. To satisfy my curiosity, why does this work?

**Comment by abdulg** [comment]
This worked for me as well, although I did not list the packages in `externals`.

**Comment by campidelli** [comment]
> @campidelli Thanks for this. To satisfy my curiosity, why does this work?

Because the plugin looks for `chromium.br` in a relative path that follows the `node_modules` structure. It would be nice to have a property to specify the path to `chromium.br` instead of using a hardcoded one. But in any case it works. BTW, I am not a JS developer, but a Java one. I had to upgrade the NodeJs version of a lambda from ours because Node8 is getting deprecated on AWS, maybe this is not the most elegant solution.

**Comment by mattiasnixell** [comment]
Hi, I bumped into this issue as well. @campidelli, your solution works best if there's only 1 entry in the Webpack config. However, if one wants to bundle multiple functions (e.g. serverless' `slsw.lib.entries` using "package individually"), the binary files will be copied to every function's bundle. If one only need chromium in 1 function, this behavior will occupy unnecessary storage from their AWS lambda shared code storage.

I propose to use Webpack's `file-loader` instead so that one gains more control of which function bundles should include chromium. I'm using the following Webpack config currently:
```javascript
const slsw = require('serverless-webpack');

module.exports = {
  entry: slsw.lib.entries,
  module: {
    rules: [
      {
        test: /\.ts$/,
        use: [{ loader: 'ts-loader', options: { transpileOnly: true } }],
      },
      /**
       * Use file loader to move chromium .br files into /bin
       * @link https://github.com/alixaxel/chrome-aws-lambda/issues/80
       */
      {
        test: /\.br$/,
        use: [{ loader: 'file-loader', options: { name: '/bin/[name].[ext]' } }],
      },
    ],
  },
  resolve: {
    extensions: ['.ts', '.js'],
  },
  stats: {
    /* @link https://www.npmjs.com/package/ts-loader#transpileonly-boolean-defaultfalse */
    warningsFilter: /export .* was not found in/,
  },
  target: 'node',
};
```
...and then add these imports to the top of the handler file where you need chromium:
```javascript
import 'chrome-aws-lambda/bin/aws.tar.br';
import 'chrome-aws-lambda/bin/chromium.br';
import 'chrome-aws-lambda/bin/swiftshader.tar.br';
```
I hope someone finds this useful, and thanks @campidelli for your solution and pointers :)

**Comment by AntoniaMendoza** [comment]
@mattiasnixell Could you show your dependencies and how you are importing modules and launching puppeteer on your handler file?
I tried using your solution with the only difference being that I use awsSamPlugin as entry (and some other minor configs), and it is not working.
Thanks!

**Comment by imhashir** [comment]
@campidelli @mattiasnixell 

Both of you guys are awesome. I was stuck in this for more 12 hours. I don't know why but @mattiasnixell 's exact solution wasn't working for me. I took a closer look at @campidelli 's answer as well and tried to understand what's actually happening.  My function was not able to find the chrome binary. So I just changed the file-loader rule a bit and it worked.

Here's the updated rules block from @mattiasnixell 's answer:

```
  module: {
    rules: [
      {
        test: /\.ts$/,
        use: [{ loader: 'ts-loader', options: { transpileOnly: true } }],
      },
      /**
       * Use file loader to move chromium .br files into /bin
       * @link https://github.com/alixaxel/chrome-aws-lambda/issues/80
       */
      {
        test: /\.br$/,
        use: [{ loader: 'file-loader', options: { name: '[path][name].[ext]' } }],
      },
    ],
  }
```

**Comment by danfoust** [comment]
@imhashir, @mattiasnixell 

This solution throws an error locally for me on the **aws.tar.br** file:

```
[
  'C:\\Users\\dev_machine\\client\\project\\node_modules\\chrome-aws-lambda\\bin\\aws.tar.br:1',
  '��MA�A|���]!iC��B�kf\u001c��T@જ�h�\u0001E��r�&�:⛻�\u0014���~�F��G����\u0013����/�\u0014c;\u0016!.\u000eTP %i�u�f��~5�\b`ߝ~%<������He��\t\u0013S�D#�f���FQė�������������������������⌂���m�⌂�s���9�ީ\f��\u0014fh"��\u0014�b��',
  '',
  '',
  'SyntaxError: Invalid or unexpected token',
  'at wrapSafe (internal/modules/cjs/loader.js:1053:16)',
  'at Module._compile (internal/modules/cjs/loader.js:1101:27)',
  'at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)',
  'at Module.load (internal/modules/cjs/loader.js:985:32)',
  'at Function.Module._load (internal/modules/cjs/loader.js:878:14)',
  'at Module.require (internal/modules/cjs/loader.js:1025:19)',
  'at require (internal/modules/cjs/helpers.js:72:18)',
  'at Object.chrome-aws-lambda/bin/aws.tar.br (C:\\Users\\dev_machine\\client\\project\\.webpack\\service\\webpack:\\external "chrome-aws-lambda\\bin\\aws.tar.br":1:1)',
  'at __webpack_require__ (C:\\Users\\dev_machine\\client\\project\\.webpack\\service\\webpack:\\webpack\\bootstrap:19:1)'   
]
```

**Comment by devpms** [comment]
Was getting the same error, it got resolved by copywebpack plugins.

need to add below code in webpack.config.js. Make sure you follow new syntax which includes patterns key.

```plugins: [
    new CopyWebpackPlugin({
      patterns: [
      { from: 'node_modules/chrome-aws-lambda', to: 'node_modules/chrome-aws-lambda' },
      { from: 'node_modules/lambdafs', to: 'node_modules/lambdafs' },
    ]})
  ]```

**Comment by devpms** [comment]
with webpack 5.24.4  we will get an error  `compilation.getCache is not a function`

to resolve that we need to use copy-webpack-plugin to ^6.3.2. Which will solve that error.
