### ISSUE TITLE
[REQUEST] Compatibility issue when invoking Serverless locally

### ISSUE THREAD

**Issue by adriangmweb** [alixaxel/chrome-aws-lambda#83]
When using the Serverless framework to create and manage the AWS Lambda functions there is a command to test individual functions: 

`serverless invoke local --function functionName`

This command simulates a lambda function, and it includes the environment variable `AWS_LAMBDA_FUNCTION_NAME` when invoked. This causes an error due to chromium headless property set to true.

## Environment
* `chrome-aws-lambda` Version: 2.0.1
* `puppeteer` / `puppeteer-core` Version: 2.0.0
* OS: Linux & MacOs
* Node.js Version: 12.x
* Lambda / GCF Runtime: nodejs

**Comment by alixaxel** [comment]
@adriangmweb Apologies for taking so long - this check is now released on version 2.0.2. Thanks!
