### ISSUE TITLE
Question: has anyone used chrome-aws-lambda with chrome-remote-interface instead of puppeteer?

### ISSUE THREAD

**Issue by renschler** [alixaxel/chrome-aws-lambda#86]
I'm trying to port my project from [serverless-chrome]( https://github.com/adieuadieu/serverless-chrome/tree/master/packages/lambda) to chrome-aws-lambda because serverless-chrome no longer works with node 10 + Amazon Linux 2 (see issue: https://github.com/adieuadieu/serverless-chrome/issues/203).

Anyways, my project uses chrome-remote-interface and not puppeteer and it would be awesome I didn't have to port things to puppeteer and I could just reuse my chrome-remote-interface code.

Has anyone done this? I'm sure it's doable but just not sure how I should go about it.

**Comment by extraordinaire** [comment]
@renschler see [about running locally](https://github.com/alixaxel/chrome-aws-lambda/wiki/HOWTO:-Local-Development), otherwise `chromium.executablePath` will return `null` and there's no `.then` on `null` :)

Something like this should work:

```
const Chrome = require('chrome-remote-interface')
const chromium = require('chrome-aws-lambda')
const { spawn } = require('child_process')

const options = chromium.args.concat(['--remote-debugging-port=9222'])

chromium.executablePath.then(path => {
  chrome = spawn(path, options)
  chrome.stdout.on('data', data => console.log(data.toString()))
  chrome.stderr.on('data', data => console.log(data.toString()))

  Chrome().then(client => {
    const {Emulation, Network, Page, Runtime, DOM, Console} = client
  })
})
```

**Comment by renschler** [comment]
thank you! I'll try it out

**Comment by alixaxel** [comment]
Yes, exactly @extraordinaire that should do it - thanks for stepping in! :smiley: :+1:
