### ISSUE TITLE
[REQUEST] Creating more than one 'browser' in AWS lambda fails

### ISSUE THREAD

**Issue by macadev** [alixaxel/chrome-aws-lambda#88]
Thanks for this great project. Really awesome stuff.

Today I started using it to scrape some pages. I noticed that when I attempted to create two browser instances execution would fail:

```
const browserA = await chromium.puppeteer.launch({
    args: chromium.args,
    defaultViewport: chromium.defaultViewport,
    executablePath: await chromium.executablePath,
    headless: chromium.headless,
  });

const browserB = await chromium.puppeteer.launch({
    args: chromium.args,
    defaultViewport: chromium.defaultViewport,
    executablePath: await chromium.executablePath,
    headless: chromium.headless,
  });
```

The error I saw in the CloudWatch logs cryptically stated **"Error: spawn ETXTBSY"** - This has something to do with shared resources between different processes. I think this limitation is worth highlighting in the docs (maybe it's already there and I didn't find it).

Concrete request: Update documentation to reflect that you can only instantiate one browser object inside a Lambda function.

**Comment by sdk0794** [comment]
Not sure if you need two browsers only. But if possible you can use two tabs if it works for you.

```
const browserA = await chromium.puppeteer.launch({
    args: chromium.args,
    defaultViewport: chromium.defaultViewport,
    executablePath: await chromium.executablePath,
    headless: chromium.headless,
  });

let page1 = await browser.newPage();

let newPage = await newPagePromise;

let page2 = await newPage.page();
```

I have used this on

"chrome-aws-lambda": "^1.19.0"
"puppeteer-core": "^1.19.0"
AWS runtime: 8.10

**Comment by alixaxel** [comment]
@macadev I don't know why you'd need two instances under Lambda, but your example definitely won't work (as `chromium.executablePath` will inflate the binary a second time while the first is already in use).

You could try this:

```js
const binary = await chromium.executablePath;

const browserA = await chromium.puppeteer.launch({
  args: chromium.args,
  defaultViewport: chromium.defaultViewport,
  executablePath: binary,
  headless: chromium.headless
});

const browserB = await chromium.puppeteer.launch({
  args: chromium.args,
  defaultViewport: chromium.defaultViewport,
  executablePath: binary,
  headless: chromium.headless
});
```

But I've never actually tested this scenario so use it with caution.
