### ISSUE TITLE
Failed to connect to the host via ssh: Shared connection

### ISSUE THREAD

**Issue by HareshChhelana** [alixaxel/chrome-aws-lambda#89]
TASK [Cloning Depot Tools] *******************************************************************************************************************
changed: [XX.XX.XX.XX]

TASK [Resolving Chromium Revision from Puppeteer Version] ************************************************************************************
ok: [XX.XX.XX.XX]

TASK [Resolving Git Commit from Chromium Revision] *******************************************************************************************
ok: [XX.XX.XX.XX]

TASK [Fetching Chromium] *********************************************************************************************************************
fatal: [XX.XX.XX.XX]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: Shared connection to XX.XX.XX.XX closed.", "unreachable": true}

PLAY RECAP ***********************************************************************************************************************************
127.0.0.1                  : ok=6    changed=2    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
XX.XX.XX.XX                : ok=8    changed=5    unreachable=1    failed=0    skipped=0    rescued=0    ignored=0   

Adding more details 
fatal: [XX.XX.XX.XX]: UNREACHABLE! => {
    "changed": false, 
    "msg": "Failed to connect to the host via ssh: OpenSSH_7.6p1 Ubuntu-4ubuntu0.3, OpenSSL 1.0.2n  7 Dec 2017\r\ndebug1: Reading configuration data /etc/ssh/ssh_config\r\ndebug1: /etc/ssh/ssh_config line 19: Applying options for *\r\ndebug1: auto-mux: Trying existing master\r\ndebug2: fd 3 setting O_NONBLOCK\r\ndebug2: mux_client_hello_exchange: master version 4\r\ndebug3: mux_client_forwards: request forwardings: 0 local, 0 remote\r\ndebug3: mux_client_request_session: entering\r\ndebug3: mux_client_request_alive: entering\r\ndebug3: mux_client_request_alive: done pid = 11404\r\ndebug3: mux_client_request_session: session request sent\r\ndebug1: mux_client_request_session: master session id: 2\r\ndebug3: mux_client_read_packet: read header failed: Broken pipe\r\ndebug2: Control master terminated unexpectedly\r\nShared connection to XX.XX.XX.XX closed.", 
    "unreachable": true
}

**Comment by alixaxel** [comment]
@HareshChhelana The Ansible playbook launches a new EC2 Spot Instance:

https://github.com/alixaxel/chrome-aws-lambda/blob/ac73d95adcc96262125d41d9fafdf3720cc8fe32/_/ansible/plays/chromium.yml#L38-L60

The target hourly cost is limited to 0.75 USD.

Based on supply/demand it might not be enough to hold the instance for the entire duration of the play.

I assume that your spot instance was shutdown because of this, therefore it's not a bug.
