### ISSUE TITLE
[BUG] Multiple text lines on canvas are overlapped

### ISSUE THREAD

**Issue by gihanw** [alixaxel/chrome-aws-lambda#91]
## Environment
* `chrome-aws-lambda` Version: 2.0.1
* `puppeteer` / `puppeteer-core` Version:  2.0.0
* OS: Amazon Linux 2
* Node.js Version: 10.x
* Lambda / GCF Runtime: nodejs10.x

## Expected Behavior
![expected](https://user-images.githubusercontent.com/1883686/71893271-2466be00-3171-11ea-90b0-7f95d0f04d49.png)

Text lines are not overlapped. (This image is rendered from my PC which is running debian linux)

## Current Behavior
![chrome-aws-lambda-image](https://user-images.githubusercontent.com/1883686/71893253-19ac2900-3171-11ea-8449-23e0d0002364.jpg)

Text lines are overlapped when running on aws lambda.

## Possible Solution
N/A

## Steps to Reproduce
Render text element on canvas with multiple lines separated by the new line character. For example: '7.1%\nFLR{sub|95}'

**Note**: These graphics are rendered from [echarts](https://echarts.apache.org/en/option.html#title) charting library.

**Comment by alixaxel** [comment]
@gihanw If you could share some repro that would be helpful to hone down the issue, but at first sight it seems and without more information, it seems that your local Debian is rendering the text with a different font-face than the one available on Lambda (note the curvature on the 7).

By default, Lambda ships only with **DejaVu** font on Node 8.x runtime, and on other runtimes this package bundles **Roboto** font-face. I recommend you check which font is being used to render the SVG on your local setup and provision that same font on the Lambda using the [`font()`](https://github.com/alixaxel/chrome-aws-lambda#fonts) method.
