### ISSUE TITLE
Non-English characters are showing as rectangle boxes

### ISSUE THREAD

**Issue by swngarg1308** [alixaxel/chrome-aws-lambda#94]
### Steps to reproduce

**Environment Details:**

* Puppeteer version: puppeteer-core : 2.0.0
* Platform / OS version: AWS Lambda
* URLs (if applicable): http://dir.hinkhoj.com
* Node.js version: 10

_Code that reproduces the issue._
```
  const browserConfig = {
    args: chromium.args,
    defaultViewport: chromium.defaultViewport,
    executablePath: await chromium.executablePath,
    headless: chromium.headless
  }
  console.log('launching the browser');
  browser = await puppeteer.launch(browserConfig);

  const page = await browser.newPage();
  await page.goto('http://dir.hinkhoj.com');

  await page.screenshot({fullPage: true});
```

**What is the expected result?**
Website contains Hindi language fonts which are not rendering.

**What happens instead?**
It's showing Hindi fonts as rectangle boxes. It's happening on AWS Lambda only.

**Comment by trujillm** [comment]
@swngarg1308 
if you are on node10 and AWS lambda are you using Amazon linux 2? If so is chromium launching for you? I am unable to get it to launch and just made the move to node 10 on lambda as well.

**Comment by swngarg1308** [comment]
@trujillm Yes, I'm running node10 with default runtime. Chromium is launching in headless mode and screenshots are generating. the only issue is that it's not rendering non-english fonts.

**Comment by alixaxel** [comment]
@swngarg1308 The reason is the lack of full Unicode support in the available fonts.

In Node 10 / 12, the only available font is Roboto, which might not have the characters your need.

On Node 8, the only available font is DejaVu which might have the same issue.

I suggest you use the [`font()`](https://github.com/alixaxel/chrome-aws-lambda#fonts) method to provision the fonts your need for your specific use case.

@trujillm It should work on either runtime, open an issue if it's not working for you.

**Comment by yashutanna** [comment]
@swngarg1308 were you able to successfully move past this issue by using `font()`?

I seem to be having the same issue with Chinese characters

**Comment by theashishranjan** [comment]
@yashutanna : I was able to solve this rectangle boxes thing for Devanagari characters using `fonts()`

```javascript
const browser = await puppeteer.launch({
    args: chromium.args,
    defaultViewport: chromium.defaultViewport,
    font: await chromium.font('https://rawcdn.githack.com/.../NotoSansDevanagari/NotoSansDevanagari-Regular.ttf'),
    executablePath: await chromium.executablePath,
    headless: true
});
```
and then in my HTML/CSS, I declared a font-face for the same
```css
@font-face {
   font-family: 'NotoSansDevanagari';
   src: url('NotoSansDevanagari-Regular.ttf')  format('truetype');
}
```

**Comment by alixaxel** [comment]
@theashishranjan Your syntax is off, should be:

```js
await chromium.font('https://rawcdn.githack.com/.../NotoSansDevanagari/NotoSansDevanagari-Regular.ttf');
await chromium.font('yetAnotherFont.ttf');

const browser = await puppeteer.launch({
    args: chromium.args,
    defaultViewport: chromium.defaultViewport,
    executablePath: await chromium.executablePath,
    headless: true
});
```

**Comment by swngarg1308** [comment]
@yashutanna `chromium.font` always works when you know which font you're targeting. 
In my use-case, i needed to provide support for all possible fonts. If we use `chromium.font` for all the fonts it'll delay my execution until all fonts are loaded. So i solved this using the following approach
1. Create a folder `fonts` in root of lambda function
2. Put all fonts in this folder 
3. In you code add these lines before launch

```js
process.env.HOME = '/tmp';

if (!fs.existsSync('/tmp/.fonts')) { 
    fs.mkdirSync('/tmp/.fonts');
}

const files = fs.readdirSync('/var/task/fonts');

for (let i = 0; i < files.length; i++) {
    await copy('/var/task/fonts/' + files[i], '/tmp/.fonts/' + files[i]);
}


----------------------------------------------
// copy file from source to destination
async function copy(source, destination) {
  return new Promise((resolve) => {
      fs.copyFile(source, destination, (err) => {
          resolve()
      });
  });
}

**Comment by alixaxel** [comment]
@swngarg1308 Since version 3.0.4 the `font` method accepts paths to local files too and it will symlink them into the correct directory (which should be faster than copying them).

**Comment by robertu7** [comment]
this works for me:

```js
// load fonts
await chromium.font('/var/task/fonts/NotoSerifTC-Light.otf');
await chromium.font('/var/task/fonts/NotoSerifTC-Medium.otf');
await chromium.font('/var/task/fonts/NotoSerifTC-Regular.otf');


// init puppeteer
browser = await puppeteer.launch({
...
...
```

**Comment by manoj5464** [comment]
thanks its working
