### ISSUE TITLE
Unknown application error occurred\nRuntime.UserCodeSyntaxError

### ISSUE THREAD

**Issue by JeevanEashwar** [alixaxel/chrome-aws-lambda#95]
Hi, 
I am getting an `Unknown application error occurred\nRuntime.UserCodeSyntaxError` while importing chrome-aws-lambda module in an aws lamda function using node js. However, it works fine when imported in a regular node function. 

Upon some search i found this [thread](https://stackoverflow.com/a/58047481) which says the import syntax that was causing the SyntaxError exceptions. 

This is how i am importing.
`const chromium = require("chrome-aws-lambda");`

can someone please help with this issue.

**Comment by alixaxel** [comment]
@JeevanEashwar The way you're requiring the module is perfectly fine and it shouldn't be the culprit.

I suggest you add more context to this issue so that it's reproducible. Feel free to reopen then.

**Comment by dungeon2567** [comment]
i`m having this problem too. I`m using docker and nodejs14.
