### ISSUE TITLE
Amazon linux 2 getting Error: socket hang up 

### ISSUE THREAD

**Issue by trujillm** [alixaxel/chrome-aws-lambda#96]
Background: 
I have this code working in AWS linux AMI with node 8 for lambda. Since Amazon has discontinued node 8 in lambda I have been working on transitioning to node 10 which now uses the Amazon linux 2. Since upgrading I have been unable to get past the error: socket hang up issue.

Version sets:
Node version = v10.18.1
chrome-aws-lambda version = 2.0.2
puppeteer version = 2.0.0
AWS linux version = Amazon Linux release 2 (Karoo)

Snippet of code:
```
console.log('start 1')
try {
        // create the browser session and page. Then go to url 
        const browser = await puppeteer.launch({
            // devtools: true
            args: chrome.args,
            defaultViewport: chrome.defaultViewport,
            executablePath: await chrome.executablePath,
            headless: chrome.headless,   
        })

        console.log('start 2')

        const page = await browser.newPage()

        console.log('starting browser logic')

        // set page timeout out milisecods, currently 2
        page.setDefaultTimeout(pageTimeOut)
        
        // goes to webpage waits for network traffic to die off
        const [startPage] = await Promise.all([
            page.goto(url),
            page.waitForNavigation({waitUntil: "networkidle0"})
        ])
```

Error:
The Error occurs at await puppeteer.launch
```
bash-4.2# node run.js
starting check: LoginCheck
start 1
ErrorEvent {
  target:
   WebSocket {
     domain: null,
     _events:
      [Object: null prototype] { open: [Function], error: [Function] },
     _eventsCount: 2,
     _maxListeners: undefined,
     readyState: 3,
     protocol: '',
     _binaryType: 'nodebuffer',
     _closeFrameReceived: false,
     _closeFrameSent: false,
     _closeMessage: '',
     _closeTimer: null,
     _closeCode: 1006,
     _extensions: {},
     _receiver: null,
     _sender: null,
     _socket: null,
     _isServer: false,
     _redirects: 0,
     url:
      'ws://127.0.0.1:41553/devtools/browser/cd72d3b1-e70e-4a34-aa65-351ef1857587',
     _req: null },
  type: 'error',
  message: 'socket hang up',
  error:
   { Error: socket hang up
       at createHangUpError (_http_client.js:323:15)
       at Socket.socketOnEnd (_http_client.js:426:23)
       at Socket.emit (events.js:203:15)
       at Socket.EventEmitter.emit (domain.js:448:20)
       at endReadableNT (_stream_readable.js:1145:12)
       at process._tickCallback (internal/process/next_tick.js:63:19) code: 'ECONNRESET' } }
```

**Comment by trujillm** [comment]
I was able to resolve this by installing the following packages. 

gcc-c++ openssl-devel python27 cyrus-sasl-devel ca-certificates lz4-devel gcc zlib-devel glibc-devel
pango.x86_64 libXcomposite.x86_64 libXcursor.x86_64 libXdamage.x86_64 libXext.x86_64 libXi.x86_64 libXtst.x86_64 cups-libs.x86_64 libXScrnSaver.x86_64 libXrandr.x86_64 alsa-lib.x86_64 gtk3.x86_64 xorg-x11-fonts-100dpi xorg-x11-utils xorg-x11-fonts-Type1 xorg-x11-fonts-misc xorg-x11-fonts-cyrillic xorg-x11-fonts-75dpi ipa-gothic-fonts atk.x86_64 GConf2.x86_64 avahi.x86_64

**Comment by buresmi7** [comment]
@trujillm please give more details, how to install packages.

**Comment by don-aot** [comment]
Experiencing the same issue. How we can add the above packages? @alixaxel @trujillm

**Comment by trujillm** [comment]
@alixaxel @don-aot you can install with yum. See above solution I modified.

**Comment by Hideman85** [comment]
Hi @trujillm I'm getting the same issue as you.

I try to make a lambda layer for nodejs12 and got this issue. I try locally in my docker image of amazonlinux2 and has also this issue but the package list you provided solve it.

My question is what should I ship in my layer archive to get in working?
