### ISSUE TITLE
Need to load Chinese, Arabian ..etc fonts from local directory

### ISSUE THREAD

**Issue by kesavankrishnan** [alixaxel/chrome-aws-lambda#97]
How can we load custom font from local directory inside lambda code

**Comment by alixaxel** [comment]
@kesavankrishnan On Node 10/12 you can simply copy / symlink your fonts into `/tmp/aws/.fonts/`.

Bare in mind that this folder structure is only created after `executablePath` resolves.

**Comment by kesavankrishnan** [comment]
I copied all my fonts into /tmp/aws/.fonts directory but still fonts not loaded.

**Comment by alixaxel** [comment]
@kesavankrishnan Without a repro, there's little I can do to support you further.

Are you able to share some code and/or deployment package?

**Comment by kesavankrishnan** [comment]
I used this code to copy all my fonts to tmp directory.
await fs.copy('./fonts', '/tmp/aws/.fonts');
And the list of fonts in tmp after i copied,

Roboto
LICENSE_OFL.txt
NotoSans-Black.ttf
NotoSans-BlackItalic.ttf
NotoSans-Bold.ttf
NotoSans-BoldItalic.ttf
NotoSans-Condensed.ttf
NotoSans-CondensedBlack.ttf
NotoSans-CondensedBlackItalic.ttf
NotoSans-CondensedBold.ttf
NotoSans-CondensedBoldItalic.ttf
NotoSans-CondensedExtraBold.ttf
NotoSans-CondensedExtraBoldItalic.ttf
NotoSans-CondensedExtraLight.ttf
NotoSans-CondensedExtraLightItalic.ttf
NotoSans-CondensedItalic.ttf
NotoSans-CondensedLight.ttf
NotoSans-CondensedLightItalic.ttf
NotoSans-CondensedMedium.ttf
NotoSans-CondensedMediumItalic.ttf
NotoSans-CondensedSemiBold.ttf
NotoSans-CondensedSemiBoldItalic.ttf
NotoSans-CondensedThin.ttf
NotoSans-CondensedThinItalic.ttf
NotoSans-ExtraBold.ttf
NotoSans-ExtraBoldItalic.ttf
NotoSans-ExtraCondensed.ttf
NotoSans-ExtraCondensedBlack.ttf
NotoSans-ExtraCondensedBlackItalic.ttf
NotoSans-ExtraCondensedBold.ttf
NotoSans-ExtraCondensedBoldItalic.ttf
NotoSans-ExtraCondensedExtraBold.ttf
NotoSans-ExtraCondensedExtraBoldItalic.ttf
NotoSans-ExtraCondensedExtraLight.ttf
NotoSans-ExtraCondensedExtraLightItalic.ttf
NotoSans-ExtraCondensedItalic.ttf
NotoSans-ExtraCondensedLight.ttf
NotoSans-ExtraCondensedLightItalic.ttf
NotoSans-ExtraCondensedMedium.ttf
NotoSans-ExtraCondensedMediumItalic.ttf
NotoSans-ExtraCondensedSemiBold.ttf
NotoSans-ExtraCondensedSemiBoldItalic.ttf
NotoSans-ExtraCondensedThin.ttf
NotoSans-ExtraCondensedThinItalic.ttf
NotoSans-ExtraLight.ttf
NotoSans-ExtraLightItalic.ttf
NotoSans-Italic.ttf
NotoSans-Light.ttf
NotoSans-LightItalic.ttf
NotoSans-Medium.ttf
NotoSans-MediumItalic.ttf
NotoSans-Regular.ttf
NotoSans-SemiBold.ttf
NotoSans-SemiBoldItalic.ttf
NotoSans-SemiCondensed.ttf
NotoSans-SemiCondensedBlack.ttf
NotoSans-SemiCondensedBlackItalic.ttf
NotoSans-SemiCondensedBold.ttf
NotoSans-SemiCondensedBoldItalic.ttf
NotoSans-SemiCondensedExtraBold.ttf
NotoSans-SemiCondensedExtraBoldItalic.ttf
NotoSans-SemiCondensedExtraLight.ttf
NotoSans-SemiCondensedExtraLightItalic.ttf
NotoSans-SemiCondensedItalic.ttf
NotoSans-SemiCondensedLight.ttf
NotoSans-SemiCondensedLightItalic.ttf
NotoSans-SemiCondensedMedium.ttf
NotoSans-SemiCondensedMediumItalic.ttf
NotoSans-SemiCondensedSemiBold.ttf
NotoSans-SemiCondensedSemiBoldItalic.ttf
NotoSans-SemiCondensedThin.ttf
NotoSans-SemiCondensedThinItalic.ttf
NotoSans-Thin.ttf
NotoSans-ThinItalic.ttf

**Comment by alixaxel** [comment]
@kesavankrishnan Where is `fs.copy` coming from?

**Comment by kesavankrishnan** [comment]
@alixaxel here,
**fs         = require('fs-extra'),**
const browser = await chromium.puppeteer.launch({
args: chromium.args,
defaultViewport: chromium.defaultViewport,
executablePath: await chromium.executablePath,
headless: chromium.headless,
ignoreHTTPSErrors: true
});

and **'./fonts'** is my font directory which i has with source code,

**await fs.copy('./fonts', '/tmp/aws/.fonts');**

here its my directory structure,
fonts
node_modules
index.js
package.json
package-lock.json
template.yaml

**Comment by kesavankrishnan** [comment]
@alixaxel Its works in real aws environment. Before i tried with SAM CLI in local system.
Thanks for the update.

**Comment by timminkov** [comment]
If I copy my fonts the way they do above, I'm unable to launch the browser anymore due to a missing `libnss3` error.

**Comment by eggp** [comment]
@timminkov fonts directory just container ttf files! I have your erros, when delete license.txt , this work! 

Sry my english is very bad :(

**Comment by kesavankrishnan** [comment]
> If I copy my fonts the way they do above, I'm unable to launch the browser anymore due to a missing `libnss3` error.

@timminkov Is that issue fixed.?
